/* Cinematography & Visual Style Knowledge Base — style cards + tag-based search engine */
/* For two-round KB retrieval in storyboard / visual direction pipelines */
/* Expanded: 2026-08-03 — 155+ entries across 6 categories */

export interface VisualCard {
  name: string;
  tags: string;
  category: string;
  era: string;
  signature: string;
  bestFor: string;
}
const ALL_VISUAL_CARDS: VisualCard[] = [
  // ═══════════════════════════════════════════
  // Cinematographers (55)
  // ═══════════════════════════════════════════
  // ── Western Masters (14) ──
  { name: 'Roger Deakins', tags: 'naturalistic-lighting,soft-key,single-source,practical-motivated,color-simplicity,negative-fill,atmospheric-noir', category: 'cinematographer', era: 'contemporary', signature: 'Single-source key + negative fill — simplicity is the ultimate complexity', bestFor: 'naturalistic-drama,epic-landscape,thriller,war-film' },
  { name: 'Chivo Lubezki', tags: 'natural-light-only,wide-angle-intimacy,fluid-long-take,golden-hour,organic-camera,kinetic-energy', category: 'cinematographer', era: 'contemporary', signature: 'All-natural light + wide-angle intimacy + fluid long takes — light IS the story', bestFor: 'natural-light-epic,survival-drama,immersive-war,cosmic-awe' },
  { name: 'Bradford Young', tags: 'dark-skin-exposure,shadow-as-subject,color-temperature-contrast,african-aesthetic,negative-space-light,intimate-darkness', category: 'cinematographer', era: 'contemporary', signature: 'Redefined exposure — dark skin as light anchor — shadow = narrative subject', bestFor: 'intimate-drama,african-american-narrative,sci-fi-atmosphere,emotional-darkness' },
  { name: 'Vittorio Storaro', tags: 'color-philosophy,chiaroscuro,operatic-lighting,shadow-drama,goethe-color-theory,dialectical-light', category: 'cinematographer', era: 'classic-hollywood', signature: 'Writing with Light — each film has its own color philosophy system', bestFor: 'historical-epic,psychological-drama,color-as-metaphor,operatic-scale' },
  { name: 'Greig Fraser', tags: 'led-volume,low-light-digital,atmospheric-haze,silhouette,dune-desert-light,scifi-texture', category: 'cinematographer', era: 'contemporary', signature: 'LED Volume revolution + low-light digital + silhouette storytelling', bestFor: 'sci-fi-epic,atmospheric-world-building,low-light-thriller,scale-landscape' },
  { name: 'Janusz Kaminski', tags: 'bleach-bypass,desaturated-palette,atmospheric-diffusion,backlight-halo,historical-grit,emotional-light-movement', category: 'cinematographer', era: 'contemporary', signature: 'Bleach Bypass + atmospheric diffusion — visual encoding of historical texture', bestFor: 'historical-epic,war-drama,emotional-realist,holocaust,memory-narrative' },
  { name: 'Hoyte van Hoytema', tags: 'imax-narrative,large-format,subjective-camera,intimacy-through-scale,practical-firelight,spherical-purity', category: 'cinematographer', era: 'contemporary', signature: 'IMAX as emotional tool — intimacy in giant format + practical firelight', bestFor: 'epic-intimacy,historical-scale,war-drama,sci-fi-humanism' },
  { name: 'Claudio Miranda', tags: 'hdr-first,digital-color-grade,ocean-light,holographic-realism,high-contrast-digital', category: 'cinematographer', era: 'contemporary', signature: 'HDR-native thinking + ocean/water/reflection obsession — digital color pioneer', bestFor: 'ocean-adventure,action-aerial,digital-future,high-contrast-hdr' },
  { name: 'Darius Khondji', tags: 'texture-obsession,chemical-process,film-stock-experiment,shadow-detail,oneiric-quality,degraded-beauty', category: 'cinematographer', era: 'contemporary', signature: 'Texture alchemy — chemical processes + beauty of decay — shadows have color not black', bestFor: 'psychological-thriller,urban-decay,dream-sequence,period-romance' },
  { name: 'Matthew Libatique', tags: 'kinetic-camera,dynamic-movement,club-lighting,neon-noir,handheld-energy,color-contamination', category: 'cinematographer', era: 'contemporary', signature: 'Camera as heartbeat — always moving — neon color contamination', bestFor: 'psychological-intensity,dance-performance,music-drama,neon-night-urban' },
  { name: 'Rachel Morrison', tags: 'female-gaze,intimate-naturalism,skin-tone-fidelity,subjective-light,grounded-superhero', category: 'cinematographer', era: 'contemporary', signature: 'Intimate naturalism + skin-tone fidelity — breaking the male gaze', bestFor: 'intimate-epic,emotional-realism,female-protagonist,grounded-action' },
  { name: 'Robert Richardson', tags: 'hot-top-light,hard-shadow,theatrical-contrast,spotlight-drama,blown-highlights,intentional-overexposure', category: 'cinematographer', era: 'contemporary', signature: 'Hot top-light + intentional overexposure — extreme expressionism', bestFor: 'historical-drama,expressionist-style,theatrical-tension,action-spectacle' },
  { name: 'Rodrigo Prieto', tags: 'color-precision-grit,film-chemistry,analog-digital-hybrid,cultural-accuracy,texture-contrast,emotional-palette-shift', category: 'cinematographer', era: 'contemporary', signature: 'Film + digital hybrid — switching media = switching emotion', bestFor: 'historical-epic,cultural-drama,dual-timeline,period-contemporary-mix' },
  { name: 'Linus Sandgren', tags: 'single-camera-immersion,soft-atmosphere,romantic-light,vaseline-lens,period-texture,panavision-love', category: 'cinematographer', era: 'contemporary', signature: 'Single-camera + anamorphic + Vaseline filter — velvet romance', bestFor: 'musical-romance,period-spectacle,emotional-color-arc,soft-atmosphere' },
  // ── Classic Hollywood & New Hollywood Legends (10) ──
  { name: 'Gordon Willis', tags: 'prince-of-darkness,underexposure-mastery,chiaroscuro-extreme,top-light-only,shadow-as-character,minimalist-drama', category: 'cinematographer', era: 'new-hollywood', signature: 'Prince of Darkness — underexposed chiaroscuro + top-light only — shadow = moral ambiguity 黑暗王子/极低曝光顶光/暗影=道德模糊', bestFor: 'mafia-epic,psychological-drama,moral-ambiguity,low-key-noir,conspiracy-thriller' },
  { name: 'Gregg Toland', tags: 'deep-focus-revolution,ceilinged-sets,wide-angle-depth,low-angle-authority,citizen-kane-look,technical-innovation', category: 'cinematographer', era: 'classic-hollywood', signature: 'Deep focus revolution — everything in frame sharp simultaneously — ceilings on sets for the first time 深焦革命/全画幅清楚/首次在天花板下布光', bestFor: 'political-drama,power-dynamics,architectural-space,deep-stage,expressionist-noir' },
  { name: 'James Wong Howe', tags: 'low-key-noir-pioneer,deep-focus-interior,handheld-newsreel,crab-dolly-inventor,chinese-hollywood,shadow-psychology', category: 'cinematographer', era: 'classic-hollywood', signature: 'Newsreel handheld + low-key noir pioneer — invented the crab dolly — shadow = psychology 新闻手持/暗调先驱/螃蟹车发明者/阴影=心理', bestFor: 'boxing-drama,noir-psychological,newsreel-style,urban-night,shadow-portrait' },
  { name: 'Robert Surtees', tags: 'epic-widescreen,ben-hur-scale,technicolor-grandeur,outdoor-super-production,chariot-light,panoramic-vista', category: 'cinematographer', era: 'classic-hollywood', signature: 'Epic widescreen grandeur — Technicolor + 65mm — the biggest canvas possible 史诗宽银幕/Technicolor+65mm/最大画布', bestFor: 'biblical-epic,roman-history,chariot-action,widescreen-spectacle,period-grandeur' },
  { name: 'Freddie Young', tags: 'desert-epic-light,70mm-grandeur,mirage-heat,lawrence-sun,panoramic-nature,wide-angle-epic', category: 'cinematographer', era: 'classic-hollywood', signature: 'Desert as light sculpture — 70mm mirage — the sun IS the key light 沙漠即光雕/70mm海市蜃楼/太阳是主光', bestFor: 'desert-epic,historical-biography,arabian-landscape,mirages,70mm-spectacle' },
  { name: 'Raoul Coutard', tags: 'french-new-wave,handheld-liberation,available-light-street,jump-cut-light,natural-camera,newsreel-aesthetic', category: 'cinematographer', era: '20th-century', signature: 'French New Wave liberation — handheld + natural light — the street is the studio 法国新浪潮解放/手持+自然光/街头即影棚', bestFor: 'urban-romance,french-new-wave,street-realism,improvised-light,documentary-feel' },
  { name: 'Sven Nykvist', tags: 'nordic-naturalism,soft-diffused-light,window-light-reverence,winter-light,human-face-landscape,bergman-intimacy', category: 'cinematographer', era: '20th-century', signature: 'Naturalism as philosophy — Scandinavian light, faces as landscapes, no artifice 北欧自然主义/软扩散光/面孔即风景/零人工', bestFor: 'intimate-drama,psychological-portrait,winter-landscape,spiritual-crisis,chamber-film' },
  { name: 'Néstor Almendros', tags: 'magic-hour-pioneer,available-light-only,natural-source,candlelight-scene,practical-motivation,lyrical-simplicity', category: 'cinematographer', era: 'new-hollywood', signature: 'Magic hour pioneer — all available light — simplicity = the highest sophistication 魔幻时刻先驱/全可用光/简单即最高精炼', bestFor: 'period-rural,romantic-landscape,golden-hour,poetic-naturalism,immersive-nature' },
  { name: 'Vilmos Zsigmond', tags: 'flashing-technique,desaturated-pastel,smoke-diffusion,period-authenticity,low-contrast-print,american-70s', category: 'cinematographer', era: 'new-hollywood', signature: 'Flashing — pre-exposing film to reduce contrast — smoke + desaturation = memory texture 预曝光降反差/烟+去饱和=回忆质感', bestFor: 'period-1970s,war-trauma,small-town-america,sci-fi-realist,western-revisionist' },
  { name: 'Owen Roizman', tags: 'documentary-realism,available-light-urban,handheld-energy,new-york-grit,location-light,car-chase-night', category: 'cinematographer', era: 'new-hollywood', signature: 'Documentary realism + handheld energy — New York streets lit by what is there 纪实写实/手持能量/纽约街灯即光源', bestFor: 'urban-crime,car-chase,new-york-drama,exorcism-horror,documentary-style' },
  // ── Contemporary Western Masters (16) ──
  { name: 'Conrad Hall', tags: 'naturalistic-elegance,single-source-beauty,shadow-gradation,emotional-darkness,interior-intimacy,light-movement', category: 'cinematographer', era: 'new-hollywood', signature: 'Light as emotional movement — shadows with infinite gradation — naturalism as elegance 光即情感运动/无限灰度阴翳/自然即优雅', bestFor: 'period-drama,father-son-story,crime-noir,american-gothic,intimate-epic' },
  { name: 'Robert Elswit', tags: 'desert-light,oil-field-grit,wide-lens-landscape,practical-fire,period-texture-accuracy,american-frontier', category: 'cinematographer', era: 'contemporary', signature: 'Desert light + wide lens + practical fire — the American landscape as moral battlefield 沙漠光/广角/实地火焰/美国风景即道德战场', bestFor: 'frontier-epic,period-drama,industrial-grit,american-landscape,character-study' },
  { name: 'Caleb Deschanel', tags: 'painterly-cinematography,backlight-halo,smoke-atmosphere,religious-iconography,animal-vision,lyrical-realist', category: 'cinematographer', era: 'contemporary', signature: 'Painterly style — every frame composed like oil on canvas — backlight = divine 绘画风/背光光环/烟氛/每帧如油画', bestFor: 'religious-epic,nature-drama,coming-of-age,historical-biopic,animal-story' },
  { name: 'John Toll', tags: 'natural-light-epic,landscape-as-character,weather-emotional,golden-hour-mastery,organic-war,panavision-wide', category: 'cinematographer', era: 'contemporary', signature: 'Natural light only — epic landscapes shot like nature documentaries — available light = truth 纯自然光/史诗风景/可用光即真理', bestFor: 'historical-epic,nature-war,period-landscape,organic-action,frontier' },
  { name: 'John Seale', tags: 'desert-action-heat,orange-teal-extreme,practical-vehicle-light,kinetic-landscape,multi-camera-action,digital-pioneer-old', category: 'cinematographer', era: 'contemporary', signature: 'Desert heat + orange/teal extreme + practical action lighting — the landscape fights with you 沙漠热浪/橙青极致/实地动作光/风景与你搏斗', bestFor: 'desert-action,post-apocalyptic,road-war,kinetic-epic,vehicle-chase' },
  { name: 'Michael Ballhaus', tags: '360-degree-camera,circular-movement,energetic-flow,scorsese-collaboration,german-precision,fassbinder-color', category: 'cinematographer', era: 'contemporary', signature: '360-degree camera movement — the world spins around the character — energy = story 360度旋转运镜/世界绕角色转动/能量即叙事', bestFor: 'urban-crime,psychological-spiral,kinetic-drama,german-expressionist' },
  { name: 'Bill Pope', tags: 'green-matrix-tint,comic-book-color,vfx-integration-pioneer,bullet-time-lighting,action-compositing,digital-hybrid', category: 'cinematographer', era: 'contemporary', signature: 'VFX-native cinematography — comic book color + bullet-time lighting — reality is adjustable 特效原生摄影/漫画色彩/子弹时间布光/现实可调', bestFor: 'sci-fi-action,comic-adaptation,vfx-heavy,stylized-action,digital-world' },
  { name: 'Bruno Delbonnel', tags: 'color-expressionism,unconventional-palette,amber-green-world,stylized-reality,light-as-emotion,french-poetic', category: 'cinematographer', era: 'contemporary', signature: 'Color expressionism — amber/green/sepia worlds — light = emotional distortion of reality 色彩表现主义/琥珀绿棕世界/光即情感扭曲', bestFor: 'fantasy-romance,stylized-period,emotional-fable,poetic-color,whimsical-drama' },
  { name: 'Slawomir Idziak', tags: 'color-filter-extreme,green-blue-isolation,subjective-color,philosophical-light,polish-expressionist,three-colors', category: 'cinematographer', era: 'contemporary', signature: 'Color as philosophical instrument — green/blue filters = subjective emotional states 色彩即哲学工具/绿蓝滤镜=主观情绪状态', bestFor: 'philosophical-drama,emotional-isolation,arthouse-color,war-realism' },
  { name: 'Dion Beebe', tags: 'digital-pioneer,color-contrast-extreme,precision-sharpness,asian-light,action-clarity,fashion-gloss', category: 'cinematographer', era: 'contemporary', signature: 'Digital-native precision — extreme sharpness + color contrast — clarity as aesthetic 数字原生精度/极锐+色反差/清晰即美学', bestFor: 'sci-fi-action,asian-period,high-tech-thriller,fashion-gloss,digital-clean' },
  { name: 'Philippe Rousselot', tags: 'golden-interior-light,candle-chiaroscuro,river-water-light,natural-period,french-luminosity,adaptation-range', category: 'cinematographer', era: 'contemporary', signature: 'Golden interior light + water reflection mastery — period luminosity without artifice 金色室内光/水面反光/时代光泽无造作', bestFor: 'period-literary,river-nature,historical-biopic,gothic-horror,vampire-romance' },
  { name: 'Anthony Dod Mantle', tags: 'digital-revolution,mini-dv-aesthetic,dogme95,available-light-digital,low-fi-texture,experimental-sensor', category: 'cinematographer', era: 'contemporary', signature: 'Digital revolution pioneer — mini-DV to high-end — the sensor IS the film stock 数字革命先驱/传感器即新胶片', bestFor: 'digital-indie,urban-realist,slum-narrative,experimental-texture,found-footage' },
  { name: 'Haskell Wexler', tags: 'political-cinematography,documentary-truth,handheld-activism,available-light-protest,hybrid-realism,social-justice-lens', category: 'cinematographer', era: 'new-hollywood', signature: 'Camera as political witness — handheld + available light — truth over beauty 摄影机即政治见证/手持+可用光/真实胜于美', bestFor: 'social-realist,political-drama,protest-narrative,documentary-hybrid,activist-cinema' },
  { name: 'John Alcott', tags: 'candlelight-only,natural-period-light,fast-lens-pioneer,18th-century-luminosity,practical-flame,barry-lyndon-look', category: 'cinematographer', era: '20th-century', signature: 'Candlelight only — f/0.7 lens shooting by real flame — 18th century lit by 18th century light 纯烛光/f0.7镜头/18世纪由18世纪的光照亮', bestFor: 'period-candlelit,historical-intimacy,aristocratic-interior,flame-light,natural-period' },
  { name: 'Dean Cundey', tags: 'spielberg-blockbuster-light,backlight-silhouette,adventure-glow,practical-effects-light,halloween-horror,night-blue', category: 'cinematographer', era: 'contemporary', signature: 'Blockbuster glow — backlight + silhouettes + adventure light — the Spielberg look 大片光晕/背光剪影/冒险之光/斯皮尔伯格风格', bestFor: 'adventure-blockbuster,sci-fi-family,creature-horror,backlight-action,dinosaur-spectacle' },
  { name: 'Giuseppe Rotunno', tags: 'italian-epic-light,ballroom-opulence,operatic-color,decadent-interior,visconti-collaboration,candle-and-chandelier', category: 'cinematographer', era: 'classic-hollywood', signature: 'Operatic interior light — ballrooms + chandeliers — decadence lit with precision 歌剧室内光/舞厅吊灯/精确照亮的颓废', bestFor: 'historical-epic,aristocratic-ballroom,italian-period,opulent-interior,opera-scale' },
  // ── Global Contemporary (13) ──
  { name: 'Kazuo Miyagawa', tags: 'deep-focus-master,multi-camera-action,long-take-tracking,sumi-e-composition,weather-as-drama,japanese-spatial-depth', category: 'cinematographer', era: 'classic-hollywood', signature: 'Deep focus + multi-camera action + tracking mastery — every frame a sumi-e painting 深焦/多机位/长跟拍/水墨构图/黑泽明御用', bestFor: 'jidaigeki-samurai,period-epic,kinetic-action,battle-sequence,rain-snow-atmosphere' },
  { name: 'Tak Fujimoto', tags: 'psychological-close-up,horror-intimacy,subjective-camera-light,face-half-shadow,philadelphia-realist,demme-collaboration', category: 'cinematographer', era: 'contemporary', signature: 'Psychological close-up — face half-lit — the camera sees what the character fears 心理特写/半面光/摄影机看见角色恐惧', bestFor: 'psychological-horror,serial-killer-thriller,intimate-drama,courtroom,subjective-POV' },
  { name: 'Peter Biziou', tags: 'artificial-world-light,truman-show-sky,controlled-reality,studio-sunlight,seamless-fake,utopian-clean', category: 'cinematographer', era: 'contemporary', signature: 'Artificial world lighting — studio sunlight that is too perfect — reality as set design 人工世界光/过于完美的摄影棚日光/现实即布景', bestFor: 'dystopian-comedy,controlled-reality,studio-fantasy,fake-utopia,meta-narrative' },
  { name: 'Dick Pope', tags: 'turner-light,painterly-landscape,english-pastoral,weather-atmosphere,oil-painting-composition,sky-drama', category: 'cinematographer', era: 'contemporary', signature: 'Painterly cinematography — Turner skies + English pastoral — every frame = 19th century oil 绘画风格/Turner天空/每帧如19世纪油画', bestFor: 'artist-biopic,english-pastoral,period-painting,sky-atmosphere,landscape-drama' },
  { name: 'Benoît Debie', tags: 'acid-color,neon-nightmare,strobe-hallucination,gaspar-noe-collaboration,extreme-saturation,psychedelic-horror', category: 'cinematographer', era: 'contemporary', signature: 'Acid color + strobe hallucination — neon as nightmare — the retina is the target 酸色彩+频闪幻觉/霓虹即噩梦/视网膜是目标', bestFor: 'psychedelic-horror,club-nightmare,drug-sequence,extreme-color,visual-assault' },
  { name: 'Sean Bobbitt', tags: 'historical-realist,long-take-suffering,natural-light-brutal,handheld-witness,12-years-look,steadicam-empathy', category: 'cinematographer', era: 'contemporary', signature: 'Long-take witness — handheld as moral stance — the camera does not look away 长镜见证/手持即道德立场/摄影机不移开视线', bestFor: 'historical-trauma,slavery-narrative,social-realist,suffering-witness,long-take-drama' },
  { name: 'Mátyás Erdély', tags: 'shallow-focus-extreme,face-isolation,holocaust-narrow,son-of-saul-look,tunnel-vision,square-format', category: 'cinematographer', era: 'contemporary', signature: 'Extreme shallow focus — face is the whole world — background horror seen but not focused 极浅焦/面孔即整个世界/背景恐怖可见但不在焦点', bestFor: 'holocaust-drama,tunnel-vision-horror,subjective-nightmare,shallow-focus,narrow-POV' },
  { name: 'Mandy Walker', tags: 'female-epic-scale,outback-landscape,australian-light,period-color-accuracy,action-beauty,golden-desert', category: 'cinematographer', era: 'contemporary', signature: 'Female gaze on epic scale — Australian outback light — beauty in harshness 女性视角史诗/澳洲内陆光/严酷中的美', bestFor: 'female-epic,outback-landscape,australian-period,period-action,desert-beauty' },
  { name: 'Jarin Blaschke', tags: 'black-and-white-modern,orthochromatic-look,lighthouse-texture,silver-nitrate,monochrome-horror,period-BW-purity', category: 'cinematographer', era: 'contemporary', signature: 'Modern black-and-white — orthochromatic + silver nitrate texture — monochrome horror 现代黑白/正色片+硝酸银纹理/单色恐怖', bestFor: 'gothic-horror,period-BW,isolation-drama,texture-noir,expressionist-modern' },
  { name: 'Sayombhu Mukdeeprom', tags: 'thai-tropical-light,jungle-humidity,slow-cinema-nature,long-take-forest,meditative-camera,tropical-slow', category: 'cinematographer', era: 'contemporary', signature: 'Tropical slow cinema — jungle humidity visible in light — nature breathes 热带慢电影/丛林湿气可见于光/自然在呼吸', bestFor: 'tropical-drama,jungle-mystery,slow-cinema,meditative-nature,asian-contemplative' },
  { name: 'Christopher Blauvelt', tags: 'natural-light-pastoral,deep-forest-atmosphere,avail-light-interior,period-naturalism,texture-authenticity,slow-cinema-light', category: 'cinematographer', era: 'contemporary', signature: 'Pastoral naturalism — forest/field available light — texture IS the period 田园自然光/森林田野可用光/质感即时代', bestFor: 'period-pastoral,frontier-naturalism,slow-rural,intimate-western,forest-atmosphere' },
  { name: 'Bojan Bazelli', tags: 'fantasy-gothic,sorcery-light,practical-magic-glow,wizarding-world,dark-fantasy-color,underwater-sequel', category: 'cinematographer', era: 'contemporary', signature: 'Dark fantasy + sorcery light — practical magic glow — the supernatural lit from within 暗黑奇幻/魔法光/实用魔法辉光/超自然由内照亮', bestFor: 'fantasy-gothic,wizard-world,supernatural-horror,underwater-fantasy,magic-realism' },
  { name: 'Mihai Mălaimare Jr.', tags: 'slow-motion-light,ballet-camera,precision-movement,stylized-violence,tableau-composition,master-shot', category: 'cinematographer', era: 'contemporary', signature: 'Slow-motion ballet — violence as choreographed movement — the tableau as unit of meaning 慢镜芭蕾/暴力即编舞/画面即意义单元', bestFor: 'stylized-action,ballet-drama,slow-motion,surreal-tableau,choreographed-violence' },
  // ── Chinese Cinematographers (9) ──
  { name: '赵小丁 (Zhao Xiaoding)', tags: 'zhang-yimou-colorist,monochromatic-bold,chinese-red-gold,period-immersion,sweeping-aerial,ink-wash-influence', category: 'cinematographer', era: 'contemporary', signature: '张艺谋御用摄影——单色专制转化为画面——红/金/蓝的单色暴力——"英雄"黑红白绿四色分段', bestFor: 'wuxia-epic,historical-china,color-as-drama,large-scale-battle' },
  { name: '杜可风 (Christopher Doyle)', tags: 'neon-hong-kong,handheld-energy,saturated-color,drunken-master-style,available-light-push,wide-angle-portrait,step-printing-collaborator', category: 'cinematographer', era: 'contemporary', signature: '霓虹香港+手持能量+饱和色彩——"醉酒大师"式直觉运镜——POV不只是视角，是情感状态', bestFor: 'urban-noir,romantic-chaos,night-neon,handheld-intimacy' },
  { name: '罗攀 (Luo Pan)', tags: 'chinese-realism,cold-northern-light,natural-light-only,historical-texture,documentary-approach,long-take-composition', category: 'cinematographer', era: 'contemporary', signature: '中国式写实——冷北方自然光+纪录片出身——"长安十二时辰"唐代烛光/日光精确重建', bestFor: 'historical-realism,period-china,natural-light-drama,documentary-style' },
  { name: '吕乐 (Lü Yue)', tags: 'documentary-background,early-zhang-yimou,natural-light-evolution,handheld-documentary,chinese-rural-light', category: 'cinematographer', era: 'contemporary', signature: '纪录片出身——从"活着"到"一九四二"——从形式化构图到粗粝真实的进化', bestFor: 'rural-drama,historical-trauma,natural-light-period,family-epic' },
  { name: '曹郁 (Cao Yu)', tags: 'candlelight-specialist,poetic-realism,flame-flicker,low-light-digital,historical-texture,atmospheric-war', category: 'cinematographer', era: 'contemporary', signature: '烛光/篝火专家——"八佰"纯火光夜景——低光照下的历史质感——光即时间', bestFor: 'war-drama,historical-atmospheric,candlelight-scene,period-texture' },
  { name: '曾剑 (Zeng Jian)', tags: 'handheld-intimacy,available-light,urban-realist,observational-camera,subjective-pov', category: 'cinematographer', era: 'contemporary', signature: '手持亲密+完全可用光——"春风沉醉的夜晚"偷窥式跟拍——摄影机=在场者不是旁观者', bestFor: 'intimate-drama,urban-realist,observational-style,lgbtq-narrative' },
  { name: '王昱 (Wang Yu)', tags: 'delicate-atmospheric,water-reflection,urban-melancholy,soft-diffusion,poetic-commercial', category: 'cinematographer', era: 'contemporary', signature: '"苏州河"水反射美学的极致——城市倒影=人物内心——柔光+扩散+水的诗歌', bestFor: 'urban-melancholy,water-city,poetic-realist,reflection-narrative' },
  { name: '余静萍 (Yu Jingping)', tags: 'female-gaze,intimate-portrait,youth-texture,natural-light,skin-tone-fidelity,female-cinematographer', category: 'cinematographer', era: 'contemporary', signature: '女性凝视——"少年的你"特写即世界——青春肌肤质感的极致还原', bestFor: 'youth-drama,female-protagonist,intimate-portrait,coming-of-age' },
  { name: '董劲松 (Dong Jinsong)', tags: 'industrial-decay,urban-wasteland,noir-china,texture-as-emotion,bleak-beauty,rust-belt-aesthetic', category: 'cinematographer', era: 'contemporary', signature: '工业废墟美学——"白日焰火"东北衰败的黑色诗意——纹理=情绪=历史', bestFor: 'noir-thriller,industrial-decay,post-industrial-landscape,crime-drama' },
  // ── Korean Cinematographers (5) ──
  { name: '洪慶杓 (Hong Kyung-pyo)', tags: 'precise-composition,confined-space-tension,class-allegory-through-light,basement-light,architectural-cinematography', category: 'cinematographer', era: 'contemporary', signature: '寄生虫/Snowpiercer/Burning——精确构图+密闭空间张力——阶级=光线层级——地下室=无光', bestFor: 'social-thriller,confined-space,class-drama,architectural-tension' },
  { name: '金智龙 (Kim Ji-yong)', tags: 'baroque-color,symmetrical-precision,historical-korea,period-texture,erotic-composition', category: 'cinematographer', era: 'contemporary', signature: '"小姐/老男孩"——巴洛克式色彩+绝对对称——情色=构图张力——韩国古典美学的现代视觉化', bestFor: 'period-thriller,erotic-drama,baroque-visual,symmetrical-composition' },
  { name: 'Chung Chung-hoon', tags: 'park-chan-wook-regular,gothic-color,red-black-palette,stylized-violence,operatic-composition', category: 'cinematographer', era: 'contemporary', signature: '朴赞郁御用摄影——哥特色彩+红/黑暴力美学——"老男孩"走廊横移长镜头=暴力芭蕾', bestFor: 'revenge-thriller,gothic-visual,stylized-violence,operatic-drama' },
  { name: '李模介 (Lee Mo-gae)', tags: 'dark-urban,beauty-in-violence,neo-noir-korea,contrast-extreme', category: 'cinematographer', era: 'contemporary', signature: '"看见恶魔"——黑暗都市+暴力中的美——极端对比度=道德的绝对对立', bestFor: 'revenge-thriller,extreme-contrast,urban-noir,violence-as-beauty' },
  { name: 'Kim Woo-hyung', tags: 'claustrophobic-action,zombie-chaos,confined-space-horror,kinetic-energy,commercial-precision', category: 'cinematographer', era: 'contemporary', signature: '"釜山行"——密闭空间动作+僵尸混乱中的清晰——狭小空间=最大化紧张', bestFor: 'zombie-horror,action-thriller,confined-space,kinetic-action' },
  // ── Indian Cinematographers (4) ──
  { name: 'Ravi Varman', tags: 'saturated-color,epic-scale,indian-light,musical-color,period-opulence', category: 'cinematographer', era: 'contemporary', signature: '"庞尼因塞尔文"——史诗规模+印度饱和色彩——音乐剧式色彩=情感放大器', bestFor: 'historical-epic,musical-drama,period-opulence,indian-cinema' },
  { name: 'Santosh Sivan', tags: 'period-texture,natural-light-india,humanist-scale,intimate-epic,landscape-as-emotion', category: 'cinematographer', era: 'contemporary', signature: '"恐怖分子"——自然光印度+人文尺度——大地=角色——最小的故事最大的画面', bestFor: 'period-drama,natural-light,humanist-narrative,indian-landscape' },
  { name: 'P.C. Sreeram', tags: 'soft-golden-warmth,natural-light-pioneer,available-light-india,tamil-cinema-poetry,intimate-color', category: 'cinematographer', era: 'contemporary', signature: '印度自然光先驱——柔和金色温暖+可用光哲学——"Nayakan" = 印度教父的低调光影', bestFor: 'intimate-drama,natural-light,warm-palette,character-study' },
  { name: 'Sudeep Chatterjee', tags: 'period-opulence,maratha-light,epic-composition,massive-set-lighting,indian-historical', category: 'cinematographer', era: 'contemporary', signature: '"巴吉拉奥"——马拉塔帝国的奢华光影——超大场景+蜡烛/火炬混合照明——印度史诗视觉', bestFor: 'historical-epic,period-opulence,indian-historical,massive-scale' },

  // ═══════════════════════════════════════════
  // Directors (40)
  // ═══════════════════════════════════════════
  // ── Western / Global Existing (9) ──
  { name: 'Wong Kar-wai', tags: 'neon-noir,step-printing,time-lapse-emotion,saturated-color,wide-angle-portrait,smoke-and-mirror,fragmented-narrative', category: 'director', era: 'contemporary', signature: 'Step-Printing + neon palette + 24mm wide close-ups — memory made material', bestFor: 'romantic-melancholy,urban-alienation,memory-narrative,neon-atmosphere' },
  { name: 'Zhang Yimou', tags: 'color-dictatorship,monochromatic-obsession,sweeping-landscape,precision-blocking,chinese-red,figurative-symmetry', category: 'director', era: 'contemporary', signature: 'Monochromatic tyranny — each film ruled by one color + thousand-person precision blocking', bestFor: 'wuxia-epic,historical-china,color-as-power,monumental-scale' },
  { name: 'Denis Villeneuve', tags: 'megalophobia,monumental-composition,negative-space-power,slow-burn,bone-dry-color,architectural-cinema', category: 'director', era: 'contemporary', signature: 'Monumental composition + bone-dry desaturation — making the audience feel small', bestFor: 'sci-fi-epic,monumental-scale,slow-burn-thriller,existential-horror' },
  { name: 'Christopher Nolan', tags: 'temporal-structure,practical-effects,imax-realism,cross-cutting-climax,analog-purity,spiral-narrative', category: 'director', era: 'contemporary', signature: 'Time = protagonist — spiral narrative + practical > CGI + IMAX format', bestFor: 'temporal-thriller,spiral-narrative,large-format-epic,practical-action' },
  { name: 'Wes Anderson', tags: 'symmetry-dictatorship,planimetric-composition,pastel-palette,dollhouse-aesthetic,whip-pan,color-grade-as-character', category: 'director', era: 'contemporary', signature: 'Planimetric composition + absolute symmetry + pastel color swatches — every frame = graphic design', bestFor: 'stylized-comedy,fairy-tale,retro-aesthetic,whimsical-drama' },
  { name: 'David Fincher', tags: 'camera-lock,precision-framing,desaturated-green,single-point-perspective,focus-rack-psychology,digital-purity', category: 'director', era: 'contemporary', signature: 'Locked camera + desaturated green/yellow — the camera is God and God does not move', bestFor: 'psychological-thriller,crime-procedural,digital-cold,dread-atmosphere' },
  { name: 'Terrence Malick', tags: 'golden-hour-only,wandering-steadi,whisper-voiceover,nature-as-character,contre-jour,elliptical-editing', category: 'director', era: 'new-hollywood', signature: 'Golden hour only + wandering Steadicam + whisper montage — light is the breath of God', bestFor: 'poetic-drama,cosmic-contemplation,nature-spirituality,memory-montage' },
  { name: 'Paul Thomas Anderson', tags: 'virtuoso-long-take,steadicam-ballet,anamorphic-widescreen,smoke-haze-atmosphere,period-texture,character-follow', category: 'director', era: 'contemporary', signature: 'Virtuoso long takes + anamorphic widescreen + haze density — immersion over spectacle', bestFor: 'period-epic,character-study,ensemble-drama,romance-period' },
  { name: 'Andrei Tarkovsky', tags: 'sculpting-in-time,long-take-hypnosis,elemental-nature,water-fire-obsession,dream-realism,spiritual-light', category: 'director', era: '20th-century', signature: 'Sculpting in Time — ultra-long takes = experiencing time — water/fire/wind = cosmic breath', bestFor: 'spiritual-journey,slow-cinema,contemplative,elemental-landscape' },
  // ── Classic Western Masters (9) ──
  { name: 'Stanley Kubrick', tags: 'one-point-perspective,symmetrical-wide,geometric-precision,slow-zoom-horror,clinical-composition,architectural-framing', category: 'director', era: '20th-century', signature: 'One-point perspective + clinical symmetry — god is-eye geometry — every frame = mathematical proof 单点透视/临床对称/上帝视角几何/每帧=数学证明', bestFor: 'sci-fi-epic,existential-horror,historical-epic,psychological-thriller,satire' },
  { name: 'Alfred Hitchcock', tags: 'vertigo-effect,subjective-camera,suspense-POV,dolly-zoom,point-of-view-editing,visual-psychology', category: 'director', era: 'classic-hollywood', signature: 'Vertigo effect + subjective POV — the camera IS the character is fear — suspense through what you see 眩晕效果/主观POV/摄影机即角色恐惧/所见即悬念', bestFor: 'psychological-thriller,suspense-horror,subjective-POV,voyeur-narrative,paranoia' },
  { name: 'Ingmar Bergman', tags: 'extreme-close-up,human-face-landscape,stark-nordic-light,spiritual-silence,chamber-drama,existential-isolation', category: 'director', era: '20th-century', signature: 'Close-up mastery + stark Nordic light — the human face contains all of existence 特写大师/北欧硬光/人脸包含全部存在', bestFor: 'existential-drama,spiritual-crisis,chamber-piece,psychological-portrait,faith-doubt' },
  { name: 'Federico Fellini', tags: 'surreal-composition,circus-aesthetic,dream-sequence,baroque-crowd,memory-distortion,italian-baroque', category: 'director', era: '20th-century', signature: 'Surreal circus aesthetic — dreams and memory distorted through baroque composition 超现实马戏美学/梦境与记忆经巴洛克构图扭曲', bestFor: 'dream-sequence,surreal-memory,italian-baroque,carnival-atmosphere,autobiographical' },
  { name: 'Jean-Luc Godard', tags: 'jump-cut,brechtian-distance,color-pop,breaking-fourth-wall,typography-on-screen,revolutionary-form', category: 'director', era: '20th-century', signature: 'Jump cuts + Brechtian alienation + color as political statement — form IS content 跳切+布莱希特间离+色彩即政治声明/形式即内容', bestFor: 'experimental-narrative,political-cinema,urban-romance,color-experiment,meta-cinema' },
  { name: 'Akira Kurosawa', tags: 'weather-as-drama,telephoto-action,multi-camera-battle,axial-cutting,geometric-blocking,movement-as-character', category: 'director', era: '20th-century', signature: 'Weather = drama — rain/wind/snow = emotional amplifier — telephoto + multi-camera action 天气即戏剧/风雨雪=情感放大器/长焦多机位 七武士/罗生门', bestFor: 'samurai-epic,battle-sequence,weather-drama,multi-perspective,moral-parable' },
  { name: 'Yasujirō Ozu', tags: 'tatami-shot,low-camera,pillow-shots,static-composition,domestic-space,seasonal-transition,mono-no-aware', category: 'director', era: '20th-century', signature: 'Tatami-level camera + pillow shots — stillness reveals the eternal in the everyday 榻榻米高度/枕头镜头/静止揭示日常中的永恒 东京物语', bestFor: 'family-drama,domestic-space,stillness-narrative,seasonal-story,japanese-nostalgia' },
  { name: 'Kenji Mizoguchi', tags: 'flowing-long-take,floating-camera,ghost-aesthetic,scroll-painting-movement,emotional-distance,period-japan', category: 'director', era: '20th-century', signature: 'Flowing long takes — camera floats like a ghost — scroll painting unrolled in time 流动长镜/摄影机如幽灵漂浮/卷轴画在时间中展开 雨月物语', bestFor: 'ghost-story,period-japan,floating-camera,scroll-painting,supernatural-drama' },
  { name: 'Satyajit Ray', tags: 'humanist-cinema,light-through-windows,child-perspective,indian-village,universal-in-particular,economic-storytelling', category: 'director', era: '20th-century', signature: '人文主义电影——阿普三部曲——窗光+儿童视角——从最微小见最宏大——"每一帧都是一幅画"', bestFor: 'humanist-drama,coming-of-age,rural-narrative,window-light-poetry' },
  // ── Contemporary Western Masters (8) ──
  { name: 'Martin Scorsese', tags: 'kinetic-camera,rock-music-editing,long-take-virtuoso,urban-italian-american,religious-imagery,freeze-frame', category: 'director', era: 'new-hollywood', signature: 'Kinetic camera + rock rhythm editing + freeze frame — movement as moral velocity 动能摄影/摇滚节奏剪辑/定格/运动即道德速度', bestFor: 'urban-crime,gangster-epic,religious-struggle,music-driven,character-arc' },
  { name: 'Francis Ford Coppola', tags: 'operatic-family,chiaroscuro-drama,period-immersion,shadow-psychology,slow-dissolve,american-epic', category: 'director', era: 'new-hollywood', signature: 'Operatic family chiaroscuro — shadows declare moral descent — the epic in the intimate 歌剧式家族明暗/暗影宣告道德堕落/亲密中的史诗', bestFor: 'mafia-epic,family-saga,war-psychological,period-america,moral-decline' },
  { name: 'Ridley Scott', tags: 'atmospheric-world-building,smoke-haze-light,production-design-integration,epic-scale,blade-runner-noir,historical-spectacle', category: 'director', era: 'contemporary', signature: 'Atmospheric world-building + smoke/haze/rain — environment precedes character — world as protagonist 气氛世界建造/烟霾雨/环境先于角色/世界即主角', bestFor: 'sci-fi-world,historical-epic,cyberpunk,dystopian-noir,world-building' },
  { name: 'David Lynch', tags: 'surreal-suburban,dream-logic,uncanny-valley,industrial-texture,flickering-light,red-curtain,alternate-reality', category: 'director', era: 'contemporary', signature: 'Dream logic + suburban uncanny — flickering light + red curtain — the nightmare behind the picket fence 梦逻辑/郊区诡异/闪烁光+红幕/白色篱笆后的噩梦', bestFor: 'surreal-horror,psychological-mystery,dream-nightmare,small-town-uncanny,alternate-reality' },
  { name: 'Guillermo del Toro', tags: 'gothic-fairy-tale,amber-gold-light,practical-creature,clockwork-aesthetic,catholic-imagery,spanish-civil-war', category: 'director', era: 'contemporary', signature: 'Gothic fairy tale + amber/gold light + practical creatures — monsters are the real saints 哥特童话/琥珀金光/实体怪物/怪物才是真正的圣人', bestFor: 'dark-fantasy,gothic-fairy-tale,creature-design,spanish-period,war-fable' },
  { name: 'Alfonso Cuarón', tags: 'long-take-immersion,real-time-tension,space-silence,class-divide-space,social-landscape,steadicam-marathon', category: 'director', era: 'contemporary', signature: 'Long-take immersion — real-time tension — the unbroken shot as reality contract 长镜沉浸/实时紧张/不剪辑镜头即现实契约', bestFor: 'real-time-thriller,sci-fi-survival,space-drama,social-realist,long-take-mastery' },
  { name: 'Krzysztof Kieślowski', tags: 'color-filter-philosophy,visual-moral-inquiry,light-as-grace,parallel-life,intimate-epic,spiritual-realist', category: 'director', era: '20th-century', signature: 'Color as moral inquiry + light as grace — each film asks: what is the right way to live? 色彩即道德质询/光即恩典/每部电影问：怎样活才对？三色', bestFor: 'philosophical-drama,moral-inquiry,parallel-narrative,intimate-epic,color-symbolism' },
  { name: 'Werner Herzog', tags: 'ecstatic-truth,jungle-madness,operatic-nature,impossible-image,documentary-as-vision,elemental-obsession', category: 'director', era: '20th-century', signature: 'Ecstatic truth + impossible images — dragging a ship over a mountain — nature as cosmic madness 狂喜真相/不可能的画面/拉船越山/自然即宇宙疯狂', bestFor: 'jungle-nightmare,obsession-narrative,elemental-nature,documentary-as-art,visionary-landscape' },
  // ── Chinese/Korean/Asian Directors (13) ──
  { name: '陈凯歌 (Chen Kaige)', tags: 'epic-historical,theatrical-staging,poetic-realism,chinese-opera-influence,cultural-memory,forbidden-love', category: 'director', era: 'contemporary', signature: '"霸王别姬"——史诗历史+京剧舞台美学——个体命运=国家命运——"不疯魔不成活"', bestFor: 'historical-epic,cultural-memory,forbidden-romance,artistic-obsession' },
  { name: '贾樟柯 (Jia Zhangke)', tags: 'documentary-realism,long-take,social-change-through-faces,non-professional-actor,urbanization-trauma,slow-observation', category: 'director', era: 'contemporary', signature: '纪实写实+长镜头+非职业演员——社会变迁写在脸上——"三峡好人"=中国肉身', bestFor: 'social-realism,urbanization-narrative,documentary-style,slow-cinema' },
  { name: '侯孝贤 (Hou Hsiao-hsien)', tags: 'distant-observation,static-camera,nature-as-time,long-take-meditation,elliptical-narrative,taiwanese-identity', category: 'director', era: 'contemporary', signature: '远观+固定机位+自然=时间——"悲情城市"——摄影机在远处静静看着，不介入', bestFor: 'historical-memory,slow-cinema,meditative-drama,taiwanese-narrative' },
  { name: '李安 (Ang Lee)', tags: 'cross-genre-mastery,emotional-precision,repressed-desire,visual-metaphor,cultural-duality,technical-innovation', category: 'director', era: 'contemporary', signature: '跨类型掌控+情感精确——横跨武侠/科幻/家庭/战争——"每个人心中都有一座断背山"', bestFor: 'cross-genre,emotional-drama,cultural-conflict,technical-experiment' },
  { name: '朴赞郁 (Park Chan-wook)', tags: 'baroque-violence,precise-symmetry,red-black-palette,revenge-trilogy,gothic-romance,stylized-cruelty', category: 'director', era: 'contemporary', signature: '巴洛克暴力+精确对称+红/黑调——复仇三部曲——暴力=美学=道德追问', bestFor: 'revenge-thriller,baroque-visual,gothic-romance,moral-ambiguity' },
  { name: '奉俊昊 (Bong Joon-ho)', tags: 'genre-hybrid,class-allegory-through-space,stairs-as-metaphor,tonal-shift-master,unexpected-comedy,social-thriller', category: 'director', era: 'contemporary', signature: '类型混合+阶级通过空间表达——楼梯=社会层级——"寄生虫"半地下室/豪宅=韩国社会剖面', bestFor: 'social-thriller,genre-hybrid,class-drama,unexpected-tone' },
  { name: '李沧东 (Lee Chang-dong)', tags: 'humanist-realism,poetry-in-ordinary,anger-as-love,marginalized-voice,silence-as-narrative,invisible-people', category: 'director', era: 'contemporary', signature: '人文写实+日常中的诗——"燃烧"——愤怒=爱的最高形式——边缘人的尊严', bestFor: 'humanist-drama,marginalized-narrative,slow-burn,poetic-realism' },
  { name: '金基德 (Kim Ki-duk)', tags: 'minimal-dialogue,symbolic-imagery,water-metaphor,buddhist-aesthetic,isolated-character,nature-as-witness', category: 'director', era: 'contemporary', signature: '极简对话+佛教象征+水=净化与毁灭——"春夏秋冬"——孤独者与自然对峙', bestFor: 'allegorical-drama,buddhist-narrative,minimal-dialogue,water-imagery,symbolic-landscape' },
  { name: 'Sanjay Leela Bhansali', tags: 'operatic-indian,devdas-aesthetic,saturated-spectacle,chandelier-light,maximalist-emotion,musical-tragedy', category: 'director', era: 'contemporary', signature: '印度歌剧式电影——"Devdas"水晶吊灯美学——极致奢华=极致悲剧——每个镜头都是一幅细密画', bestFor: 'operatic-romance,musical-tragedy,maximalist-spectacle,period-opulence' },
  { name: 'S.S. Rajamouli', tags: 'mythological-scale,maximalist-epic,indian-mythology-modernized,kinetic-spectacle,emotional-canvas,rrr-baahubali', category: 'director', era: 'contemporary', signature: '神话尺度+极致史诗——"RRR"——神话=超级英雄=民族叙事——每场戏都是一部电影的高潮', bestFor: 'mythological-epic,action-spectacle,maximalist-action,indian-mythology' },
  { name: 'Mira Nair', tags: 'cross-cultural,monsoon-aesthetic,vibrant-palette,diaspora-narrative,indian-modernity,color-as-identity', category: 'director', era: 'contemporary', signature: '"季风婚宴"——跨文化+鲜艳色彩——离散=色彩对比——印度现代性在传统与全球间的平衡', bestFor: 'cross-cultural-drama,diaspora-narrative,vibrant-color,family-saga' },
  { name: 'Apichatpong Weerasethakul', tags: 'slow-cinema,jungle-mysticism,reincarnation-narrative,animist-aesthetic,liminal-space,thai-tropical', category: 'director', era: 'contemporary', signature: '"能召回前世的布米叔叔"——慢电影+丛林神秘主义——灵魂/前世/自然=一体——线性时间不存在', bestFor: 'slow-cinema,spiritual-narrative,jungle-atmosphere,liminal-space' },
  { name: 'Tran Anh Hung', tags: 'poetic-naturalism,food-as-cinema,scent-of-green-papaya,vietnamese-aesthetic,sensual-cinema,still-life-composition', category: 'director', era: 'contemporary', signature: '"青木瓜之味"——诗性自然主义——食物=电影——静物构图——越南的"物哀"美学', bestFor: 'poetic-drama,culinary-narrative,asian-aesthetic,sensual-cinema' },

  // ═══════════════════════════════════════════
  // Production Designers / Art Directors (22) — category added 2026-08
  // ═══════════════════════════════════════════
  // ── Chinese Production Designers (3) ──
  { name: '叶锦添 (Tim Yip)', tags: 'oriental-fantasy,tang-dynasty-reconstruction,hanfu-accuracy,fabric-as-narrative,cultural-research-driven', category: 'production-designer', era: 'contemporary', signature: '"卧虎藏龙/英雄"——东方奇幻世界构建+唐代服装精确重建——面料=叙事——文化考据驱动设计', bestFor: 'oriental-fantasy,historical-china,wuxia-world,period-accuracy' },
  { name: '张叔平 (William Chang)', tags: 'qipao-elegance,1960s-hong-kong,cheongsam-as-character,wong-kar-wai-regular,wallpaper-psychology', category: 'production-designer', era: 'contemporary', signature: '"花样年华"——旗袍=角色心理——每套旗袍是一种情绪——1960年代香港物质世界的精确重建', bestFor: 'period-romance,hong-kong-aesthetic,fashion-as-character,intimate-period' },
  { name: '种田阳平 (Yohei Taneda)', tags: 'war-torn-detail,1937-nanjing,damaged-beauty,historical-destruction,period-decay', category: 'production-designer', era: 'contemporary', signature: '"金陵十三钗/Kill Bill"——战争废墟的细节之美——破坏=叙事——被摧毁的美丽更美', bestFor: 'war-drama,period-destruction,historical-trauma,tactile-ruin' },
  // ── Western Production Designers (19) ──
  { name: 'Dante Ferretti', tags: 'fellini-scorsese-regular,dark-operatic,italian-gothic,catholic-imagery,historical-engulfing', category: 'production-designer', era: 'contemporary', signature: 'Fellini+Scorsese御用——暗调歌剧式——哥特意大利+天主教图像——空间吞噬人物', bestFor: 'operatic-drama,gothic-atmosphere,historical-epic,catholic-imagery' },
  { name: 'Rick Carter', tags: 'immersive-world,jurassic-park-legacy,avatar-pandora,future-organic,world-building-from-scratch', category: 'production-designer', era: 'contemporary', signature: '"阿凡达/侏罗纪公园"——从零构建沉浸世界——潘多拉星球的每一个植物=功能+美学双重设计', bestFor: 'sci-fi-world,fantasy-world,immersive-environment,alien-aesthetic' },
  { name: 'Sarah Greenwood', tags: 'english-literary,period-precision,dollhouse-detail,green-architecture,anna-karenina-theater,historical-immersion', category: 'production-designer', era: 'contemporary', signature: 'Period precision + dollhouse detail — literary England built as miniature universes 时代精度/娃娃屋细节/文学英国建作微缩宇宙', bestFor: 'literary-adaptation,english-period,regency-drama,dollhouse-aesthetic,green-world' },
  { name: 'Adam Stockhausen', tags: 'wes-anderson-world,miniature-precision,dollhouse-aesthetic,symmetrical-set,pastel-palette-3d', category: 'production-designer', era: 'contemporary', signature: 'Wes Anderson御用——"布达佩斯大饭店"——娃娃屋般精确——对称×粉彩×微缩模型的世界', bestFor: 'stylized-fantasy,dollhouse-aesthetic,symmetrical-design,whimsical-world' },
  { name: 'Catherine Martin', tags: 'maximalist-musical,art-deco-extreme,baz-luhrmann-regular,opulent-period,fabric-explosion', category: 'production-designer', era: 'contemporary', signature: '"红磨坊/了不起的盖茨比"——极致主义音乐剧——Art Deco推到极限——面料/珠宝/灯光的爆炸', bestFor: 'musical-epic,opulent-period,art-deco,maximalist-spectacle' },
  { name: 'Patrice Vermette', tags: 'sci-fi-realism,alien-brutalism,dune-world,minimalist-epic,desert-civilization-design', category: 'production-designer', era: 'contemporary', signature: '"沙丘/降临"——科幻现实主义——外星=极简+粗野主义——沙漠文明的每件器物都有千年历史', bestFor: 'sci-fi-epic,alien-civilization,minimalist-future,brutalist-scifi' },
  { name: 'Ken Adam', tags: 'cold-war-modernism,dr-strangelove-war-room,james-bond-villain-lair,expressionist-concrete,geometric-menace', category: 'production-designer', era: 'classic-hollywood', signature: '"奇爱博士战争室/007反派巢穴"——冷战现代主义——混凝土=威胁——几何=权力', bestFor: 'cold-war-thriller,villain-lair,expressionist-set,geometric-menace' },
  { name: 'Eugenio Caballero', tags: 'dark-fantasy-realism,fascist-brutalism,fairy-tale-grotto,mexican-gothic,war-bunker,mythological-underground', category: 'production-designer', era: 'contemporary', signature: 'Dark fairy tale realism + fascist brutalism — the grotto is both wonder and horror 暗黑童话写实/法西斯粗野/洞穴既是奇迹也是恐怖', bestFor: 'dark-fantasy,spanish-civil-war,fairy-tale-horror,underground-world,gothic-realist' },
  { name: 'Stuart Craig', tags: 'british-design,harry-potter-world,hogwarts-organic-growth,gothic-whimsy,magical-realism-set', category: 'production-designer', era: 'contemporary', signature: '哈利波特全系列——霍格沃茨=有机生长的建筑——哥特+奇想+英国寄宿学校的魔法化', bestFor: 'fantasy-world,magical-academy,gothic-whimsy,british-heritage' },
  { name: 'Bo Welch', tags: 'expressionist-suburbia,tim-burton-gothic,distorted-reality,whimsical-horror,men-in-black-sleek,outsider-aesthetic', category: 'production-designer', era: 'contemporary', signature: 'Expressionist suburbia + distorted reality — houses with emotional states — whimsy as horror 表现主义郊区/扭曲现实/有情绪的房子/异想即恐怖', bestFor: 'gothic-fantasy,suburban-uncanny,burton-world,sci-fi-comedy,expressionist-set' },
  { name: 'Mark Tildesley', tags: 'textile-interior,phantom-thread-detail,wood-panel-psychology,english-restraint,post-apocalyptic-decay,craft-as-character', category: 'production-designer', era: 'contemporary', signature: 'Textile as psychology + craft as character — the dress IS the psyche 织物即心理/手艺即角色/裙子即灵魂', bestFor: 'period-fashion,craft-drama,english-restraint,post-apocalyptic,psychological-interior' },
  { name: 'KK Barrett', tags: 'near-future-warmth,soft-sci-fi,emotional-architecture,tactile-future,where-wild-things-are,organic-tech', category: 'production-designer', era: 'contemporary', signature: 'Soft sci-fi + emotional architecture — the future is warm and tactile, not cold steel 软科幻/情感建筑/未来是温暖可触的非冷钢', bestFor: 'near-future,ai-romance,soft-sci-fi,warm-minimalism,organic-tech,tactile-world' },
  { name: 'Jeannine Oppewall', tags: 'american-period-precision,mid-century-authenticity,office-politics-space,institutional-interior,la-noir,suburban-realism', category: 'production-designer', era: 'contemporary', signature: 'American period precision + institutional interior — space = social hierarchy 美国时代精度/机构室内/空间=社会等级', bestFor: 'period-america,noir-detective,institutional-drama,mid-century,civic-architecture' },
  { name: 'Dennis Gassner', tags: 'blade-runner-expansion,brutalist-future,golden-age-noir,wartime-trench,skyfall-scotland,bond-modernist', category: 'production-designer', era: 'contemporary', signature: 'Brutalist future + golden age noir — expanding worlds across sequels without losing DNA 粗野未来/金色时代黑色/跨续集扩世界不丢DNA', bestFor: 'cyberpunk,spy-thriller,sci-fi-sequel,war-trench,modernist-villain-lair' },
  { name: 'Jack Fisk', tags: 'american-landscape,there-will-be-blood,frontier-brutality,oil-boom-architecture,raw-wood-aesthetic', category: 'production-designer', era: 'contemporary', signature: '"血色将至/荒野猎人"——美国地景=角色——油田/边疆=粗野诚实——建筑从地里长出来', bestFor: 'frontier-drama,american-landscape,period-brutality,raw-material' },
  { name: 'Grant Major', tags: 'middle-earth,lotr-world,tolkien-visualized,new-zealand-landscape-set,medieval-fantasy-real', category: 'production-designer', era: 'contemporary', signature: '"指环王"——中土世界的视觉化——新西兰地景=中土——每个种族有独立的建筑/器物美学体系', bestFor: 'fantasy-epic,medieval-fantasy,world-building,mythological-scale' },
  { name: 'Wynn Thomas', tags: 'african-american-space,barbershop-culture,community-interior,spike-lee-color,urban-authenticity,black-cinema-design', category: 'production-designer', era: 'contemporary', signature: 'African American cultural space — barbershop + block + brownstone — community as architecture 非裔美国文化空间/理发店+街区+褐石屋/社区即建筑', bestFor: 'black-cinema,urban-drama,community-space,brooklyn-interior,cultural-authenticity' },

  // ═══════════════════════════════════════════
  // Painters (25)
  // ═══════════════════════════════════════════
  // ── Existing Western (7) ──
  { name: 'Rembrandt', tags: 'rembrandt-lighting,triangle-patch,chiaroscuro,selective-illumination,dark-background,inner-light', category: 'painter', era: 'classical-painting', signature: 'Rembrandt lighting — triangle patch under eye + chiaroscuro = modeling 3D with light', bestFor: 'dramatic-portrait,moral-conflict,historical-drama,chiaroscuro-scene' },
  { name: 'Vermeer', tags: 'window-light,soft-north-light,domestic-intimacy,blue-yellow-palette,pearl-highlight,camera-obscura', category: 'painter', era: 'classical-painting', signature: 'North window soft light + blue-yellow palette — the everyday becomes sacred through window light', bestFor: 'interior-intimacy,window-light-scene,domestic-drama,still-life-beauty' },
  { name: 'Caravaggio', tags: 'tenebrism,hard-contrast,divine-light,common-people-sacred,selective-spotlight,extreme-chiaroscuro', category: 'painter', era: 'classical-painting', signature: 'Tenebrism — violent chiaroscuro — light as a sword slashing truth from total darkness', bestFor: 'violent-contrast,dramatic-revelation,biblical-epic,street-realism' },
  { name: 'Monet', tags: 'impressionism,broken-color,light-atmosphere,same-scene-series,optical-mixing,en-plein-air', category: 'painter', era: 'modern-painting', signature: 'Broken color + same-scene series — light is the only protagonist — form is just a container for light', bestFor: 'atmospheric-landscape,seasonal-change,optical-experiment,impressionistic-sequence' },
  { name: 'Edward Hopper', tags: 'urban-isolation,geometric-light,empty-space,green-gold-light,voyeuristic-framing,american-solitude', category: 'painter', era: 'modern-painting', signature: 'Geometric light blocks cutting through loneliness — figures exposed by light but isolated by composition', bestFor: 'urban-isolation,modern-alienation,night-interior,architectural-light' },
  { name: 'Francis Bacon', tags: 'existential-distortion,isolated-figure,caged-space,screaming-pope,meat-and-flesh,blurred-motion', category: 'painter', era: 'modern-painting', signature: 'Caged space + smeared/blurred motion — body = prison of the soul — flesh as existential matter', bestFor: 'psychological-horror,body-horror,existential-dread,distorted-portrait' },
  { name: 'Hokusai', tags: 'ukiyo-e,flat-composition,dynamic-diagonal,prussian-blue,waves-and-wind,japanese-spatial', category: 'painter', era: 'classical-painting', signature: 'Flat depth + Prussian blue + diagonal energy lines — ukiyo-e dynamic nature geometrized', bestFor: 'stylized-landscape,japanese-aesthetic,graphic-composition,dynamic-nature' },
  // ── More Western Masters (9) ──
  { name: 'J.M.W. Turner', tags: 'light-dissolution,sea-sky-merge,proto-impressionist,sublime-nature,atmospheric-vortex,color-over-form', category: 'painter', era: 'classical-painting', signature: 'Light dissolves all — sea/sky/mist merge — form consumed by light — all shapes eventually return to light 光溶解万物/海天雾融一体/形式被光吞噬/一切终归于光', bestFor: 'atmospheric-landscape,sea-storm,light-dissolution,sublime-nature' },
  { name: 'Vincent van Gogh', tags: 'emotional-brushwork,starry-swirl,color-as-emotion,impasto-technique,post-impressionist-intensity,thick-paint-life', category: 'painter', era: 'modern-painting', signature: 'Emotional brushwork + Starry Night swirl + color = emotion — impasto = life energy 情感笔触/星夜漩涡/色彩=情感/厚涂=生命能量', bestFor: 'emotional-landscape,starry-sky,expressive-color,passion-visual' },
  { name: 'Salvador Dalí', tags: 'surrealist-melting,dream-landscape,double-imagery,paranoid-critical,desert-space,clock-soft', category: 'painter', era: 'modern-painting', signature: 'Melting forms + dream landscapes — the irrational rendered with photographic precision 融化形式/梦境风景/非理性以摄影精度呈现', bestFor: 'dream-sequence,surreal-landscape,melting-reality,time-distortion,subconscious-imagery' },
  { name: 'Georgia O\'Keeffe', tags: 'magnified-flower,desert-bone,abstraction-nature,organic-form,new-mexico-light,close-up-landscape', category: 'painter', era: 'modern-painting', signature: 'Magnified flowers + desert bones — nature abstracted through extreme close-up — the micro becomes macro 放大花卉/沙漠骨/极近距抽象自然/微观成宏观', bestFor: 'floral-abstraction,desert-landscape,organic-closeup,nature-magnification,feminine-gaze' },
  { name: 'Gustav Klimt', tags: 'gold-leaf,decorative-pattern,erotic-symbolism,mosaic-texture,byzantine-influence,ornamental-portrait', category: 'painter', era: 'modern-painting', signature: 'Gold leaf + decorative mosaic — eroticism clothed in ornament — Byzantine meets Art Nouveau 金箔/装饰马赛克/情色披装饰外衣/拜占庭遇新艺术', bestFor: 'golden-portrait,decorative-erotic,pattern-rich,mosaic-texture,vienna-secession' },
  { name: 'Egon Schiele', tags: 'distorted-figure,expressive-line,raw-emotion,twisted-anatomy,self-portrait-brutal,body-honesty', category: 'painter', era: 'modern-painting', signature: 'Distorted anatomy + expressive line — the body as emotional truth — beauty in the broken 扭曲解剖/表现线条/身体即情感真相/破碎中的美', bestFor: 'body-horror-lite,psychological-portrait,distorted-figure,raw-emotion,expressionist-body' },
  { name: 'Mark Rothko', tags: 'color-field,floating-rectangles,spiritual-depth,meditative-painting,thin-wash-layers,chapel-space', category: 'painter', era: 'modern-painting', signature: 'Color field painting — floating rectangles + spiritual depth — standing before the painting = meditation 色域绘画/浮动矩形+精神深度/站在画前=冥想', bestFor: 'meditative-space,color-field,spiritual-minimalism,emotional-color' },
  { name: 'Piet Mondrian', tags: 'geometric-abstraction,primary-colors,black-grid,neoplasticism,horizontal-vertical,universal-harmony', category: 'painter', era: 'modern-painting', signature: 'Geometric abstraction + primary colors — black grid + red/yellow/blue — universal harmony in rectangles 几何抽象/原色/黑格+红黄蓝/矩形中的普世和谐', bestFor: 'geometric-composition,primary-color,architectural-grid,modernist-set,abstract-interior' },
  { name: 'Frida Kahlo', tags: 'surreal-self-portrait,mexican-symbolism,pain-as-color,nature-backdrop,unibrow-icon,personal-is-political', category: 'painter', era: 'modern-painting', signature: 'Surreal self-portrait + Mexican symbolism — physical pain transformed into visual myth 超现实自画像/墨西哥象征/身体痛苦化为视觉神话', bestFor: 'painterly-portrait,surreal-autobiography,mexican-color,symbolic-nature,feminine-suffering' },
  // ── Chinese Masters (6) ──
  { name: '张大千 (Zhang Daqian)', tags: 'splash-ink,color-field,chinese-landscape-abstract,pomo-technique,blue-green-landscape,east-west-fusion', category: 'painter', era: 'modern-painting', signature: '泼墨泼彩——将中国水墨推向抽象表现——青绿=唐代精神的现代复活——东方=色彩不是西式补色', bestFor: 'abstract-landscape,chinese-ink-style,atmospheric-color-field,cosmic-landscape' },
  { name: '齐白石 (Qi Baishi)', tags: 'spontaneous-brushwork,shrimp-crab-flower,life-energy,folk-to-fine-art,negative-space-master,everyday-sacred', category: 'painter', era: 'modern-painting', signature: '写意笔法+日常神圣化——虾/蟹/花鸟=生命能量——"妙在似与不似之间"', bestFor: 'minimalist-nature,spontaneous-composition,folk-aesthetic,life-energy' },
  { name: '徐悲鸿 (Xu Beihong)', tags: 'ink-western-fusion,horse-anatomy,heroic-realism,dynamic-brush,historical-epic-chinese,muscular-energy', category: 'painter', era: 'modern-painting', signature: '水墨+西方写实——奔马解剖学精度——东西融合肌肉与精神——"人不可有傲气但不可无傲骨"', bestFor: 'horse-anatomy,heroic-animal,dynamic-motion,ink-realism,chinese-epic' },
  { name: '八大山人 (Bada Shanren)', tags: 'negative-space-extreme,lonely-bird-fish,ming-loyalist,minimalist-ink,expressive-dot,protest-through-absence', category: 'painter', era: 'classical-painting', signature: '极致留白+孤独鸟/鱼——明遗民的反抗=白眼向人——"计白当黑"——空即有', bestFor: 'minimalist-composition,negative-space,lone-protagonist,visual-protest' },
  { name: '吴冠中 (Wu Guanzhong)', tags: 'abstract-landscape,dots-and-lines,chinese-modernist,southern-china-river-town,white-wall-black-tile', category: 'painter', era: 'modern-painting', signature: '抽象山水+点/线/面——江南水乡=白墙黑瓦=几何抽象——中国笔墨×西方现代主义', bestFor: 'abstract-landscape,chinese-rural,geometric-beauty,southern-china' },
  { name: '赵无极 (Zao Wou-Ki)', tags: 'lyrical-abstraction,cosmic-energy,oil-on-canvas-chinese-spirit,light-from-within,landscape-of-mind', category: 'painter', era: 'modern-painting', signature: '抒情的抽象——油彩画布上的中国精神——光从画面内部发出——不是画风景，是风景在画你', bestFor: 'cosmic-landscape,abstract-atmosphere,inner-light,spiritual-visual' },
  // ── Japanese Masters (3) ──
  { name: '伊藤若冲 (Ito Jakuchu)', tags: 'intricate-detail,colorful-nature,japanese-birds,mosaic-feather,pattern-grid,kyoto-edo', category: 'painter', era: 'classical-painting', signature: 'Intricate detail + colorful nature — birds rendered feather by feather in mosaic-like grids 极致细节/彩色自然/鸟羽如马赛克网格逐根绘', bestFor: 'nature-detail,bird-composition,grid-pattern,colorful-animal,japanese-edo' },
  { name: '雪舟 (Sesshu Toyo)', tags: 'sumi-e-landscape,zen-minimalism,ink-gradation,splashed-ink,monochrome-depth,spiritual-nature', category: 'painter', era: 'classical-painting', signature: 'Sumi-e landscape + Zen minimalism — splashed ink + empty space — the void contains all form 水墨山水/禅极简/泼墨+空/虚空含万形', bestFor: 'zen-landscape,monochrome-nature,ink-wash,mountain-mist,spiritual-minimalism' },

  // ═══════════════════════════════════════════
  // Photographers (17)
  // ═══════════════════════════════════════════
  // ── Existing Western (5) ──
  { name: 'Steve McCurry', tags: 'war-portrait,direct-gaze,national-geographic-color,human-dignity-in-crisis,environmental-portrait,eye-contact', category: 'photographer', era: 'contemporary', signature: 'Direct gaze — Afghan Girl = the personal cost of all wars in one frame', bestFor: 'war-portrait,cultural-documentary,direct-gaze,human-story' },
  { name: 'Annie Leibovitz', tags: 'celebrity-iconography,conceptual-portrait,lighting-as-narrative,group-tableau,myth-making,constructed-reality', category: 'photographer', era: 'contemporary', signature: 'Conceptual portraiture — celebrities are modern mythology — sets = film production scale', bestFor: 'iconic-portrait,myth-making,group-tableau,conceptual-character' },
  { name: 'Sebastiao Salgado', tags: 'biblical-light,human-epic,black-and-white-sublime,exodus-scale,environmental-refugee,sacred-labor', category: 'photographer', era: 'contemporary', signature: 'Biblical high-contrast BW — seeing every face within million-person scale', bestFor: 'epic-documentary,human-scale,tragedy-scale,black-and-white-monument' },
  { name: 'Tim Walker', tags: 'surreal-fashion,fairy-tale-scale,oversized-prop,whimsical-costume,dream-narrative,pastel-fantasy', category: 'photographer', era: 'contemporary', signature: 'Oversized props + all in-camera (no Photoshop) — fashion = adult fairy tale book', bestFor: 'fantasy-fashion,dream-sequence,fairy-tale,whimsical-world' },
  { name: 'Gregory Crewdson', tags: 'cinematic-still,suburban-surreal,hooper-esque,film-production-photo,single-frame-movie,alienation-tableau', category: 'photographer', era: 'contemporary', signature: 'One photo = one movie — Hollywood-scale crew for a single still frame', bestFor: 'suburban-uncanny,psychological-freeze,americana-alienation,cinematic-still' },
  // ── Classic & Contemporary Western (6) ──
  { name: 'Henri Cartier-Bresson', tags: 'decisive-moment,street-photography,geometric-timing,human-geometry,leica-composition,life-in-fraction', category: 'photographer', era: '20th-century', signature: 'The decisive moment — geometry + timing + human truth converge in 1/125th second 决定性瞬间/几何+时机+人性在1/125秒交汇', bestFor: 'street-scene,human-geometry,spontaneous-composition,decisive-moment,life-captured' },
  { name: 'Cindy Sherman', tags: 'self-portrait-as-character,identity-performance,female-stereotype-deconstruction,cinematic-still-series,untitled-film-stills', category: 'photographer', era: 'contemporary', signature: 'Self-portrait as character — each photo = a film that does not exist — identity is performance 自拍=角色/每张=不存在的电影/身份即表演', bestFor: 'identity-narrative,female-character,performance-as-self,stereotype-critique' },
  { name: 'Andreas Gursky', tags: 'mega-scale,globalization-image,rhine-ii,capitalist-sublime,repetition-pattern,god-perspective', category: 'photographer', era: 'contemporary', signature: 'God is perspective + globalization landscape — repetition = contemporary sublime 上帝视角+全球化景观/重复=当代崇高', bestFor: 'mega-scale,globalization-visual,pattern-landscape,capitalist-aesthetic' },
  { name: 'Nan Goldin', tags: 'intimate-documentary,queer-community,raw-color,personal-is-political,snapshot-aesthetic,love-and-loss', category: 'photographer', era: 'contemporary', signature: 'Intimate documentary + raw color — photographing your own life — love/loss/drag/queer 亲密纪实/原生色彩/拍摄自己的生活/爱失变装酷儿', bestFor: 'intimate-diary,queer-narrative,raw-portrait,community-life,emotional-documentary' },
  { name: 'William Eggleston', tags: 'color-pioneer,american-vernacular,democratic-camera,banal-subject-beauty,red-ceiling,everyday-color', category: 'photographer', era: 'contemporary', signature: 'Color pioneer + American vernacular — the banal made monumental — red ceiling = the whole South 色彩先驱/美国方言/平凡成宏伟/红天花板=整个南方', bestFor: 'americana-color,suburban-detail,everyday-beauty,vernacular-landscape,color-pioneer' },
  { name: 'Alec Soth', tags: 'american-landscape,melancholic-portrait,river-road,journey-photo,large-format-intimacy,lonely-places', category: 'photographer', era: 'contemporary', signature: 'Melancholic American landscape + river journeys — large-format intimacy with strangers — the road as longing 忧郁美国风景/河流旅程/大画幅与陌生人亲密/路即渴望', bestFor: 'american-road,melancholy-landscape,river-journey,stranger-portrait,lonely-beauty' },
  // ── Asian Photographers (6) ──
  { name: '何藩 (Fan Ho)', tags: 'geometric-light,hong-kong-1950s,shadow-poetry,chinese-street-photography,single-source-drama,everyday-theater', category: 'photographer', era: '20th-century', signature: '几何光影+1950年代香港——街头=剧场——单光源戏剧性——阴影=故事', bestFor: 'street-noir,geometric-shadow,urban-drama,chinese-retro' },
  { name: '森山大道 (Daido Moriyama)', tags: 'high-contrast-grain,are-bure-boke,street-snap,existential-urban,lost-in-the-city,no-viewfinder', category: 'photographer', era: 'contemporary', signature: '高反差+粗颗粒+失焦——"アレ·ブレ·ボケ"——都市=迷失——不用取景器的直觉拍摄', bestFor: 'urban-grit,high-contrast-bw,existential-street,noir-texture' },
  { name: '荒木经惟 (Nobuyoshi Araki)', tags: 'intimate-erotic,kinbaku-rope,japanese-shadow,flower-sensuality,diary-photo,life-and-death', category: 'photographer', era: 'contemporary', signature: 'Intimate + erotic + death — photographing as breathing — the camera as extension of the body 亲密/情色/死/拍摄如呼吸/相机即身体延伸', bestFor: 'intimate-portrait,erotic-imagery,japanese-shadow,rope-texture,diary-aesthetic' },
  { name: '杉本博司 (Hiroshi Sugimoto)', tags: 'long-exposure,seascapes-theaters,time-philosophy,conceptual-photography,minimalist-sublime,lightning-field', category: 'photographer', era: 'contemporary', signature: '超长曝光——海景/剧院——时间=可见——一部电影=一张白色矩形=时间的容器', bestFor: 'time-meditation,minimalist-landscape,conceptual-visual,long-exposure' },
  { name: '川内倫子 (Rinko Kawauchi)', tags: 'quiet-everyday,soft-light,poetic-detail,small-moments,gentle-color,japanese-serene', category: 'photographer', era: 'contemporary', signature: 'Quiet everyday + soft light + small moments — the profound in the insignificant 安静日常/柔光/小瞬间/平凡中的深远/观看即冥想', bestFor: 'quiet-intimacy,poetic-detail,soft-atmosphere,everyday-sacred,japanese-serene' },
  { name: '陈漫 (Chen Man)', tags: 'chinese-fashion,digital-surreal,vivid-color,beauty-maximalism,oriental-futurism,celebrity-as-art', category: 'photographer', era: 'contemporary', signature: '中国时尚摄影女王——数字超现实+鲜艳色彩——东方未来主义——美=极致=可触摸', bestFor: 'fashion-drama,oriental-futurism,digital-surreal,vivid-beauty' },
  { name: '蜷川实花 (Mika Ninagawa)', tags: 'flower-explosion,saturated-color,kawaii-surreal,goldfish-and-flower,japanese-pop-visual,overload-aesthetic', category: 'photographer', era: 'contemporary', signature: '花爆炸+饱和色彩+可爱超现实——金鱼/花/女性——色彩=过量=快乐=死亡', bestFor: 'fantasy-fashion,pop-surreal,kawaii-aesthetic,color-maximalism' },

  // ═══════════════════════════════════════════
  // Animators (10)
  // ═══════════════════════════════════════════
  // ── Existing (6) ──
  { name: 'Hayao Miyazaki', tags: 'flight-obsession,ma-negative-space,hand-drawn-purity,nature-reverence,wind-in-every-frame,eco-feminism', category: 'animator', era: 'contemporary', signature: 'Ma (negative space) + flight obsession + hand-drawn purity — wind = life = spirit', bestFor: 'animated-fantasy,eco-epic,coming-of-age,flight-sequence,spirit-world' },
  { name: 'Satoshi Kon', tags: 'match-cut-reality-shift,dream-reality-blur,anime-psychological,time-collapse-montage,identity-fragmentation,frame-within-frame', category: 'animator', era: 'contemporary', signature: 'Match-Cut reality shifts — editing = structure of consciousness — 100% controllable reality of animation', bestFor: 'psychological-thriller,dream-sequence,reality-shift,anime-style,identity-crisis' },
  { name: 'Makoto Shinkai', tags: 'digital-light-porn,sky-replacement,lens-flare-poetry,focus-rack-emotion,ultra-detail-background,weather-as-emotion', category: 'animator', era: 'contemporary', signature: 'Digital light aesthetic — sky = emotional screen — weather = inner state', bestFor: 'teenage-romance,light-poetry,weather-emotion,separation-drama' },
  { name: 'Mamoru Oshii', tags: 'static-philosophy,urban-void,techno-dystopia,stillness-as-action,reflective-surface,cyberpunk-noir', category: 'animator', era: 'contemporary', signature: 'Explosive power of stillness — characters motionless for 3-5 seconds = eternity — animation can be still', bestFor: 'cyberpunk,philosophical-sf,urban-dystopia,stillness-meditation' },
  { name: 'Hideaki Anno', tags: 'psychological-collapse,still-frame-horror,text-on-screen,mixed-media-breakdown,train-station-symbolism,otaku-deconstruction', category: 'animator', era: 'contemporary', signature: 'Multimedia breakdown — when emotion exceeds expression, the medium itself must collapse', bestFor: 'psychological-horror,apocalyptic,media-experiment,trauma-narrative' },
  { name: 'Isao Takahata', tags: 'watercolor-realism,everyday-sacred,slow-observation,unspoken-emotion,hand-drawn-texture,japanese-rural', category: 'animator', era: 'contemporary', signature: 'Watercolor aesthetic + slow observation — the deepest emotions are never spoken', bestFor: 'rural-drama,memory-narrative,war-tragedy,slice-of-life,watercolor-style' },
  // ── New (4) ──
  { name: 'Tex Avery', tags: 'exaggerated-physics,wild-take,stretch-squash-extreme,eye-pop,cartoon-surrealism,timing-extreme', category: 'animator', era: '20th-century', signature: 'Exaggerated cartoon physics — wild takes + eye pops — reality breaks for the joke 夸张卡通物理/眼球弹出/现实为笑料崩坏——动画的法则覆盖物理', bestFor: 'slapstick-comedy,cartoon-physics,exaggerated-expression,wild-takes,comic-timing' },
  { name: 'Yuri Norstein', tags: 'cut-out-animation,poetic-texture,multi-plane-glass,soft-light-effect,tale-of-tales,hazy-memory', category: 'animator', era: '20th-century', signature: 'Cut-out animation + multi-plane glass — hazy memories told through layered translucency — poetry over plot 剪纸动画/多层玻璃板/朦胧记忆经层叠透明讲述 故事中的故事', bestFor: 'poetic-memory,hazy-dream,folk-tale,layered-transparency,cut-out-style' },
  { name: 'Jan Švankmajer', tags: 'stop-motion-surrealism,tactile-material,clay-meat-wood,czech-surrealist,childhood-horror,alchemical-object', category: 'animator', era: '20th-century', signature: 'Stop-motion surrealism + tactile materials — clay/meat/wood/rust — objects have malicious life 定格超现实/可触材料/黏土肉木锈/物体有恶意生命', bestFor: 'surreal-horror,tactile-nightmare,object-animation,allegorical,childhood-creepy' },
  { name: 'Don Hertzfeldt', tags: 'stick-figure-philosophy,existential-comedy,hand-drawn-simplicity,time-and-memory,analog-filmmaking,camera-as-character', category: 'animator', era: 'contemporary', signature: 'Stick figure philosophy + existential comedy — simplest drawings, deepest questions 火柴人哲学/存在喜剧/最简绘画最深问题/手绘模拟反叛', bestFor: 'existential-comedy,philosophical-short,time-memory,surreal-stick-figure,analog-texture' },
];

// ─── Search Engine ───
export function searchVisualKB(query: string): string {
  const kws = query.toLowerCase().split(/[\s,，、]+/).filter(k => k.length > 1);
  if (!kws.length) return '';

  const scored: { card: VisualCard; score: number }[] = [];
  for (const card of ALL_VISUAL_CARDS) {
    const haystack = (card.name + ' ' + card.tags + ' ' + card.signature + ' ' + card.bestFor + ' ' + card.category + ' ' + card.era).toLowerCase();
    let score = 0;
    for (const kw of kws) {
      if (haystack.includes(kw)) score += kw.length;
      for (let i = 0; i <= kw.length - 2; i++) {
        if (haystack.includes(kw.substring(i, i + 2))) score += 0.5;
      }
    }
    if (score > 0) scored.push({ card, score });
  }

  scored.sort((a, b) => b.score - a.score);
  const seen = new Set<string>();
  const unique = scored.filter(s => {
    if (seen.has(s.card.name)) return false;
    seen.add(s.card.name);
    return true;
  });

  const blocks = unique.slice(0, 6).map(s => {
    const c = s.card;
    return '### ' + c.name + ' (' + c.category + ' / ' + c.era + ')\ntags: ' + c.tags + '\n**Technique**: ' + c.signature + '\n**Best for**: ' + c.bestFor;
  });
  return blocks.join('\n\n---\n\n');
}

// ─── KB Catalog ───
export const VISUAL_KB_CATALOG = `### Cinematography & Visual Style KB

**Cinematographers (55):**
Roger Deakins(naturalistic/single-source/negative-fill) | Chivo Lubezki(all-natural-light/wide-angle-intimacy/fluid-long-take) | Bradford Young(dark-skin-exposure/shadow-as-subject) | Vittorio Storaro(color-philosophy/chiaroscuro/writing-with-light) | Greig Fraser(LED-Volume/low-light-digital/silhouette) | Janusz Kaminski(bleach-bypass/desaturated/backlight-halo) | Hoyte van Hoytema(IMAX-intimacy/large-format/practical-firelight) | Claudio Miranda(HDR-pioneer/ocean-light/digital-color) | Darius Khondji(texture-alchemy/chemical-process/degraded-beauty) | Matthew Libatique(kinetic-camera/neon-noir/color-contamination) | Rachel Morrison(female-gaze/skin-tone-fidelity/intimate-naturalism) | Robert Richardson(hot-top-light/blown-highlights/expressionist) | Rodrigo Prieto(film-digital-hybrid/cultural-color-accuracy) | Linus Sandgren(single-camera/vaseline-lens/romantic-soft) |
Gordon Willis(underexposure/chiaroscuro/prince-of-darkness/top-light-only) | Gregg Toland(deep-focus-revolution/citizen-kane/ceilinged-sets) | James Wong Howe(low-key-noir/newsreel-handheld/crab-dolly) | Robert Surtees(epic-widescreen/technicolor/65mm-grandeur) | Freddie Young(desert-epic/70mm-mirage/lawrence-sun) | Raoul Coutard(French-New-Wave/handheld-liberation/street-is-studio) | Sven Nykvist(nordic-naturalism/soft-diffused/face-as-landscape) | Néstor Almendros(magic-hour/available-light-only/lyrical-simplicity) | Vilmos Zsigmond(flashing-technique/desaturated-pastel/smoke-diffusion) | Owen Roizman(doc-realism/handheld-energy/NYC-grit) |
Conrad Hall(naturalistic-elegance/single-source/shadow-gradation) | Robert Elswit(desert-light/oil-field-grit/wide-lens/practical-fire) | Caleb Deschanel(painterly-style/backlight-halo/religious-iconography) | John Toll(natural-light-epic/landscape-character/golden-hour) | John Seale(desert-action/orange-teal/practical-vehicle-light) | Michael Ballhaus(360-camera/circular-movement/scorsese-kinetic) | Bill Pope(matrix-green/comic-book-color/bullet-time/VFX-native) | Bruno Delbonnel(color-expressionism/amber-green-world/light-as-emotion) | Slawomir Idziak(color-filter/philosophical-light/green-blue-isolation) | Dion Beebe(digital-pioneer/precision-sharpness/asian-light) | Philippe Rousselot(golden-interior/candle-chiaroscuro/river-light) | Anthony Dod Mantle(digital-revolution/dogme95/available-light-digital) | Haskell Wexler(political-camera/doc-truth/available-light-protest) | John Alcott(candlelight-only/f0.7-lens/natural-period-flame) | Dean Cundey(blockbuster-glow/backlight-silhouette/Spielberg-look) | Giuseppe Rotunno(italian-epic/ballroom-opulence/operatic-color) |
Kazuo Miyagawa(deep-focus/multi-camera/tracking/sumi-e-composition) | Tak Fujimoto(psychological-close-up/subjective-camera/half-face-shadow) | Peter Biziou(artificial-world-light/Truman-Show/controlled-reality) | Dick Pope(Turner-light/painterly-landscape/oil-painting-composition) | Benoît Debie(acid-color/neon-nightmare/strobe-hallucination) | Sean Bobbitt(long-take-witness/natural-light-brutal/historical-realist) | Mátyás Erdély(extreme-shallow-focus/face-isolation/tunnel-vision) | Mandy Walker(female-epic/australian-outback/desert-beauty) | Jarin Blaschke(modern-BW/orthochromatic/lighthouse-texture) | Sayombhu Mukdeeprom(tropical-slow/jungle-humidity/meditative-nature) | Christopher Blauvelt(pastoral-naturalism/forest-light/period-texture) | Bojan Bazelli(dark-fantasy/sorcery-light/practical-magic) | Mihai Mălaimare Jr.(slow-motion-ballet/stylized-violence/master-tableau) |
**[CN]** 赵小丁(ZhangYimou-colorist/monochromatic/ink-wash) | 杜可风/ChristopherDoyle(neon-HK/handheld-energy/drunken-master) | 罗攀(Chinese-realism/cold-northern-light/documentary-approach) | 吕乐(documentary-background/natural-light-evolution) | 曹郁(candlelight-specialist/low-light-digital/flame-flicker) | 曾剑(handheld-intimacy/available-light/observational) | 王昱(water-reflection/urban-melancholy/soft-diffusion) | 余静萍(female-gaze/youth-texture/skin-tone-fidelity) | 董劲松(industrial-decay/noir-china/rust-belt) |
**[KR]** 洪慶杓(precise-composition/confined-space/class-allegory-light) | 金智龙(baroque-color/symmetrical-precision/erotic-composition) | ChungChung-hoon(gothic-color/red-black/park-chan-wook) | 李模介(dark-urban/neo-noir-korea/contrast-extreme) | KimWoo-hyung(claustrophobic-action/zombie-chaos/confined-space) |
**[IN]** RaviVarman(saturated-color/epic-scale/indian-light) | SantoshSivan(natural-light-india/humanist-scale/landscape-as-emotion) | P.C.Sreeram(soft-golden-warmth/available-light-india/tamil-poetry) | SudeepChatterjee(period-opulence/maratha-light/epic-composition)

**Directors (40):**
Wong Kar-wai(step-printing/neon-noir/memory-materialized) | Zhang Yimou(monochromatic-tyranny/precision-blocking/chinese-red) | Denis Villeneuve(megalophobia/monumental-composition/bone-dry-color/architectural-cinema) | Christopher Nolan(temporal-structure/spiral-narrative/practical>CGI/IMAX) | Wes Anderson(symmetry-dictatorship/planimetric/pastel-palette) | David Fincher(camera-lock/desaturated-green/focus-rack-psychology) | Terrence Malick(golden-hour-only/wandering-steadicam/whisper-montage) | Paul Thomas Anderson(virtuoso-long-take/anamorphic/haze-density) | Andrei Tarkovsky(sculpting-in-time/long-take-hypnosis/elemental-nature) |
Stanley Kubrick(one-point-perspective/geometric-precision/slow-zoom) | Alfred Hitchcock(vertigo-effect/subjective-POV/suspense-through-what-you-see) | Ingmar Bergman(extreme-close-up/Nordic-light/face-as-existence) | Federico Fellini(surreal-circus/dream-sequence/baroque-memory) | Jean-Luc Godard(jump-cut/Brechtian/color-as-political-statement) | Akira Kurosawa(weather-as-drama/telephoto-action/multi-camera) | Yasujirō Ozu(tatami-shot/pillow-shots/stillness/mono-no-aware) | Kenji Mizoguchi(flowing-long-take/floating-camera/ghost-aesthetic) | Satyajit Ray(lyrical-realism/natural-light-India/humanist-observation) |
Martin Scorsese(kinetic-camera/rock-editing/freeze-frame) | Francis Ford Coppola(operatic-family/chiaroscuro/shadow-moral-descent) | Ridley Scott(atmospheric-world-building/haze-light/environment-first) | David Lynch(surreal-suburban/dream-logic/red-curtain/uncanny) | Guillermo del Toro(gothic-fairy-tale/amber-gold/practical-creatures) | Alfonso Cuarón(long-take-immersion/real-time-tension/steadicam-marathon) | Krzysztof Kieślowski(color-as-moral-inquiry/light-as-grace/parallel-lives) | Werner Herzog(ecstatic-truth/jungle-madness/impossible-image) |
**[CN]** 陈凯歌(epic-historical/theatrical-staging/forbidden-love) | 贾樟柯(doc-realism/long-take/social-change-through-faces) | 侯孝贤(distant-observation/static-camera/nature-as-time) | 李安/AngLee(cross-genre/emotional-precision/cultural-duality) |
**[KR]** 朴赞郁(baroque-violence/red-black/revenge-trilogy) | 奉俊昊(genre-hybrid/class-through-space/stairs-metaphor) | 李沧东(humanist-realism/poetry-in-ordinary/marginalized) | 金基德(minimal-dialogue/Buddhist-symbolism/water-metaphor) |
**[IN/SEA]** SanjayLeelaBhansali(operatic-indian/devdas-aesthetic/chandelier-light) | S.S.Rajamouli(mythological-scale/maximalist-epic/indian-mythology) | MiraNair(cross-cultural/monsoon-aesthetic/diaspora-narrative) | ApichatpongWeerasethakul(slow-cinema/jungle-mysticism/reincarnation) | TranAnhHung(poetic-naturalism/food-as-cinema/vietnamese-aesthetic)

**Production Designers / Art Directors (22):**
叶锦添/TimYip(oriental-fantasy/tang-dynasty/hanfu-accuracy) | 张叔平/WilliamChang(qipao-elegance/cheongsam-as-character/wong-kar-wai) | 种田阳平/YoheiTaneda(war-torn-detail/damaged-beauty/historical-destruction) |
Dante Ferretti(fellini-scorsese/dark-operatic/italian-gothic) | Rick Carter(immersive-world/avatar-pandora/jurassic-park) | Sarah Greenwood(period-precision/dollhouse-detail/literary-England) | Adam Stockhausen(wes-anderson-world/miniature-precision/dollhouse-aesthetic) | Catherine Martin(maximalist-musical/art-deco-extreme/baz-luhrmann) | Patrice Vermette(sci-fi-realism/alien-brutalism/dune-world/minimalist-epic) | Ken Adam(cold-war-modernism/james-bond-villain-lair/expressionist-concrete) | Eugenio Caballero(dark-fairy-tale/fascist-brutalism/grotto-horror) | Stuart Craig(harry-potter-world/hogwarts-organic/gothic-whimsy) | Bo Welch(expressionist-suburbia/burton-gothic/distorted-reality) | Mark Tildesley(textile-psychology/craft-as-character/phantom-thread) | KK Barrett(soft-sci-fi/emotional-architecture/warm-future) | Jeannine Oppewall(period-precision/institutional-interior/space=social-hierarchy) | Dennis Gassner(brutalist-future/golden-age-noir/bond-modernist) | Jack Fisk(american-landscape/frontier-brutality/raw-wood) | Grant Major(middle-earth/lotr-world/tolkien-visualized) | Wynn Thomas(black-cinema-space/community-architecture/cultural-authenticity)

**Painters (25):**
Rembrandt(rembrandt-lighting/triangle-patch/chiaroscuro) | Vermeer(window-light/blue-yellow/everyday-sacred) | Caravaggio(tenebrism/violent-chiaroscuro/divine-light) | Monet(broken-color/same-scene-series/light-protagonist) | Edward Hopper(geometric-light/urban-isolation/voyeuristic-frame) | Francis Bacon(caged-space/existential-distortion/flesh-as-matter) | Hokusai(ukiyo-e/flat-composition/prussian-blue/diagonal-energy) |
J.M.W.Turner(light-dissolution/sea-sky-merge/sublime-nature) | Vincent van Gogh(emotional-brushwork/starry-swirl/impasto) | Salvador Dalí(surrealist-melting/dream-landscape/paranoid-critical) | Georgia O'Keeffe(magnified-flower/desert-bone/organic-abstraction) | Gustav Klimt(gold-leaf/decorative-mosaic/erotic-ornament) | Egon Schiele(distorted-figure/expressive-line/raw-emotion-body) | Mark Rothko(color-field/floating-rectangles/spiritual-depth) | Piet Mondrian(geometric/primary-colors/black-grid) | Frida Kahlo(surreal-self-portrait/Mexican-symbolism/pain-as-color) |
**[CN]** 张大千(splash-ink/color-field/blue-green-landscape) | 齐白石(spontaneous-brushwork/negative-space/everyday-sacred) | 徐悲鸿(ink-western/horse-anatomy/heroic-realism) | 八大山人(negative-space-extreme/minimalist-ink/lonely-bird) | 吴冠中(abstract-landscape/dots-and-lines/white-wall-black-tile) | 赵无极(lyrical-abstraction/cosmic-energy/light-from-within) |
**[JP]** 伊藤若冲(intricate-detail/colorful-birds/mosaic-feather) | 雪舟(sumi-e-Zen/splashed-ink/monochrome-depth)

**Photographers (17):**
Steve McCurry(war-portrait/direct-gaze) | Annie Leibovitz(conceptual-portrait/celebrity=myth) | Sebastiao Salgado(biblical-BW/human-epic-scale) | Tim Walker(surreal-fashion/oversized-props/in-camera) | Gregory Crewdson(cinematic-still/Hollywood-crew-one-frame) |
Henri Cartier-Bresson(decisive-moment/street-photography/geometry+timing) | Cindy Sherman(self-portrait-character/identity-performance/film-still) | Andreas Gursky(mega-scale/globalization-image/capitalist-sublime) | Nan Goldin(intimate-documentary/queer-community/raw-color) | William Eggleston(color-pioneer/American-vernacular/banal-monumental) | Alec Soth(melancholic-America/river-journey/stranger-intimacy) |
**[JP/CN]** 何藩(geometric-light/hong-kong-1950s/shadow-poetry) | 森山大道(high-contrast-grain/are-bure-boke/existential-street) | 荒木经惟(intimate-erotic/kinbaku/diary-as-breathing) | 杉本博司(long-exposure/time-philosophy/seascapes) | 川内倫子(quiet-everyday/soft-light/poetic-detail) | 陈漫(chinese-fashion/digital-surreal/oriental-futurism) | 蜷川实花(flower-explosion/saturated-color/kawaii-surreal)

**Animators (10):**
Hayao Miyazaki(ma-negative-space/flight-obsession/hand-drawn/wind=life) | Satoshi Kon(match-cut-reality-shift/editing=consciousness) | Makoto Shinkai(digital-light-aesthetic/sky=emotion/weather=inner-state) | Mamoru Oshii(stillness-philosophy/urban-void/cyberpunk-noir) | Hideaki Anno(multimedia-breakdown/psychological-collapse/still-frame-horror) | Isao Takahata(watercolor-realism/slow-observation/everyday-sacred) |
Tex Avery(exaggerated-physics/wild-takes/cartoon-surrealism) | Yuri Norstein(cut-out/multi-plane-glass/hazy-poetic-memory) | Jan Švankmajer(stop-motion-surreal/tactile-material/objects-malicious-life) | Don Hertzfeldt(stick-figure-philosophy/existential-comedy/analog-rebellion)

**Theory:** Color Theory(hue/saturation/value/complementary/analogous/triadic/color-psychology) | Lighting Design(three-point/hard-soft-diffused/direction-narrative/CCT-temperature/Rembrandt-Chiaroscuro-HighKey-LowKey-Cameo) | Composition(rule-of-thirds/leading-lines/symmetry/frame-within-frame/negative-space/focal-length-narrative/camera-movement-semiotics) | Production Design(space-as-character/architectural-psychology/period-texture/prop-semiotics/set-decoration-narrative) | Art Direction(color-palette-world/era-authenticity/cultural-space-design)`;

// ─── Retrieval Prompt ───
export const KB_RETRIEVAL_PROMPT_STORYBOARD = `你是一位顶级视觉导演和分镜设计师。在分析剧本设计分镜之前，上面是一个摄影/视觉风格知识库的目录。请先思考这个剧本需要什么样的视觉基调、灯光风格、色彩方向和镜头语言，然后选择你需要检索的 5-8 个方向。

你需要重点考虑的维度（共 8 个）：

1. 灯光风格 — 自然主义(Deakins/Lubezki)？表现主义(Richardson)？柔光浪漫(Sandgren)？硬光戏剧？Rembrandt式？霓虹黑色？极低曝光(Willis)？北欧自然光(Nykvist)？烛光时代(Alcott)？酸色霓虹(Debie)？→ 匹配摄影师技法
2. 色彩方向 — 低饱和严肃(Fincher)？单色专制(张艺谋)？粉彩童话(Wes Anderson)？霓虹科幻？互补冲突？色彩表现主义(Delbonnel)？色域抽象(Rothko)？泼墨泼彩(张大千)？金色装饰(Klimt)？→ 匹配色彩理论+画家风格
3. 构图策略 — 对称(Wes Anderson)？负空间？纪念碑式(Villeneuve)？三分法？框中框？单点透视(Kubrick)？榻榻米视角(Ozu)？深焦(Toland/Miyagawa)？→ 匹配导演视觉风格+焦段叙事
4. 运镜风格 — 手持纪录片？Steadicam流动？静态上帝视角？缓慢推轨？360度旋转(Ballhaus)？流动长镜(Mizoguchi)？眩晕效果(Hitchcock)？长镜沉浸(Cuarón)？→ 匹配运镜语意
5. 美术设计 — 东方美学(叶锦添)？Art Deco奢华(Catherine Martin)？粗野未来(Gassner)？纪念碑极简(Vermette)？狂妄建筑(Ken Adam)？手工边疆(Fisk)？中土实建(Major)？旗袍心理(张叔平)？→ 匹配Production Designer/Art Director的世界建造
6. 绘画参考 — Rembrandt明暗法？Vermeer窗光？Turner大气崇高？Van Gogh厚涂？Dalí超现实？Hopper都市孤独？Rothko色域？张大千泼彩？八大山人极简？Klimt金箔？Mondrian几何？→ 匹配画家风格光照+色彩+肌理
7. 摄影参考 — Cartier-Bresson决定性瞬间？森山大道粗粒高反差？Crewdson电影单帧？何藩几何光影？Gursky全球化景观？川内倫子安静日常？→ 匹配摄影师构图+质感
8. 动画风格（如需动画）— 今敏意识流？宫崎骏飞行+间？新海诚数字光？押井守静止哲学？Švankmajer触觉材料？Hertzfeldt火柴人哲学？→ 匹配动画手法

**亚洲电影参考——按地区检索：**
- 中国：张艺谋单色专制 | 陈凯歌京剧美学 | 贾樟柯纪实写实 | 侯孝贤远观长镜 | 李安跨类型 | 赵小丁水墨摄影 | 杜可风霓虹手持 | 曹郁烛光战争 | 罗攀冷北方写实
- 韩国：朴赞郁巴洛克暴力 | 奉俊昊阶级空间 | 李沧东人文慢燃 | 金基德极简象征 | 洪慶杓密闭空间张力 | ChungChung-hoon红黑暴力
- 日本：黑泽明天气即戏剧 | 小津榻榻米静止 | 沟口流动长镜幽灵 | 宫川一夫深焦多机位 | 森山大道粗粒街头 | 杉本博司时间曝光
- 印度：Satyajit Ray窗光人文 | Bhansali歌剧奢华 | Rajamouli神话尺度 | Sivan自然光印度

输出格式（每行一个）：
关键词：简短说明用途

例如对于一部唐朝奇幻史诗：
曹郁运动灯光雕塑 → 唐风烛光+节日灯场景设计
叶锦添唐风华美美术 → 宫廷/长安街景世界建造
Gordon Willis极低曝光明暗法 → 权力阴谋暗室内戏
Vittorio Storaro色彩哲学体系 → 每幕独特色彩主题(金/红/暗)
赵小丁丝绸布光+色彩交响 → 武打场景丝织物打光
Kazuo Miyagawa深焦多机位 → 多人战斗长镜头跟拍
张大千泼墨泼彩山水 → 奇幻场景青绿山水参考
美术设计东方美学权威 → 宫廷建筑+服饰纹理

请先给出你对剧本视觉基调的简要判断（1-2句话），然后列出你需要检索的关键词。`;

// ─── Full KB fallback ───
export const VISUAL_KB_FULL = ALL_VISUAL_CARDS.map(c =>
  '### ' + c.name + ' (' + c.category + ' / ' + c.era + ')\ntags: ' + c.tags + '\n' + c.signature + '\nBest for: ' + c.bestFor
).join('\n\n---\n\n');
