/* === Scene3DNode v2 — clean rewrite === */
import React,{useState,useCallback,useMemo,useRef,useEffect,Suspense}from'react';
import{createPortal}from'react-dom';
import{Handle,Position}from'@xyflow/react';
import{Canvas,useThree,useFrame}from'@react-three/fiber';
import{OrbitControls,Grid,TransformControls,useGLTF}from'@react-three/drei';
import*as THREE from'three';
import{useCanvasStore}from'../../store/useCanvasStore';

// Types
interface SceneObject{id:string;type:'box'|'sphere'|'cylinder'|'plane'|'figure'|'camera';position:Vec3;rotation:Vec3;scale:Vec3;color?:string;figurePose?:string;figureSrc?:string;}
type Vec3=[number,number,number];type GizmoMode='translate'|'rotate'|'scale';
interface JointSet{head:Vec3;neck:Vec3;shoulderL:Vec3;shoulderR:Vec3;elbowL:Vec3;elbowR:Vec3;handL:Vec3;handR:Vec3;hip:Vec3;hipL:Vec3;hipR:Vec3;kneeL:Vec3;kneeR:Vec3;footL:Vec3;footR:Vec3;}
const KNOWN_POSES=['stand1','stand2','sit','walk','run','squat','lie','fight'];
type PoseEntry={name:string;src:string;format?:'glb'|'fbx'};
const poseRegistry=new Map<string,PoseEntry>();let poseInitDone=false;
async function initPoseRegistry(){if(poseInitDone)return;poseInitDone=true;const r=await Promise.all(KNOWN_POSES.map(async id=>{try{const r=await fetch(`/models/${id}.glb`,{method:'HEAD'});if(r.ok)return{id,ext:'glb'};}catch{}return null;}));r.filter(Boolean).forEach(x=>{if(x)poseRegistry.set(x.id,{name:PF[x.id]||x.id,src:`/models/${x.id}.glb`});});}
const PF:Record<string,string>={stand1:'站立1',stand2:'站立2',sit:'坐姿',walk:'行走',run:'跑步',squat:'蹲姿',lie:'卧躺',fight:'格斗'};
function importFile(file:File,done:(entry:PoseEntry,poseId:string)=>void){const name=file.name.replace(/\.(glb|fbx)$/i,'');const id=name.toLowerCase().replace(/[^a-z0-9]/g,'_')||`pose_${Date.now()}`;const r=new FileReader();r.onload=()=>{const src=r.result as string;const e:PoseEntry={name,src,format:'glb'};poseRegistry.set(id,e);done(e,id);};r.readAsDataURL(file);}
export function addPoseEntry(id:string,name:string,src:string,format?:'glb'|'fbx'){poseRegistry.set(id,{name,src,format});if(!poseInitDone)poseInitDone=true;}
const POSE_JOINTS:Record<string,JointSet>={stand:{head:[0,1.68,0],neck:[0,1.50,0],shoulderL:[-0.28,1.46,0],shoulderR:[0.28,1.46,0],elbowL:[-0.28,1.16,0],elbowR:[0.28,1.16,0],handL:[-0.28,0.86,0],handR:[0.28,0.86,0],hip:[0,0.85,0],hipL:[-0.14,0.83,0],hipR:[0.14,0.83,0],kneeL:[-0.14,0.42,0],kneeR:[0.14,0.42,0],footL:[-0.14,0.04,0],footR:[0.14,0.04,0]},sit:{head:[0,1.24,0],neck:[0,1.06,0],shoulderL:[-0.28,1.02,0],shoulderR:[0.28,1.02,0],elbowL:[-0.34,0.72,0.18],elbowR:[0.34,0.72,0.18],handL:[-0.40,0.48,0.30],handR:[0.40,0.48,0.30],hip:[0,0.40,0],hipL:[-0.18,0.38,0.12],hipR:[0.18,0.38,0.12],kneeL:[-0.36,0.30,0.28],kneeR:[0.36,0.30,0.28],footL:[-0.44,0.16,0.40],footR:[0.44,0.16,0.40]}};
function buildFigure(j:JointSet,c:string):React.ReactNode[]{const r:React.ReactNode[]=[];let k=0;const cyl=(a:Vec3,b:Vec3,rad:number)=>{const mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2,mz=(a[2]+b[2])/2;const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2];const len=Math.sqrt(dx*dx+dy*dy+dz*dz);const q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(dx,dy,dz).normalize());r.push(<mesh key={k++} position={[mx,my,mz]} quaternion={q} scale={[rad,len/2,rad]}><cylinderGeometry args={[1,1,2,10]}/><meshLambertMaterial color={c}/></mesh>);};const sph=(p:Vec3,rad:number)=>{r.push(<mesh key={k++} position={p} scale={rad}><sphereGeometry args={[1,14,14]}/><meshLambertMaterial color={c}/></mesh>);};const box=(p:Vec3,scl:Vec3)=>{r.push(<mesh key={k++} position={p} scale={scl}><boxGeometry/><meshLambertMaterial color={c}/></mesh>);};cyl(j.neck,j.hip,0.20);sph(j.head,0.14);sph(j.neck,0.07);sph(j.shoulderL,0.07);sph(j.shoulderR,0.07);cyl(j.shoulderL,j.elbowL,0.075);cyl(j.shoulderR,j.elbowR,0.075);sph(j.elbowL,0.055);sph(j.elbowR,0.055);cyl(j.elbowL,j.handL,0.065);cyl(j.elbowR,j.handR,0.065);sph(j.handL,0.055);sph(j.handR,0.055);sph(j.hip,0.10);cyl(j.hipL,j.kneeL,0.10);cyl(j.hipR,j.kneeR,0.10);sph(j.kneeL,0.065);sph(j.kneeR,0.065);cyl(j.kneeL,j.footL,0.085);cyl(j.kneeR,j.footR,0.085);box([j.footL[0],j.footL[1]-0.06,j.footL[2]+0.04],[0.10,0.04,0.14]);box([j.footR[0],j.footR[1]-0.06,j.footR[2]+0.04],[0.10,0.04,0.14]);return r;}
function StickFigure({poseId,color='#c0c8d0'}:{poseId:string;color?:string}){const j=POSE_JOINTS[poseId||'stand'];return j?<group>{buildFigure(j,color)}</group>:null;}
const OBJ_COLORS=['#8899aa','#99aabb','#aabbcc','#778899','#b0bec5'];const pickColor=()=>OBJ_COLORS[Math.floor(Math.random()*OBJ_COLORS.length)];
function lambertize(child:any){if(child.isMesh&&child.material?.isMeshStandardMaterial){const old=child.material;const L=new THREE.MeshLambertMaterial();L.color.copy(old.color);L.map=old.map;child.material=L;}}
function SafeModel({poseId,figureSrc,fallback}:{poseId:string;figureSrc?:string;fallback:React.ReactNode}){const src=figureSrc||(poseRegistry.get(poseId)?.src);const[exists,setExists]=useState<boolean|string>('loading');useEffect(()=>{if(!src){setExists(false);return;}if(src.startsWith('data:')||src.startsWith('blob:')){setExists(src);return;}let c=false;fetch(src,{method:'HEAD'}).then(r=>{if(!c)setExists(r.ok?src:false);}).catch(()=>{if(!c)setExists(false);});return()=>{c=true;};},[src]);if(exists==='loading')return null;if(!exists||typeof exists!=='string')return<>{fallback}</>;return<ModelEB fallback={fallback}><GLBModel src={exists as string}/></ModelEB>;}
class ModelEB extends React.Component<{fallback:React.ReactNode;children:React.ReactNode},{err:boolean}>{constructor(p:{fallback:React.ReactNode;children:React.ReactNode}){super(p);this.state={err:false};}static getDerivedStateFromError(){return{err:true};}render(){return this.state.err?this.props.fallback:this.props.children;}}
function GLBModel({src}:{src:string}){const{scene}=useGLTF(src);const cloned=useMemo(()=>{const s=scene.clone(true);s.traverse(lambertize);return s;},[scene]);const wrapped=useMemo(()=>{const g=new THREE.Group();g.add(cloned.clone(true));return g;},[cloned]);return<primitive object={wrapped}/>;}
const SCALE_FACTOR=0.12;
function RotationGizmo({center,onRotate}:{center:Vec3;onRotate:(axis:0|1|2,dx:number,dy:number)=>void}){const{gl,camera}=useThree();const gRef=useRef<THREE.Group>(null);const drag=useRef<{axis:0|1|2;lastX:number;lastY:number}|null>(null);useFrame(()=>{if(!gRef.current)return;const d=camera.position.distanceTo(new THREE.Vector3(...center));gRef.current.scale.setScalar(d*SCALE_FACTOR);});const onDown=useCallback((axis:0|1|2)=>(e:any)=>{e.stopPropagation();if(drag.current)return;window.dispatchEvent(new CustomEvent('gizmo-drag-start'));drag.current={axis,lastX:e.clientX,lastY:e.clientY};(gl.domElement as any).style.cursor='grabbing';},[gl.domElement]);useEffect(()=>{const mv=(e:PointerEvent)=>{if(!drag.current)return;const dx=e.clientX-drag.current.lastX,dy=e.clientY-drag.current.lastY;drag.current.lastX=e.clientX;drag.current.lastY=e.clientY;onRotate(drag.current.axis,dx,dy);};const up=()=>{if(!drag.current)return;(gl.domElement as any).style.cursor='';window.dispatchEvent(new CustomEvent('gizmo-drag-end'));drag.current=null;};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);};},[onRotate,gl.domElement]);const W=0.05;return(<group ref={gRef} position={center as[number,number,number]}><group onPointerDown={onDown(2)}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#4488ff" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group><group onPointerDown={onDown(1)} rotation={[Math.PI/2,0,0]}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#ddbb00" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group><group onPointerDown={onDown(0)} rotation={[0,-Math.PI/2,0]}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group></group>);}
function CameraGLB({pos,tgt}:{pos:Vec3;tgt:Vec3}){const{scene}=useGLTF('/models/camera.glb');const cloned=useMemo(()=>{const c=scene.clone(true);c.traverse((ch:any)=>{if(ch.isMesh){ch.castShadow=true;if(ch.material){ch.material.roughness=0.5;ch.material.metalness=0;ch.material.emissive=ch.material.emissive||new THREE.Color('#444');ch.material.emissiveIntensity=0.3;}}});return c;},[scene]);return<primitive object={cloned} position={pos} lookAt={tgt} scale={0.5}/>;}
function FallbackCamera({pos,tgt}:{pos:Vec3;tgt:Vec3}){return<group position={pos as[number,number,number]}><mesh lookAt={tgt}><boxGeometry args={[0.45,0.28,0.4]}/><meshStandardMaterial color="#3a3a44" roughness={0.5}/></mesh><mesh lookAt={tgt} position={[0,-0.04,0.22]}><boxGeometry args={[0.38,0.16,0.2]}/><meshStandardMaterial color="#f44" emissive="#f22" emissiveIntensity={0.6}/></mesh><mesh lookAt={tgt} position={[0,0,0.28]}><cylinderGeometry args={[0.09,0.07,0.16,12]}/><meshStandardMaterial color="#555" roughness={0.3}/></mesh></group>;}
class ErrorBoundary extends React.Component<{fallback:React.ReactNode;children:React.ReactNode},{err:boolean}>{constructor(p:any){super(p);this.state={err:false};}static getDerivedStateFromError(){return{err:true};}render(){return this.state.err?this.props.fallback:this.props.children;}}
const SENSOR_H=18.17;
const LENSES:Record<string,{name:string;fov:number;maxAperture:number;minAperture:number;blades:number}>={
'24':{name:'24mm',fov:2*Math.atan(SENSOR_H/(2*24))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'35':{name:'35mm',fov:2*Math.atan(SENSOR_H/(2*35))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'50':{name:'50mm',fov:2*Math.atan(SENSOR_H/(2*50))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'85':{name:'85mm',fov:2*Math.atan(SENSOR_H/(2*85))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'135':{name:'135mm',fov:2*Math.atan(SENSOR_H/(2*135))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
};

const mover=(el:THREE.Object3D,obj:SceneObject)=>{const p:Vec3=[el.position.x,el.position.y,el.position.z];const r:Vec3=[el.rotation.x,el.rotation.y,el.rotation.z];const s:Vec3=[el.scale.x,el.scale.y,el.scale.z];const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);window.dispatchEvent(new CustomEvent('scene3d-object-moved',{detail:{id:obj.id,position:p,rotation:r,scale:s,forward:[fwd.x,fwd.y,fwd.z]as Vec3,objRef:el}}));};
function SceneContent({objects,selectedId,onSelect,gizmoMode}:{objects:SceneObject[];selectedId:string|null;onSelect:(id:string|null)=>void;gizmoMode:GizmoMode;}){
  const meshRefs=useRef<Map<string,THREE.Object3D>>(new Map());const orbitRef=useRef<any>(null);useEffect(()=>{const s=()=>{if(orbitRef.current)orbitRef.current.enabled=false;};const e=()=>{if(orbitRef.current)orbitRef.current.enabled=true;};window.addEventListener('gizmo-drag-start',s);window.addEventListener('gizmo-drag-end',e);return()=>{window.removeEventListener('gizmo-drag-start',s);window.removeEventListener('gizmo-drag-end',e);};},[]);
  return(<><ambientLight intensity={0.35}/><hemisphereLight args={['#ffffff','#606060',0.65]}/><Grid position={[0,-0.01,0]} args={[20,20]} cellSize={1} cellThickness={0.5} cellColor="#aaaaaa" sectionSize={5} sectionThickness={1.5} sectionColor="#cccccc" fadeDistance={25} infiniteGrid/>
    <mesh onClick={()=>onSelect(null)} position={[0,-0.02,0]} rotation={[-Math.PI/2,0,0]} visible={false}><planeGeometry args={[100,100]}/></mesh>
    {objects.map(obj=>{const sel=selectedId===obj.id;const bottomY=obj.type==='figure'||obj.type==='plane'?0:0.5;return(<group key={obj.id}>
      <group position={obj.position} rotation={obj.rotation} scale={obj.scale} ref={el=>{if(el){meshRefs.current.set(obj.id,el);if(obj.type==='camera'){const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);window.dispatchEvent(new CustomEvent('cam-ready',{detail:{objRef:el,forward:[fwd.x,fwd.y,fwd.z]as Vec3}}));}}}}>
        {obj.type==='figure'?<SafeModel poseId={obj.figurePose||''} figureSrc={obj.figureSrc} fallback={<StickFigure poseId={obj.figurePose||'stand'} color={obj.color||'#c0c8d0'}/>}/>:
        obj.type==='camera'?<><mesh rotation={[-Math.PI/2,0,0]} position={[0,0.2,-0.6]}><cylinderGeometry args={[0.01,0.01,1,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6}/></mesh><mesh position={[0,0,-3]}><sphereGeometry args={[0.08,8,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.5}/></mesh><ErrorBoundary fallback={<FallbackCamera pos={[0,0,0]} tgt={[0,0,-3]}/>}><Suspense fallback={null}><CameraGLB pos={[0,0,0]} tgt={[0,0,-3]}/></Suspense></ErrorBoundary></>:
        <mesh>{obj.type==='box'&&<boxGeometry/>}{obj.type==='sphere'&&<sphereGeometry args={[0.5,28,28]}/>}{obj.type==='cylinder'&&<cylinderGeometry args={[0.5,0.5,1,24]}/>}{obj.type==='plane'&&<planeGeometry/>}<meshLambertMaterial color={obj.color||'#8899aa'}/></mesh>}
      </group>
      {sel&&<lineSegments position={obj.position} rotation={obj.rotation}><edgesGeometry args={[new THREE.BoxGeometry(0.6,0.6,0.6)]}/><lineBasicMaterial color="#60a0ff" opacity={0.6} transparent/></lineSegments>}
      {sel&&gizmoMode==='rotate'&&<RotationGizmo center={[obj.position[0],obj.position[1]-bottomY,obj.position[2]]as Vec3} onRotate={(axis,dx,dy)=>{const el=meshRefs.current.get(obj.id);if(el){el.rotation[('xyz'[axis])as'x'|'y'|'z']+=(axis===0?dy*0.008:axis===1?dx*0.008:-dx*0.008);mover(el,obj);}}}/>}
      {sel&&gizmoMode==='translate'&&<TransformControls object={meshRefs.current.get(obj.id)||undefined} mode="translate" size={0.65} onObjectChange={()=>{const el=meshRefs.current.get(obj.id);if(el){window.dispatchEvent(new CustomEvent('gizmo-drag-start'));mover(el,obj);}}} onMouseUp={()=>{window.dispatchEvent(new CustomEvent('gizmo-drag-end'));}}/>}
      {sel&&gizmoMode==='scale'&&<TransformControls object={meshRefs.current.get(obj.id)||undefined} mode="scale" size={0.65} onObjectChange={()=>{const el=meshRefs.current.get(obj.id);if(el){window.dispatchEvent(new CustomEvent('gizmo-drag-start'));mover(el,obj);}}} onMouseUp={()=>{window.dispatchEvent(new CustomEvent('gizmo-drag-end'));}}/>}
      <mesh position={[obj.position[0],obj.position[1]-(obj.type==='figure'||obj.type==='plane'?0:0.5),obj.position[2]]} onClick={e=>{e.stopPropagation();onSelect(obj.id);}}><sphereGeometry args={[0.2,8,8]}/><meshBasicMaterial color="#60a0ff" transparent opacity={0.01}/></mesh>
      {sel&&<mesh position={[obj.position[0],obj.position[1]-(obj.type==='figure'||obj.type==='plane'?0:0.5),obj.position[2]]}><sphereGeometry args={[0.15,8,8]}/><meshBasicMaterial color="#60a0ff" transparent opacity={0.6}/></mesh>}
    </group>);})}
    <OrbitControls ref={orbitRef} makeDefault enableDamping dampingFactor={0.08} minDistance={2} maxDistance={25} maxPolarAngle={Math.PI/2+0.2} target={[0,1,0]}/>
  </>);
}

function EBtn({label,active,onClick}:{label:string;active?:boolean;onClick:()=>void}){return<button onClick={onClick} style={{padding:'6px 10px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',border:active?'1px solid rgba(255,255,255,0.25)':'1px solid rgba(255,255,255,0.08)',background:active?'rgba(255,255,255,0.12)':'transparent',color:active?'#fff':'rgba(255,255,255,0.5)',whiteSpace:'nowrap',transition:'all 0.12s ease'}} onMouseEnter={e=>{e.currentTarget.style.background='rgba(255,255,255,0.1)';e.currentTarget.style.color='#fff';}} onMouseLeave={e=>{e.currentTarget.style.background=active?'rgba(255,255,255,0.12)':'transparent';e.currentTarget.style.color=active?'#fff':'rgba(255,255,255,0.5)';}}>{label}</button>;}

function PiPCam({camRef}:{camRef:React.MutableRefObject<THREE.Object3D|null>}){const{camera}=useThree();useFrame(()=>{const el=camRef.current;if(!el)return;camera.position.copy(el.position);const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);camera.lookAt(fwd);});return null;}

function FullscreenEditor({objects,selectedId,setObjects,setSelectedId,onSnapshot,onClose,nodeId}:{objects:SceneObject[];selectedId:string|null;setObjects:React.Dispatch<React.SetStateAction<SceneObject[]>>;setSelectedId:React.Dispatch<React.SetStateAction<string|null>>;onSnapshot:()=>void;onClose:()=>void;nodeId:string;}){
  const counter=useRef(objects.length);const[gizmoMode,setGizmoMode]=useState<GizmoMode>('translate');
  const undoStack=useRef<SceneObject[][]>([]);const redoStack=useRef<SceneObject[][]>([]);const dragSaved=useRef(false);
  const[showCam,setShowCam]=useState(false);const[vcamLens,setVcamLens]=useState('50');const[vcamAperture,setVcamAperture]=useState(2.8);
  const activeCamRef=useRef<THREE.Object3D|null>(null);const pipCanvasRef=useRef<HTMLDivElement>(null);const lensData=LENSES[vcamLens];

  const pushUndo=useCallback((snap:SceneObject[])=>{undoStack.current.push(snap);if(undoStack.current.length>50)undoStack.current.shift();redoStack.current=[];},[]);
  const doUndo=useCallback(()=>{const prev=undoStack.current.pop();if(!prev)return;redoStack.current.push(objects);setObjects(prev);},[objects]);
  const doRedo=useCallback(()=>{const next=redoStack.current.pop();if(!next)return;undoStack.current.push(objects);setObjects(next);},[objects]);
  useEffect(()=>{const h=()=>{if(!dragSaved.current){pushUndo(objects);dragSaved.current=true;}};window.addEventListener('gizmo-drag-start',h);return()=>window.removeEventListener('gizmo-drag-start',h);},[objects,pushUndo]);
  useEffect(()=>{const h=()=>{dragSaved.current=false;};window.addEventListener('gizmo-drag-end',h);return()=>window.removeEventListener('gizmo-drag-end',h);},[]);
  useEffect(()=>{initPoseRegistry();},[]);
  useEffect(()=>{const h=(e:Event)=>{const{id,position,rotation,scale,objRef}=(e as CustomEvent).detail as{id:string;position:Vec3;rotation?:Vec3;scale?:Vec3;objRef?:THREE.Object3D};setObjects(prev=>prev.map(o=>o.id===id?{...o,position,rotation:rotation||o.rotation,scale:scale||o.scale}:o));if(objRef&&(objRef as any).type==='camera')activeCamRef.current=objRef;};window.addEventListener('scene3d-object-moved',h);return()=>window.removeEventListener('scene3d-object-moved',h);},[setObjects]);
  useEffect(()=>{const h=(e:Event)=>{const{objRef}=(e as CustomEvent).detail as{objRef:THREE.Object3D};if(objRef)activeCamRef.current=objRef;};window.addEventListener('cam-ready',h);return()=>window.removeEventListener('cam-ready',h);},[]);

  const addObj=useCallback((type:SceneObject['type'])=>{counter.current++;const y=type==='figure'||type==='plane'?0:0.5;const first=poseRegistry.size>0?poseRegistry.keys().next().value as string:'stand1';const obj:SceneObject={id:`o_${counter.current}`,type,position:[0,y,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:type==='figure'?first:undefined,figureSrc:type==='figure'?poseRegistry.get(first)?.src:undefined};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);},[setObjects,setSelectedId,objects,pushUndo]);
  const addCamera=useCallback(()=>{counter.current++;const obj:SceneObject={id:`o_${counter.current}`,type:'camera',position:[8,2,5],rotation:[0,0,0],scale:[1,1,1]};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);},[setObjects,setSelectedId,objects,pushUndo]);
  const updatePose=useCallback((pose:string)=>{const e=poseRegistry.get(pose);setObjects(prev=>prev.map(o=>o.id===selectedId&&o.type==='figure'?{...o,figurePose:pose,figureSrc:e?.src}:o));},[selectedId,setObjects]);
  const selObj=objects.find(o=>o.id===selectedId);

  const onKey=(e:React.KeyboardEvent)=>{if(e.ctrlKey&&e.key==='z'){e.preventDefault();doUndo();return;}if(e.ctrlKey&&(e.key==='y'||(e.shiftKey&&e.key==='z'))){e.preventDefault();doRedo();return;}if(e.key==='Escape'){if(selectedId)setSelectedId(null);else onClose();}if((e.key==='Delete'||e.key==='Backspace')&&selectedId){e.preventDefault();e.stopPropagation();pushUndo(objects);setObjects(prev=>prev.filter(o=>o.id!==selectedId));setSelectedId(null);}};

  return createPortal(<div onKeyDown={onKey} tabIndex={-1} ref={el=>el?.focus()} style={{position:'fixed',inset:0,zIndex:99999,outline:'none',background:'#3a3a3a',display:'flex',flexDirection:'column',animation:'tap-fade-in 0.15s ease'}}>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'8px 14px',background:'rgba(0,0,0,0.3)',flexShrink:0}}><span style={{fontSize:14,fontWeight:600,color:'#ccc'}}>3D 场景编辑器</span><div style={{display:'flex',gap:8}}><EBtn label="截图" onClick={onSnapshot}/><button onClick={onClose} style={{padding:'6px 16px',background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:8,color:'#ccc',cursor:'pointer',fontSize:13}}>退出</button></div></div>
    <div style={{flex:1,display:'flex',minHeight:0}}>
      <div style={{width:90,display:'flex',flexDirection:'column',gap:5,padding:'10px 7px',borderRight:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0,alignItems:'center',background:'rgba(0,0,0,0.2)'}}>
        <div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>几何体</div><EBtn label="立方体" onClick={()=>addObj('box')}/><EBtn label="球体" onClick={()=>addObj('sphere')}/><EBtn label="圆柱" onClick={()=>addObj('cylinder')}/><EBtn label="平面" onClick={()=>addObj('plane')}/>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>人物</div><EBtn label="添加人物" onClick={()=>addObj('figure')}/>
        {selObj?.type==='figure'&&<select value={selObj.figurePose||''} onChange={e=>updatePose(e.target.value)} style={{marginTop:4,width:'100%',padding:5,background:'rgba(0,0,0,0.15)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:8,color:'#ccc',fontSize:10,cursor:'pointer'}}>{[...poseRegistry.entries()].map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select>}
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>摄像</div><EBtn label="加摄像机" onClick={addCamera}/><EBtn label={showCam?'关取景器':'开取景器'} onClick={()=>setShowCam(!showCam)} active={showCam}/>
      </div>
      <div style={{flex:1,minWidth:0,position:'relative'}} onDragOver={e=>{e.preventDefault();e.stopPropagation();}} onDrop={e=>{e.preventDefault();e.stopPropagation();const f=e.dataTransfer.files[0];if(!f||!f.name.match(/\.(glb|fbx)$/i))return;importFile(f,(entry,poseId)=>{counter.current++;const obj:SceneObject={id:`o_${counter.current}`,type:'figure',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:poseId,figureSrc:entry.src};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);});}}>
        <Canvas shadows camera={{position:[5,4,7],fov:50,near:0.1,far:100}} gl={{preserveDrawingBuffer:true,antialias:false,powerPreference:'high-performance'}} dpr={[0.5,1.5]} style={{width:'100%',height:'100%'}}><Suspense fallback={null}><SceneContent objects={objects} selectedId={selectedId} onSelect={setSelectedId} gizmoMode={gizmoMode}/></Suspense></Canvas>
      </div>
      <div style={{width:160,padding:'10px',borderLeft:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0,background:'rgba(0,0,0,0.15)'}}><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:8}}>属性</div>
        {selObj?<div style={{display:'flex',flexDirection:'column',gap:8}}>
          <div style={{fontSize:12,color:'rgba(255,255,255,0.55)'}}>类型:<span style={{color:'#ccc'}}>{selObj.type==='box'?'立方体':selObj.type==='sphere'?'球体':selObj.type==='cylinder'?'圆柱':selObj.type==='plane'?'平面':selObj.type==='camera'?'摄像机':'人物'}</span></div>
          {selObj.type==='figure'&&<div style={{fontSize:12,color:'rgba(255,255,255,0.55)'}}>姿态:<span style={{color:'#ccc'}}>{poseRegistry.get(selObj.figurePose||'')?.name||selObj.figurePose}</span></div>}
          <div style={{display:'flex',gap:4}}><button onClick={()=>setGizmoMode('translate')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='translate'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='translate'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='translate'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>移动</button><button onClick={()=>setGizmoMode('rotate')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='rotate'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='rotate'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='rotate'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>旋转</button><button onClick={()=>setGizmoMode('scale')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='scale'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='scale'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='scale'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>缩放</button></div>
          <div style={{fontSize:11,color:'rgba(255,255,255,0.55)'}}>位置<br/><span style={{color:'#ccc',fontSize:10}}>X:{selObj.position[0].toFixed(1)} Y:{selObj.position[1].toFixed(1)} Z:{selObj.position[2].toFixed(1)}</span></div>
          <button onClick={()=>{pushUndo(objects);setObjects(prev=>prev.map(o=>o.id===selectedId?{...o,position:[0,o.type==='figure'||o.type==='plane'?0:0.5,0]as Vec3,rotation:[0,0,0]as Vec3}:o));}} style={{padding:6,borderRadius:6,fontSize:10,cursor:'pointer',background:'rgba(200,160,0,0.08)',border:'1px solid rgba(200,160,0,0.2)',color:'#886600',width:'100%'}}>复位</button>
          <button onClick={()=>{pushUndo(objects);setObjects(prev=>prev.filter(o=>o.id!==selectedId));setSelectedId(null);}} style={{padding:7,background:'rgba(200,60,60,0.08)',border:'1px solid rgba(200,60,60,0.2)',borderRadius:8,color:'#664444',fontSize:11,cursor:'pointer',width:'100%'}}>删除</button>
        </div>:<div style={{fontSize:10,color:'rgba(255,255,255,0.2)',lineHeight:1.6}}>点击物体选中<br/>拖GLB导入<br/>右键旋转视角<br/>Esc取消选中<br/>Del删除选中</div>}
      </div>
    </div>
    {showCam&&<div style={{position:'absolute',bottom:40,right:16,zIndex:100,width:680,background:'#111',borderRadius:12,overflow:'hidden',border:'2px solid #333',boxShadow:'0 0 20px rgba(0,0,0,0.5)'}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'4px 8px',background:'#1a1a1a',gap:4}}><span style={{fontSize:10,color:'#e44',fontWeight:600}}>● REC</span><select value={vcamLens} onChange={e=>setVcamLens(e.target.value)} style={{background:'#222',border:'1px solid #444',borderRadius:4,color:'#ccc',fontSize:10,padding:'2px 4px'}}>{Object.entries(LENSES).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select><select value={vcamAperture} onChange={e=>setVcamAperture(Number(e.target.value))} style={{background:'#222',border:'1px solid #444',borderRadius:4,color:'#ccc',fontSize:10,padding:'2px 4px'}}>{[1.3,1.4,2,2.8,4,5.6,8,11,16,22].map(v=><option key={v} value={v}>T{v}</option>)}</select><button onClick={()=>{const c=pipCanvasRef.current?.querySelector('canvas');if(!c)return;const u=c.toDataURL('image/png');const s=useCanvasStore.getState();const cn=s.nodes.get(nodeId);const nx=(cn?.pos?.x||0)+540;const ny=cn?.pos?.y||0;const nid=s.addNode('image.generate',{x:nx,y:ny},'PiP '+vcamLens+' T'+vcamAperture);s.updateNode(nid,{meta:{gen:{imageUrl:u,prompt:'',model:'GPT Image2',aspect:'16:9',resolution:'2K',quality:'high',resultAssetIds:[]}}});s.triggerSync();}} style={{background:'#c44',border:'1px solid #e66',borderRadius:4,color:'#fff',fontSize:10,padding:'2px 8px',cursor:'pointer',fontWeight:600}}>📸</button><span style={{fontSize:9,color:'#888'}}>ARRI S35</span></div>
      <div ref={pipCanvasRef} style={{position:'relative',width:'100%',height:380}}>
        <Canvas key={vcamLens} camera={{position:[0,0,0],fov:lensData.fov,near:0.1,far:100}} gl={{antialias:true,preserveDrawingBuffer:true}} style={{width:'100%',height:'100%'}}>
          <PiPCam camRef={activeCamRef}/>
          <ambientLight intensity={0.35}/><hemisphereLight args={['#ffffff','#606060',0.65]}/>
          <Grid position={[0,-0.01,0]} args={[20,20]} cellSize={1} cellThickness={0.5} cellColor="#666" sectionSize={5} sectionThickness={1.5} sectionColor="#999" fadeDistance={25} infiniteGrid/>
          {objects.map(o=><group key={o.id} position={o.position} rotation={o.rotation} scale={o.scale}>{o.type==='figure'?o.figureSrc?<GLBModel src={o.figureSrc}/>:null:o.type==='box'?<mesh><boxGeometry/><meshLambertMaterial color={o.color||'#8899aa'}/></mesh>:o.type==='sphere'?<mesh><sphereGeometry args={[0.5,16,16]}/><meshLambertMaterial color={o.color||'#8899aa'}/></mesh>:o.type==='cylinder'?<mesh><cylinderGeometry args={[0.5,0.5,1,16]}/><meshLambertMaterial color={o.color||'#8899aa'}/></mesh>:o.type==='plane'?<mesh><planeGeometry/><meshLambertMaterial color={o.color||'#8899aa'}/></mesh>:null}</group>)}
        </Canvas>
        <div style={{position:'absolute',inset:0,pointerEvents:'none',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:'80%',height:'80%',border:'1px solid rgba(255,255,255,0.3)'}}/></div>
      </div>
    </div>}
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:20,padding:'5px 16px',borderTop:'1px solid rgba(255,255,255,0.06)',flexShrink:0,fontSize:10,color:'rgba(255,255,255,0.2)',background:'rgba(0,0,0,0.15)'}}><span>左键选中</span><span>移动/旋转/缩放</span><span>右键视角</span><span>Esc取消</span><span>Ctrl+Z撤销</span></div>
  </div>,document.body);
}

const NODE_W=500,NODE_H=300;
export function Scene3DNode({id,data,selected}:{id:string;data:{title?:string;isConnecting?:boolean;isConnectTarget?:boolean;multiSelect?:boolean;isPickMode?:boolean;isPickTarget?:boolean;onChange?:(p:Record<string,unknown>)=>void;};selected?:boolean;}){
  const[objects,setObjects]=useState<SceneObject[]>([]);const[selId,setSelId]=useState<string|null>(null);const[fs,setFs]=useState(false);const[gizmoMode,setGizmoMode]=useState<GizmoMode>('translate');const ctr=useRef(0);
  useEffect(()=>{initPoseRegistry();},[]);
  useEffect(()=>{const h=(e:Event)=>{const{id,position,rotation,scale}=(e as CustomEvent).detail as{id:string;position:Vec3;rotation?:Vec3;scale?:Vec3};setObjects(prev=>prev.map(o=>o.id===id?{...o,position,rotation:rotation||o.rotation,scale:scale||o.scale}:o));};window.addEventListener('scene3d-object-moved',h);return()=>window.removeEventListener('scene3d-object-moved',h);},[]);
  const addObj=useCallback((type:SceneObject['type'])=>{ctr.current++;const y=type==='figure'||type==='plane'?0:0.5;const first=poseRegistry.size>0?poseRegistry.keys().next().value as string:'stand1';const obj:SceneObject={id:`o_${ctr.current}`,type,position:[0,y,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:type==='figure'?first:undefined,figureSrc:type==='figure'?poseRegistry.get(first)?.src:undefined};setObjects(prev=>[...prev,obj]);setSelId(obj.id);},[]);
  const delSel=useCallback(()=>{if(!selId)return;setObjects(prev=>prev.filter(o=>o.id!==selId));setSelId(null);},[selId]);
  const hSnap=useCallback(()=>{const c=document.querySelector('canvas');if(!c)return;const u=c.toDataURL('image/png');const store=useCanvasStore.getState();const n=store.nodes.get(id);if(n){const m=(n.meta||{})as Record<string,unknown>;store.updateNode(id,{meta:{...m,gen:{...((m.gen as Record<string,unknown>)||{}),imageUrl:u}}});store.triggerSync();}},[id]);
  return(<>{fs&&<FullscreenEditor objects={objects} selectedId={selId} setObjects={setObjects} setSelectedId={setSelId} onSnapshot={hSnap} onClose={()=>setFs(false)} nodeId={id}/>}
    <div style={{width:NODE_W,background:'rgba(18,20,24,0.95)',border:selected?'2px solid rgba(100,140,255,0.7)':'1px solid rgba(255,255,255,0.08)',borderRadius:14,overflow:'hidden',boxShadow:selected?'0 0 24px rgba(100,140,255,0.18)':'0 4px 16px rgba(0,0,0,0.3)',transition:'border 0.15s, box-shadow 0.15s'}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'6px 12px',borderBottom:'1px solid rgba(255,255,255,0.06)',fontSize:12,color:'rgba(255,255,255,0.5)',fontWeight:600,flexShrink:0}}><span>🎬 {data.title||'3D 场景'}</span><span style={{fontSize:10,color:'rgba(255,255,255,0.2)'}}>{objects.length} 物体</span></div>
      <div style={{width:'100%',height:NODE_H,position:'relative',background:'#3a3a3a',overflow:'hidden'}}><Canvas shadows camera={{position:[5,4,7],fov:50,near:0.1,far:100}} gl={{preserveDrawingBuffer:true,antialias:false,powerPreference:'high-performance'}} dpr={[0.5,1.5]} style={{width:'100%',height:'100%'}}><Suspense fallback={null}><SceneContent objects={objects} selectedId={selId} onSelect={setSelId} gizmoMode={gizmoMode}/></Suspense></Canvas>
        {selected?<button onClick={()=>setFs(true)} className="nodrag" style={{position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-50%)',padding:'10px 24px',borderRadius:10,fontSize:13,fontWeight:600,background:'rgba(100,140,255,0.15)',border:'1px solid rgba(100,140,255,0.3)',color:'rgba(140,170,255,0.9)',cursor:'pointer',zIndex:5}}>⛶ 全屏编辑</button>:<div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,0.4)',pointerEvents:'none'}}><div style={{textAlign:'center'}}><div style={{fontSize:36,opacity:0.15}}>🎬</div><div style={{fontSize:12,color:'rgba(255,255,255,0.35)',marginTop:4}}>选中节点开始编辑</div></div></div>}
      </div>
      <div style={{display:'flex',alignItems:'center',gap:5,padding:'6px 10px',borderTop:'1px solid rgba(255,255,255,0.06)',flexShrink:0,overflowX:'auto'}}><EBtn label="立方体" onClick={()=>addObj('box')}/><EBtn label="球体" onClick={()=>addObj('sphere')}/><EBtn label="圆柱" onClick={()=>addObj('cylinder')}/><EBtn label="平面" onClick={()=>addObj('plane')}/><EBtn label="人物" onClick={()=>addObj('figure')}/><span style={{flex:1}}/><button onClick={()=>setGizmoMode('translate')} title="移动" style={{padding:'4px 8px',borderRadius:5,fontSize:11,cursor:'pointer',background:gizmoMode==='translate'?'rgba(100,140,255,0.15)':'transparent',border:gizmoMode==='translate'?'1px solid rgba(100,140,255,0.25)':'1px solid transparent',color:gizmoMode==='translate'?'#a0c0ff':'rgba(255,255,255,0.35)'}}>↕</button><button onClick={()=>setGizmoMode('rotate')} title="旋转" style={{padding:'4px 8px',borderRadius:5,fontSize:11,cursor:'pointer',background:gizmoMode==='rotate'?'rgba(100,140,255,0.15)':'transparent',border:gizmoMode==='rotate'?'1px solid rgba(100,140,255,0.25)':'1px solid transparent',color:gizmoMode==='rotate'?'#a0c0ff':'rgba(255,255,255,0.35)'}}>↻</button><button onClick={()=>setGizmoMode('scale')} title="缩放" style={{padding:'4px 8px',borderRadius:5,fontSize:11,cursor:'pointer',background:gizmoMode==='scale'?'rgba(100,140,255,0.15)':'transparent',border:gizmoMode==='scale'?'1px solid rgba(100,140,255,0.25)':'1px solid transparent',color:gizmoMode==='scale'?'#a0c0ff':'rgba(255,255,255,0.35)'}}>⤡</button>{selId&&<EBtn label="删除" onClick={delSel}/>}</div>
      <Handle type="target" position={Position.Left} id="image-in" style={{background:'rgba(180,180,200,0.5)',width:10,height:10,border:'none'}}/>
      <Handle type="source" position={Position.Right} id="image-out" style={{background:'rgba(180,180,200,0.5)',width:10,height:10,border:'none'}}/>
    </div>
  </>);
}