/* === Scene3DNode v2 — clean rewrite === */
import React,{useState,useCallback,useMemo,useRef,useEffect,Suspense}from'react';
import{createPortal}from'react-dom';
import{Handle,Position}from'@xyflow/react';
import{Canvas,useThree,useFrame}from'@react-three/fiber';
import{OrbitControls,Grid,TransformControls,useGLTF,useFBX,useTexture,useAnimations}from'@react-three/drei';
import{Sky}from'three/examples/jsm/objects/Sky';
import{FBXLoader}from'three/examples/jsm/loaders/FBXLoader';
import*as THREE from'three';
const animMixers:THREE.AnimationMixer[]=[];let animTime=0;let animPlaying=false;
import{useCanvasStore}from'../../store/useCanvasStore';

// Types
interface SceneObject{id:string;type:'box'|'sphere'|'cylinder'|'plane'|'figure'|'camera';position:Vec3;rotation:Vec3;scale:Vec3;color?:string;figurePose?:string;figureSrc?:string;}
type Vec3=[number,number,number];type GizmoMode='translate'|'rotate'|'scale';type TrackType='dolly'|'curved'|'orbit';interface SpeedKey{time:number;speed:number;}interface RotationKey{time:number;pitch:number;yaw:number;}interface CameraRig{type:TrackType;duration:number;speedCurve:SpeedKey[];rotationKeys:RotationKey[];dolly?:{pointA:Vec3;pointB:Vec3;};curved?:{controlPoints:{id:string;position:Vec3;}[];};orbit?:{center:Vec3;radius:number;height:number;startAngle:number;endAngle:number;};}
interface JointSet{head:Vec3;neck:Vec3;shoulderL:Vec3;shoulderR:Vec3;elbowL:Vec3;elbowR:Vec3;handL:Vec3;handR:Vec3;hip:Vec3;hipL:Vec3;hipR:Vec3;kneeL:Vec3;kneeR:Vec3;footL:Vec3;footR:Vec3;}
const KNOWN_POSES=['stand1','stand2','sit','walk','run','squat','lie','fight'];
type PoseEntry={name:string;src:string;format?:'glb'|'fbx'};
const poseRegistry=new Map<string,PoseEntry>();let poseInitDone=false;
async function initPoseRegistry(){if(poseInitDone)return;poseInitDone=true;const r=await Promise.all(KNOWN_POSES.map(async id=>{try{const r=await fetch(`/models/${id}.glb`,{method:'HEAD'});if(r.ok)return{id,ext:'glb'};}catch{}return null;}));r.filter(Boolean).forEach(x=>{if(x)poseRegistry.set(x.id,{name:PF[x.id]||x.id,src:`/models/${x.id}.glb`});});}
const PF:Record<string,string>={stand1:'站立1',stand2:'站立2',sit:'坐姿',walk:'行走',run:'跑步',squat:'蹲姿',lie:'卧躺',fight:'格斗'};
function importFile(file:File,done:(entry:PoseEntry,poseId:string)=>void){const name=file.name.replace(/\.(glb|fbx)$/i,'');const id=name.toLowerCase().replace(/[^a-z0-9]/g,'_')||`pose_${Date.now()}`;const ext=file.name.endsWith('.fbx')?'fbx':'glb';const r=new FileReader();r.onload=()=>{const src=r.result as string;const e:PoseEntry={name,src,format:ext};poseRegistry.set(id,e);done(e,id);};r.readAsDataURL(file);}
export function addPoseEntry(id:string,name:string,src:string,format?:'glb'|'fbx'){poseRegistry.set(id,{name,src,format});if(!poseInitDone)poseInitDone=true;}
const POSE_JOINTS:Record<string,JointSet>={stand:{head:[0,1.68,0],neck:[0,1.50,0],shoulderL:[-0.28,1.46,0],shoulderR:[0.28,1.46,0],elbowL:[-0.28,1.16,0],elbowR:[0.28,1.16,0],handL:[-0.28,0.86,0],handR:[0.28,0.86,0],hip:[0,0.85,0],hipL:[-0.14,0.83,0],hipR:[0.14,0.83,0],kneeL:[-0.14,0.42,0],kneeR:[0.14,0.42,0],footL:[-0.14,0.04,0],footR:[0.14,0.04,0]},sit:{head:[0,1.24,0],neck:[0,1.06,0],shoulderL:[-0.28,1.02,0],shoulderR:[0.28,1.02,0],elbowL:[-0.34,0.72,0.18],elbowR:[0.34,0.72,0.18],handL:[-0.40,0.48,0.30],handR:[0.40,0.48,0.30],hip:[0,0.40,0],hipL:[-0.18,0.38,0.12],hipR:[0.18,0.38,0.12],kneeL:[-0.36,0.30,0.28],kneeR:[0.36,0.30,0.28],footL:[-0.44,0.16,0.40],footR:[0.44,0.16,0.40]}};
function buildFigure(j:JointSet,c:string):React.ReactNode[]{const r:React.ReactNode[]=[];let k=0;const cyl=(a:Vec3,b:Vec3,rad:number)=>{const mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2,mz=(a[2]+b[2])/2;const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2];const len=Math.sqrt(dx*dx+dy*dy+dz*dz);const q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(dx,dy,dz).normalize());r.push(<mesh key={k++} position={[mx,my,mz]} quaternion={q} scale={[rad,len/2,rad]}><cylinderGeometry args={[1,1,2,10]}/><meshStandardMaterial color={c} roughness={0.5} metalness={0.2}/></mesh>);};const sph=(p:Vec3,rad:number)=>{r.push(<mesh key={k++} position={p} scale={rad}><sphereGeometry args={[1,14,14]}/><meshStandardMaterial color={c} roughness={0.5} metalness={0.2}/></mesh>);};const box=(p:Vec3,scl:Vec3)=>{r.push(<mesh key={k++} position={p} scale={scl}><boxGeometry/><meshStandardMaterial color={c} roughness={0.5} metalness={0.2}/></mesh>);};cyl(j.neck,j.hip,0.20);sph(j.head,0.14);sph(j.neck,0.07);sph(j.shoulderL,0.07);sph(j.shoulderR,0.07);cyl(j.shoulderL,j.elbowL,0.075);cyl(j.shoulderR,j.elbowR,0.075);sph(j.elbowL,0.055);sph(j.elbowR,0.055);cyl(j.elbowL,j.handL,0.065);cyl(j.elbowR,j.handR,0.065);sph(j.handL,0.055);sph(j.handR,0.055);sph(j.hip,0.10);cyl(j.hipL,j.kneeL,0.10);cyl(j.hipR,j.kneeR,0.10);sph(j.kneeL,0.065);sph(j.kneeR,0.065);cyl(j.kneeL,j.footL,0.085);cyl(j.kneeR,j.footR,0.085);box([j.footL[0],j.footL[1]-0.06,j.footL[2]+0.04],[0.10,0.04,0.14]);box([j.footR[0],j.footR[1]-0.06,j.footR[2]+0.04],[0.10,0.04,0.14]);return r;}
function StickFigure({poseId,color='#c0c8d0'}:{poseId:string;color?:string}){const j=POSE_JOINTS[poseId||'stand'];return j?<group>{buildFigure(j,color)}</group>:null;}
const OBJ_COLORS=['#8899aa','#99aabb','#aabbcc','#778899','#b0bec5'];const pickColor=()=>OBJ_COLORS[Math.floor(Math.random()*OBJ_COLORS.length)];
function standardize(child:any){if(child.isMesh&&child.material){const m=child.material;const gray=new THREE.Color('#aaaaaa');if(!m.isMeshStandardMaterial&&!m.isMeshPhysicalMaterial){const s=new THREE.MeshStandardMaterial();s.color.copy(gray);if(m.map)s.map=m.map;s.roughness=m.roughness??0.35;s.metalness=m.metalness??0.25;child.material=s;}else{m.color.copy(gray);}}}
function SafeModel({poseId,figureSrc,fallback}:{poseId:string;figureSrc?:string;fallback:React.ReactNode}){const src=figureSrc||(poseRegistry.get(poseId)?.src);const[exists,setExists]=useState<boolean|string>('loading');useEffect(()=>{if(!src){setExists(false);return;}if(src.startsWith('data:')||src.startsWith('blob:')){setExists(src);return;}let c=false;fetch(src,{method:'HEAD'}).then(r=>{if(!c)setExists(r.ok?src:false);}).catch(()=>{if(!c)setExists(false);});return()=>{c=true;};},[src]);if(exists==='loading')return null;if(!exists||typeof exists!=='string')return<>{fallback}</>;const fmt=(poseRegistry.get(poseId)||{src:figureSrc})as any;const isFBX=fmt?.format==='fbx'||exists.toString().endsWith('.fbx');return<ModelEB fallback={fallback}>{isFBX?<FBXModel src={exists as string}/>:<GLBModel src={exists as string}/>}</ModelEB>;}
class ModelEB extends React.Component<{fallback:React.ReactNode;children:React.ReactNode},{err:boolean}>{constructor(p:{fallback:React.ReactNode;children:React.ReactNode}){super(p);this.state={err:false};}static getDerivedStateFromError(){return{err:true};}render(){return this.state.err?this.props.fallback:this.props.children;}}
function GLBModel({src}:{src:string}){const{scene,animations}=useGLTF(src);const cloned=useMemo(()=>{const s=scene.clone(true);s.traverse(standardize);return s;},[scene]);const wrapped=useMemo(()=>{const g=new THREE.Group();g.add(cloned.clone(true));return g;},[cloned]);useEffect(()=>{if(animations.length>0){const m=new THREE.AnimationMixer(cloned);animations.forEach(c=>m.clipAction(c).play());animMixers.push(m);return()=>{const i=animMixers.indexOf(m);if(i>=0)animMixers.splice(i,1);};}},[cloned,animations]);return<primitive object={wrapped}/>;}
function FBXModel({src}:{src:string}){const[scene,setScene]=useState<THREE.Group|null>(null);const[anims,setAnims]=useState<THREE.AnimationClip[]>([]);useEffect(()=>{let c=false;const loader=new FBXLoader();loader.load(src,(fbx:THREE.Group)=>{if(c)return;fbx.traverse(standardize);setScene(fbx);const a=(fbx as any).animations||(loader as any).animations||[];setAnims(a);},undefined,()=>setScene(new THREE.Group()));return()=>{c=true;};},[src]);useEffect(()=>{if(scene&&anims.length>0){const m=new THREE.AnimationMixer(scene);anims.forEach(c=>m.clipAction(c).play());animMixers.push(m);return()=>{const i=animMixers.indexOf(m);if(i>=0)animMixers.splice(i,1);};}},[scene,anims]);return scene?<primitive object={scene}/>:null;}
const SCALE_FACTOR=0.12;
function RotationGizmo({center,onRotate}:{center:Vec3;onRotate:(axis:0|1|2,dx:number,dy:number)=>void}){const{gl,camera}=useThree();const gRef=useRef<THREE.Group>(null);const drag=useRef<{axis:0|1|2;lastX:number;lastY:number}|null>(null);useFrame(()=>{if(!gRef.current)return;const d=camera.position.distanceTo(new THREE.Vector3(...center));gRef.current.scale.setScalar(d*SCALE_FACTOR);});const onDown=useCallback((axis:0|1|2)=>(e:any)=>{e.stopPropagation();if(drag.current)return;window.dispatchEvent(new CustomEvent('gizmo-drag-start'));drag.current={axis,lastX:e.clientX,lastY:e.clientY};(gl.domElement as any).style.cursor='grabbing';},[gl.domElement]);useEffect(()=>{const mv=(e:PointerEvent)=>{if(!drag.current)return;const dx=e.clientX-drag.current.lastX,dy=e.clientY-drag.current.lastY;drag.current.lastX=e.clientX;drag.current.lastY=e.clientY;onRotate(drag.current.axis,dx,dy);};const up=()=>{if(!drag.current)return;(gl.domElement as any).style.cursor='';window.dispatchEvent(new CustomEvent('gizmo-drag-end'));drag.current=null;};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);};},[onRotate,gl.domElement]);const W=0.05;return(<group ref={gRef} position={center as[number,number,number]}><group onPointerDown={onDown(2)}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#4488ff" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group><group onPointerDown={onDown(1)} rotation={[Math.PI/2,0,0]}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#ddbb00" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group><group onPointerDown={onDown(0)} rotation={[0,-Math.PI/2,0]}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group></group>);}
function CameraGLB({pos,tgt}:{pos:Vec3;tgt:Vec3}){const{scene}=useGLTF('/models/camera.glb');const cloned=useMemo(()=>{const c=scene.clone(true);c.traverse((ch:any)=>{if(ch.isMesh){ch.castShadow=true;if(ch.material){ch.material.roughness=0.5;ch.material.metalness=0;ch.material.emissive=ch.material.emissive||new THREE.Color('#444');ch.material.emissiveIntensity=0.3;}}});return c;},[scene]);return<primitive object={cloned} position={pos} lookAt={tgt} scale={0.5}/>;}
function FallbackCamera({pos,tgt}:{pos:Vec3;tgt:Vec3}){return<group position={pos as[number,number,number]}><mesh lookAt={tgt}><boxGeometry args={[0.45,0.28,0.4]}/><meshStandardMaterial color="#3a3a44" roughness={0.5}/></mesh><mesh lookAt={tgt} position={[0,-0.04,0.22]}><boxGeometry args={[0.38,0.16,0.2]}/><meshStandardMaterial color="#f44" emissive="#f22" emissiveIntensity={0.6}/></mesh><mesh lookAt={tgt} position={[0,0,0.28]}><cylinderGeometry args={[0.09,0.07,0.16,12]}/><meshStandardMaterial color="#555" roughness={0.3}/></mesh></group>;}
class ErrorBoundary extends React.Component<{fallback:React.ReactNode;children:React.ReactNode},{err:boolean}>{constructor(p:any){super(p);this.state={err:false};}static getDerivedStateFromError(){return{err:true};}render(){return this.state.err?this.props.fallback:this.props.children;}}
const SENSOR_H=18.17;
const LENSES:Record<string,{name:string;fov:number;maxAperture:number;minAperture:number;blades:number}>={
'24':{name:'24mm',fov:2*Math.atan(SENSOR_H/(2*24))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'35':{name:'35mm',fov:2*Math.atan(SENSOR_H/(2*35))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'50':{name:'50mm',fov:2*Math.atan(SENSOR_H/(2*50))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'85':{name:'85mm',fov:2*Math.atan(SENSOR_H/(2*85))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'135':{name:'135mm',fov:2*Math.atan(SENSOR_H/(2*135))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
};

const mover=(el:THREE.Object3D,obj:SceneObject)=>{const p:Vec3=[el.position.x,el.position.y,el.position.z];const r:Vec3=[el.rotation.x,el.rotation.y,el.rotation.z];const s:Vec3=[el.scale.x,el.scale.y,el.scale.z];const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);window.dispatchEvent(new CustomEvent('scene3d-object-moved',{detail:{id:obj.id,position:p,rotation:r,scale:s,forward:[fwd.x,fwd.y,fwd.z]as Vec3,objRef:el}}));};
function CheckerGround(){const tex=useMemo(()=>{const c=document.createElement('canvas');c.width=4;c.height=4;const ctx=c.getContext('2d')!;for(let x=0;x<4;x++){for(let y=0;y<4;y++){ctx.fillStyle=(x+y)%2===0?'#808080':'#ffffff';ctx.fillRect(x,y,1,1);}}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.colorSpace=THREE.SRGBColorSpace;return t;},[]);const{scene}=useThree();useEffect(()=>{scene.fog=new THREE.Fog('#3a3a3a',10,35);return()=>{scene.fog=null;};},[scene]);return<mesh rotation={[-Math.PI/2,0,0]} position={[0,-0.02,0]}><planeGeometry args={[100,100]}/><meshStandardMaterial map={tex} roughness={1} metalness={0}/></mesh>;}
function ProcSky({sunAzimuth,sunElevation}:{sunAzimuth:number;sunElevation:number}){const{scene}=useThree();useEffect(()=>{const s=new Sky();s.scale.setScalar(80);const phi=THREE.MathUtils.degToRad(90-sunElevation);const theta=THREE.MathUtils.degToRad(sunAzimuth);const sunPos=new THREE.Vector3().setFromSphericalCoords(1,phi,theta);const uni=s.material.uniforms;uni.turbidity.value=5;uni.rayleigh.value=0.35;uni.mieCoefficient.value=0.0005;uni.mieDirectionalG.value=0.98;uni.sunPosition.value.copy(sunPos);scene.add(s);return()=>{scene.remove(s);s.material.dispose();};},[scene,sunAzimuth,sunElevation]);return null;}
function AnimationSync({time,active}:{time:number;active:boolean}){useEffect(()=>{animTime=time;animPlaying=active;},[time,active]);useFrame((_,delta)=>{animMixers.forEach(m=>m.update(delta));});return null;}
function CloudLayer(){const tex=useMemo(()=>{const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d')!;const img=ctx.createImageData(512,256);for(let y=0;y<256;y++){for(let x=0;x<512;x++){const nx=x/512;const ny=y/256;let v=Math.sin(nx*12+Math.sin(ny*8)*3)*0.5+0.5;v+=Math.sin(ny*9+nx*2)*0.3;v+=Math.sin(nx*5+ny*7)*0.2;v+=Math.sin(nx*20+ny*15)*0.15;v=Math.max(0,(v-0.55)*2.5);if(x<30)v*=x/30;else if(x>482)v*=(512-x)/30;const i=(y*512+x)*4;img.data[i]=255;img.data[i+1]=255;img.data[i+2]=255;img.data[i+3]=Math.min(255,v*255);}}ctx.putImageData(img,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t;},[]);const ref=useRef<THREE.Mesh>(null);useFrame((_,delta)=>{if(ref.current)ref.current.rotation.y+=delta*0.002;});return<mesh ref={ref}><sphereGeometry args={[47,48,24]}/><meshBasicMaterial map={tex} transparent opacity={0.55} side={THREE.BackSide} depthWrite={false} fog={false}/></mesh>;}
function SunLight({azimuth,elevation}:{azimuth:number;elevation:number}){const radAz=(azimuth*Math.PI)/180;const radEl=(elevation*Math.PI)/180;const dist=20;const x=dist*Math.cos(radEl)*Math.sin(radAz);const y=dist*Math.sin(radEl);const z=dist*Math.cos(radEl)*Math.cos(radAz);return<directionalLight position={[x,y,z]} intensity={3.0} color="#ffe8d0"/>;}
function SceneContent({objects,selectedId,onSelect,gizmoMode,rigActive,snapToTrack,sunAzimuth,sunElevation}:{objects:SceneObject[];selectedId:string|null;onSelect:(id:string|null)=>void;gizmoMode:GizmoMode;rigActive?:boolean;snapToTrack?:((p:THREE.Vector3)=>THREE.Vector3|null);sunAzimuth?:number;sunElevation?:number;}){
  const meshRefs=useRef<Map<string,THREE.Object3D>>(new Map());const orbitRef=useRef<any>(null);useEffect(()=>{const s=()=>{if(orbitRef.current)orbitRef.current.enabled=false;};const e=()=>{if(orbitRef.current)orbitRef.current.enabled=true;};window.addEventListener('gizmo-drag-start',s);window.addEventListener('gizmo-drag-end',e);return()=>{window.removeEventListener('gizmo-drag-start',s);window.removeEventListener('gizmo-drag-end',e);};},[]);
  return(<><CheckerGround/><ProcSky sunAzimuth={sunAzimuth||45} sunElevation={sunElevation||40}/><CloudLayer/><ambientLight intensity={0.8} color="#ffffff"/><SunLight azimuth={sunAzimuth||45} elevation={sunElevation||40}/><Grid position={[0,-0.01,0]} args={[100,100]} cellSize={1} cellThickness={0.5} cellColor="#aaaaaa" sectionSize={5} sectionThickness={1.5} sectionColor="#cccccc" fadeDistance={25} infiniteGrid/>
    <mesh onClick={()=>onSelect(null)} position={[0,-0.02,0]} rotation={[-Math.PI/2,0,0]} visible={false}><planeGeometry args={[100,100]}/></mesh>
    {objects.map(obj=>{const sel=selectedId===obj.id;const bottomY=obj.type==='figure'||obj.type==='plane'?0:0.5;return(<group key={obj.id}>
      <group position={obj.position} rotation={obj.rotation} scale={obj.scale} ref={el=>{if(el){meshRefs.current.set(obj.id,el);if(obj.type==='camera'){const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);window.dispatchEvent(new CustomEvent('cam-ready',{detail:{objRef:el,forward:[fwd.x,fwd.y,fwd.z]as Vec3}}));}}}} onClick={e=>{e.stopPropagation();onSelect(obj.id);}}>
        {obj.type==='figure'?<SafeModel poseId={obj.figurePose||''} figureSrc={obj.figureSrc} fallback={<StickFigure poseId={obj.figurePose||'stand'} color={obj.color||'#c0c8d0'}/>}/>:
        obj.type==='camera'?<><mesh rotation={[-Math.PI/2,0,0]} position={[0,0.2,-0.6]}><cylinderGeometry args={[0.01,0.01,1,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6}/></mesh><mesh position={[0,0,-3]}><sphereGeometry args={[0.08,8,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.5}/></mesh><ErrorBoundary fallback={<FallbackCamera pos={[0,0,0]} tgt={[0,0,-3]}/>}><Suspense fallback={null}><CameraGLB pos={[0,0,0]} tgt={[0,0,-3]}/></Suspense></ErrorBoundary></>:
        <mesh>{obj.type==='box'&&<boxGeometry/>}{obj.type==='sphere'&&<sphereGeometry args={[0.5,28,28]}/>}{obj.type==='cylinder'&&<cylinderGeometry args={[0.5,0.5,1,24]}/>}{obj.type==='plane'&&<planeGeometry/>}<meshStandardMaterial color={obj.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>}
      </group>
      {sel&&<lineSegments position={obj.position} rotation={obj.rotation}><edgesGeometry args={[new THREE.BoxGeometry(0.6,0.6,0.6)]}/><lineBasicMaterial color="#60a0ff" opacity={0.8} transparent/></lineSegments>}
      {sel&&<mesh position={[obj.position[0],obj.position[1]-bottomY,obj.position[2]]}><sphereGeometry args={[0.2,12,12]}/><meshBasicMaterial color="#60a0ff" transparent opacity={0.7}/></mesh>}
      {sel&&gizmoMode==='rotate'&&<RotationGizmo center={[obj.position[0],obj.position[1]-bottomY,obj.position[2]]as Vec3} onRotate={(axis,dx,dy)=>{const el=meshRefs.current.get(obj.id);if(el){el.rotation[('xyz'[axis])as'x'|'y'|'z']+=(axis===0?dy*0.008:axis===1?dx*0.008:-dx*0.008);mover(el,obj);}}}/>}
      {sel&&gizmoMode==='translate'&&<TransformControls object={meshRefs.current.get(obj.id)||undefined} mode="translate" size={0.65} onObjectChange={()=>{const el=meshRefs.current.get(obj.id);if(el){const minY=obj.type==='figure'||obj.type==='plane'?0:0.5;if(el.position.y<minY)el.position.y=minY;if(rigActive&&obj.type==='camera'&&snapToTrack){const wp=new THREE.Vector3();el.getWorldPosition(wp);const s=snapToTrack(wp);if(s){el.position.copy(s);window.dispatchEvent(new CustomEvent('cam-track-snap',{detail:{worldPos:[s.x,s.y,s.z]}}));}}window.dispatchEvent(new CustomEvent('gizmo-drag-start'));mover(el,obj);}}} onMouseUp={()=>{window.dispatchEvent(new CustomEvent('gizmo-drag-end'));}}/>}
      {sel&&gizmoMode==='scale'&&<TransformControls object={meshRefs.current.get(obj.id)||undefined} mode="scale" size={0.65} onObjectChange={()=>{const el=meshRefs.current.get(obj.id);if(el){window.dispatchEvent(new CustomEvent('gizmo-drag-start'));mover(el,obj);}}} onMouseUp={()=>{window.dispatchEvent(new CustomEvent('gizmo-drag-end'));}}/>}
    </group>);})}
    <OrbitControls ref={orbitRef} makeDefault enableDamping dampingFactor={0.08} minDistance={2} maxDistance={25} maxPolarAngle={Math.PI/2+0.2} target={[0,1,0]}/>
  </>);
}

function EBtn({label,active,onClick}:{label:string;active?:boolean;onClick:()=>void}){return<button onClick={onClick} style={{padding:'6px 10px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',border:active?'1px solid rgba(255,255,255,0.25)':'1px solid rgba(255,255,255,0.08)',background:active?'rgba(255,255,255,0.12)':'transparent',color:active?'#fff':'rgba(255,255,255,0.5)',whiteSpace:'nowrap',transition:'all 0.12s ease'}} onMouseEnter={e=>{e.currentTarget.style.background='rgba(255,255,255,0.1)';e.currentTarget.style.color='#fff';}} onMouseLeave={e=>{e.currentTarget.style.background=active?'rgba(255,255,255,0.12)':'transparent';e.currentTarget.style.color=active?'#fff':'rgba(255,255,255,0.5)';}}>{label}</button>;}

function PiPCam({camRef}:{camRef:React.MutableRefObject<THREE.Object3D|null>}){const{camera}=useThree();useFrame(()=>{const el=camRef.current;if(!el)return;camera.position.copy(el.position);const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);camera.lookAt(fwd);});return null;}


function DollyRails({rig,selCp,onSelCp,onMoveCp}:{rig:CameraRig;selCp:string|null;onSelCp:(id:string|null)=>void;onMoveCp:(id:string,pos:Vec3)=>void}){if(!rig.dolly)return null;const{pointA,pointB}=rig.dolly;const dir=new THREE.Vector3(pointB[0]-pointA[0],pointB[1]-pointA[1],pointB[2]-pointA[2]);const len=dir.length();dir.normalize();const mid:Vec3=[(pointA[0]+pointB[0])/2,(pointA[1]+pointB[1])/2,(pointA[2]+pointB[2])/2];const aRef=useRef<THREE.Mesh>(null);const bRef=useRef<THREE.Mesh>(null);return<group><mesh position={[mid[0],mid[1]+0.05,mid[2]]} quaternion={new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),dir)}><cylinderGeometry args={[0.08,0.08,len,8]}/><meshStandardMaterial color="#aaa" roughness={0.5} metalness={0.8}/></mesh><mesh ref={aRef} position={pointA} onClick={e=>{e.stopPropagation();onSelCp('A');}}><sphereGeometry args={[0.2,12,12]}/><meshStandardMaterial color={selCp==='A'?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp==='A'&&aRef.current&&<TransformControls object={aRef.current} mode="translate" size={0.5} onObjectChange={()=>{const p=aRef.current?.position;if(p)onMoveCp('A',[p.x,p.y,p.z]);}}/>}<mesh ref={bRef} position={pointB} onClick={e=>{e.stopPropagation();onSelCp('B');}}><sphereGeometry args={[0.2,12,12]}/><meshStandardMaterial color={selCp==='B'?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp==='B'&&bRef.current&&<TransformControls object={bRef.current} mode="translate" size={0.5} onObjectChange={()=>{const p=bRef.current?.position;if(p)onMoveCp('B',[p.x,p.y,p.z]);}}/>}</group>;}

function CurvedTrackRails({rig,selCp,onSelCp,onMoveCp}:{rig:CameraRig;selCp:string|null;onSelCp:(id:string|null)=>void;onMoveCp:(id:string,pos:Vec3)=>void}){if(!rig.curved||rig.curved.controlPoints.length<2)return null;const pts=rig.curved.controlPoints.map(p=>new THREE.Vector3(...p.position));const curve=new THREE.CatmullRomCurve3(pts);const tubeGeom=new THREE.TubeGeometry(curve,64,0.06,8,false);const cpRefs=useRef<Map<string,THREE.Mesh>>(new Map());return<group><mesh><primitive object={tubeGeom} attach="geometry"/><meshStandardMaterial color="#888" roughness={0.5} metalness={0.7}/></mesh>{rig.curved.controlPoints.map((cp,i)=>{const mesh=cpRefs.current.get(cp.id);return<group key={cp.id}><mesh ref={el=>{if(el)cpRefs.current.set(cp.id,el as any);}} position={cp.position} onClick={e=>{e.stopPropagation();onSelCp(cp.id);}}><sphereGeometry args={[0.18,12,12]}/><meshStandardMaterial color={selCp===cp.id?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp===cp.id&&mesh&&<TransformControls object={mesh} mode="translate" size={0.5} onObjectChange={()=>{const p=mesh?.position;if(p)onMoveCp(cp.id,[p.x,p.y,p.z]);}}/>}</group>;})}</group>;}

function OrbitRing({rig}:{rig:CameraRig}){if(!rig.orbit)return null;const{center,radius,height,startAngle,endAngle}=rig.orbit;const steps=64;const pts:THREE.Vector3[]=[];for(let i=0;i<=steps;i++){const a=startAngle+(endAngle-startAngle)*i/steps;pts.push(new THREE.Vector3(center[0]+Math.cos(a)*radius,center[1]+height,center[2]+Math.sin(a)*radius));}const curve=new THREE.CatmullRomCurve3(pts);const tubeGeom=new THREE.TubeGeometry(curve,64,0.05,8,false);return<group><mesh><primitive object={tubeGeom} attach="geometry"/><meshStandardMaterial color="#888" roughness={0.5} metalness={0.7}/></mesh></group>;}

function FullscreenEditor({objects,selectedId,setObjects,setSelectedId,onSnapshot,onClose,nodeId,rig,setRig}:{objects:SceneObject[];selectedId:string|null;setObjects:React.Dispatch<React.SetStateAction<SceneObject[]>>;setSelectedId:React.Dispatch<React.SetStateAction<string|null>>;onSnapshot:()=>void;onClose:()=>void;nodeId:string;rig:CameraRig|null;setRig:React.Dispatch<React.SetStateAction<CameraRig|null>>;}){
  const counter=useRef(objects.length);const[gizmoMode,setGizmoMode]=useState<GizmoMode>('translate');
  const undoStack=useRef<SceneObject[][]>([]);const redoStack=useRef<SceneObject[][]>([]);const dragSaved=useRef(false);
  const[showCam,setShowCam]=useState(false);const[vcamLens,setVcamLens]=useState('50');const[vcamAperture,setVcamAperture]=useState(2.8);
  const activeCamRef=useRef<THREE.Object3D|null>(null);const pipCanvasRef=useRef<HTMLDivElement>(null);  const lensData=LENSES[vcamLens];
  const[playing,setPlaying]=useState(false);const[playTime,setPlayTime]=useState(0);
  const playStartRef=useRef(0);const playFromRef=useRef(0);
  const animCamPos=useRef(new THREE.Vector3());
  const animCamLook=useRef(new THREE.Vector3(0,1,0));
  const camObjIdRef=useRef<string|null>(null);
  const[trackCpId,setTrackCpId]=useState<string|null>(null);
  const[timelineH,setTimelineH]=useState(80);
  const[sunAzimuth,setSunAzimuth]=useState(45);const[sunElevation,setSunElevation]=useState(40);
  const[zoom,setZoom]=useState(60);
  const rigRef=useRef(rig);rigRef.current=rig;
  const snapToTrack=useCallback((pos:THREE.Vector3):THREE.Vector3|null=>{
    const r=rigRef.current;if(!r)return null;
    if(r.type==='dolly'&&r.dolly){const A=new THREE.Vector3(...r.dolly.pointA);const B=new THREE.Vector3(...r.dolly.pointB);const dir=B.clone().sub(A);const len=dir.length();if(len<0.001)return A.clone().add(new THREE.Vector3(0,0.13,0));dir.normalize();const t=Math.max(0,Math.min(1,pos.clone().sub(A).dot(dir)/len));const pt=A.clone().add(dir.clone().multiplyScalar(t*len));pt.y+=0.13;return pt;}
    if(r.type==='curved'&&r.curved&&r.curved.controlPoints.length>=2){const pts=r.curved.controlPoints.map(p=>new THREE.Vector3(...p.position));const curve=new THREE.CatmullRomCurve3(pts);let best=Infinity;const r2=new THREE.Vector3();for(let i=0;i<=100;i++){const pt=curve.getPointAt(i/100);const d=pos.distanceToSquared(pt);if(d<best){best=d;r2.copy(pt);}}r2.y+=0.13;return r2;}
    if(r.type==='orbit'&&r.orbit){const{center,radius,height}=r.orbit;const c=new THREE.Vector3(...center);const dx=pos.x-c.x;const dz=pos.z-c.z;const a=Math.atan2(dz,dx);return new THREE.Vector3(c.x+Math.cos(a)*radius,c.y+height+0.13,c.z+Math.sin(a)*radius);}
    return null;
  },[]);
  const getTrackCamera=useCallback((prog:number):any=>{
    const r=rigRef.current;if(!r)return null;
    const sc=r.speedCurve.sort((a,b)=>a.time-b.time);
    let sp=1;const targetTime=prog*r.duration;
    if(sc.length>=2){let i0=0;for(let i=1;i<sc.length;i++){if(sc[i].time<=targetTime)i0=i;else break;}let i1=Math.min(i0+1,sc.length-1);const st=sc[i1].time>sc[i0].time?(targetTime-sc[i0].time)/(sc[i1].time-sc[i0].time):0;sp=sc[i0].speed+(sc[i1].speed-sc[i0].speed)*st;}
    else if(sc.length===1)sp=sc[0].speed;
    const pp=Math.max(0,Math.min(1,prog*sp));
    let pitch:number|undefined,yaw:number|undefined;const rk=r.rotationKeys.sort((a,b)=>a.time-b.time);
    if(rk.length>=2){const tt=pp*r.duration;let i0=0;for(let i=1;i<rk.length;i++){if(rk[i].time<=tt)i0=i;else break;}let i1=Math.min(i0+1,rk.length-1);const st=rk[i1].time>rk[i0].time?(tt-rk[i0].time)/(rk[i1].time-rk[i0].time):0;pitch=rk[i0].pitch+(rk[i1].pitch-rk[i0].pitch)*st;yaw=rk[i0].yaw+(rk[i1].yaw-rk[i0].yaw)*st;}
    else if(rk.length===1){pitch=rk[0].pitch;yaw=rk[0].yaw;}
    if(r.type==='dolly'&&r.dolly){const A=new THREE.Vector3(...r.dolly.pointA);const B=new THREE.Vector3(...r.dolly.pointB);const pos=A.clone().lerp(B,pp);pos.y+=0.13;return{pos,look:pos.clone().add(new THREE.Vector3(0,0,-1)),pitch,yaw};}
    if(r.type==='curved'&&r.curved&&r.curved.controlPoints.length>=2){const pts=r.curved.controlPoints.map(p=>new THREE.Vector3(...p.position));const curve=new THREE.CatmullRomCurve3(pts);const pos=curve.getPointAt(pp);const tgt=curve.getTangentAt(pp);return{pos,look:pos.clone().add(tgt),pitch,yaw};}
    if(r.type==='orbit'&&r.orbit){const{center,radius,height,startAngle,endAngle}=r.orbit;const angle=startAngle+(endAngle-startAngle)*pp;const pos=new THREE.Vector3(center[0]+Math.cos(angle)*radius,center[1]+height,center[2]+Math.sin(angle)*radius);return{pos,look:new THREE.Vector3(...center),pitch,yaw};}
    return null;
  },[]);
  const playTimeRef=useRef(0);
  useEffect(()=>{playTimeRef.current=playTime;},[playTime]);
  useEffect(()=>{if(!playing||!rig)return;const camObj=objects.find(o=>o.type==='camera');camObjIdRef.current=camObj?.id||null;const startTime=performance.now();const startPlay=playTimeRef.current;let raf;const loop=(now)=>{const elapsed=(now-startTime)/1000;let p=(startPlay+elapsed)/rig.duration;if(p>=1){p=1;setPlaying(false);setPlayTime(rig.duration);}else{setPlayTime(p*rig.duration);}const cam=getTrackCamera(p);if(cam){animCamPos.current.copy(cam.pos);animCamLook.current.copy(cam.look);if(camObjIdRef.current&&activeCamRef.current){activeCamRef.current.position.copy(cam.pos);if(cam.pitch!==undefined)activeCamRef.current.rotation.set(cam.pitch,cam.yaw,0);const cid=camObjIdRef.current;const rot=cam.pitch!==undefined?([cam.pitch,cam.yaw,0]as Vec3):undefined;setObjects(prev=>prev.map(o=>o.id===cid?{...o,position:[cam.pos.x,cam.pos.y,cam.pos.z]as Vec3,rotation:rot||o.rotation}:o));}}if(p<1)raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf);},[playing,rig,getTrackCamera,setObjects]);
  useEffect(()=>{if(playing||!rig)return;const r=rigRef.current;if(!r)return;const p=playTime/Math.max(0.1,r.duration);const cam=getTrackCamera(Math.min(1,p));if(cam){animCamPos.current.copy(cam.pos);animCamLook.current.copy(cam.look);if(activeCamRef.current)activeCamRef.current.position.copy(cam.pos);}},[playTime,playing,getTrackCamera]);

  const pushUndo=useCallback((snap:SceneObject[])=>{undoStack.current.push(snap);if(undoStack.current.length>50)undoStack.current.shift();redoStack.current=[];},[]);
  const doUndo=useCallback(()=>{const prev=undoStack.current.pop();if(!prev)return;redoStack.current.push(objects);setObjects(prev);},[objects]);
  const doRedo=useCallback(()=>{const next=redoStack.current.pop();if(!next)return;undoStack.current.push(objects);setObjects(next);},[objects]);
  useEffect(()=>{const h=()=>{if(!dragSaved.current){pushUndo(objects);dragSaved.current=true;}};window.addEventListener('gizmo-drag-start',h);return()=>window.removeEventListener('gizmo-drag-start',h);},[objects,pushUndo]);
  useEffect(()=>{const h=()=>{dragSaved.current=false;};window.addEventListener('gizmo-drag-end',h);return()=>window.removeEventListener('gizmo-drag-end',h);},[]);
  useEffect(()=>{initPoseRegistry();},[]);
  useEffect(()=>{const h=(e:Event)=>{const{id,position,rotation,scale,objRef}=(e as CustomEvent).detail as{id:string;position:Vec3;rotation?:Vec3;scale?:Vec3;objRef?:THREE.Object3D};const obj=objects.find(o=>o.id===id);const minY=obj&&(obj.type==='figure'||obj.type==='plane')?0:0.5;const clampedPos:Vec3=position[1]<minY?[position[0],minY,position[2]]:position;if(objRef&&position[1]<minY)objRef.position.y=minY;setObjects(prev=>prev.map(o=>o.id===id?{...o,position:clampedPos,rotation:rotation||o.rotation,scale:scale||o.scale}:o));if(objRef&&(objRef as any).type==='camera'){activeCamRef.current=objRef;if(rig&&!playing){const wp=new THREE.Vector3();objRef.getWorldPosition(wp);const dur=rig.duration;let bestT=0,bestD=Infinity;for(let i=0;i<=100;i++){const t=i/100;const c=getTrackCamera(t);if(c){const d=wp.distanceToSquared(c.pos);if(d<bestD){bestD=d;bestT=t;}}}setPlayTime(bestT*dur);}}};window.addEventListener('scene3d-object-moved',h);return()=>window.removeEventListener('scene3d-object-moved',h);},[setObjects,rig,playing,getTrackCamera,objects]);
  useEffect(()=>{const h=(e:Event)=>{const{objRef}=(e as CustomEvent).detail as{objRef:THREE.Object3D};if(objRef)activeCamRef.current=objRef;};window.addEventListener('cam-ready',h);return()=>window.removeEventListener('cam-ready',h);},[]);
  useEffect(()=>{const h=(e:Event)=>{const wp=(e as CustomEvent).detail.worldPos as number[];if(!rig||playing)return;const dur=rig.duration;let bt=0,bd=Infinity;for(let i=0;i<=100;i++){const t=i/100;const c=getTrackCamera(t);if(c){const d=Math.pow(wp[0]-c.pos.x,2)+Math.pow(wp[1]-c.pos.y,2)+Math.pow(wp[2]-c.pos.z,2);if(d<bd){bd=d;bt=t;}}}setPlayTime(bt*dur);};window.addEventListener('cam-track-snap',h);return()=>window.removeEventListener('cam-track-snap',h);},[rig,playing,getTrackCamera]);

  const addObj=useCallback((type:SceneObject['type'])=>{counter.current++;const y=type==='figure'||type==='plane'?0:0.5;const first=poseRegistry.size>0?poseRegistry.keys().next().value as string:'stand1';const obj:SceneObject={id:`o_${counter.current}`,type,position:[0,y,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:type==='figure'?first:undefined,figureSrc:type==='figure'?poseRegistry.get(first)?.src:undefined};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);},[setObjects,setSelectedId,objects,pushUndo]);
    const makeRig=(type:TrackType)=>{const cam=objects.find(o=>o.type==='camera');if(!cam)return;const py=cam.position[1],px=cam.position[0],pz=cam.position[2];if(type==='dolly')setRig({type:'dolly',duration:8,speedCurve:[{time:0,speed:1},{time:8,speed:1}],rotationKeys:[],dolly:{pointA:[px+4,py,pz],pointB:[px-4,py,pz]}});if(type==='curved')setRig({type:'curved',duration:8,speedCurve:[{time:0,speed:1},{time:8,speed:1}],rotationKeys:[],curved:{controlPoints:[{id:'c0',position:[px+4,py,pz]},{id:'c1',position:[px,py,pz+3]},{id:'c2',position:[px-4,py,pz]}]}});if(type==='orbit')setRig({type:'orbit',duration:8,speedCurve:[{time:0,speed:1},{time:8,speed:1}],rotationKeys:[],orbit:{center:[px,py,pz-3],radius:4,height:0,startAngle:0,endAngle:Math.PI*2}});setTimeout(()=>{const start=getTrackCamera(0);if(start&&cam&&activeCamRef.current){activeCamRef.current.position.copy(start.pos);setObjects(prev=>prev.map(o=>o.id===cam.id?{...o,position:[start.pos.x,start.pos.y,start.pos.z]as Vec3}:o));}},50);setSelectedId(cam.id);};
  const addCamera=useCallback(()=>{counter.current++;const obj:SceneObject={id:`o_${counter.current}`,type:'camera',position:[8,2,5],rotation:[0,0,0],scale:[1,1,1]};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);},[setObjects,setSelectedId,objects,pushUndo]);
  const updatePose=useCallback((pose:string)=>{const e=poseRegistry.get(pose);setObjects(prev=>prev.map(o=>o.id===selectedId&&o.type==='figure'?{...o,figurePose:pose,figureSrc:e?.src}:o));},[selectedId,setObjects]);
  const selObj=objects.find(o=>o.id===selectedId);

  const onKey=(e:React.KeyboardEvent)=>{if(e.ctrlKey&&e.key==='z'){e.preventDefault();doUndo();return;}if(e.ctrlKey&&(e.key==='y'||(e.shiftKey&&e.key==='z'))){e.preventDefault();doRedo();return;}if(e.key==='Escape'){if(selectedId)setSelectedId(null);else onClose();}if((e.key==='Delete'||e.key==='Backspace')&&selectedId){e.preventDefault();e.stopPropagation();pushUndo(objects);setObjects(prev=>prev.filter(o=>o.id!==selectedId));setSelectedId(null);}};

  return createPortal(<div onKeyDown={onKey} tabIndex={-1} ref={el=>el?.focus()} style={{position:'fixed',inset:0,zIndex:99999,outline:'none',background:'#3a3a3a',display:'flex',flexDirection:'column',animation:'tap-fade-in 0.15s ease'}}>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'8px 14px',background:'rgba(0,0,0,0.3)',flexShrink:0}}><span style={{fontSize:14,fontWeight:600,color:'#ccc'}}>3D 场景编辑器</span><div style={{display:'flex',gap:8}}><EBtn label="截图" onClick={onSnapshot}/><button onClick={onClose} style={{padding:'6px 16px',background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:8,color:'#ccc',cursor:'pointer',fontSize:13}}>退出</button></div></div>
    <div style={{flex:1,display:'flex',minHeight:0}}>
      <div style={{width:90,display:'flex',flexDirection:'column',gap:5,padding:'10px 7px',borderRight:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0,alignItems:'center',background:'rgba(0,0,0,0.2)'}}>
        <div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>几何体</div><EBtn label="立方体" onClick={()=>addObj('box')}/><EBtn label="球体" onClick={()=>addObj('sphere')}/><EBtn label="圆柱" onClick={()=>addObj('cylinder')}/><EBtn label="平面" onClick={()=>addObj('plane')}/>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>人物</div><EBtn label="添加人物" onClick={()=>addObj('figure')}/>
        {selObj?.type==='figure'&&<select value={selObj.figurePose||''} onChange={e=>updatePose(e.target.value)} style={{marginTop:4,width:'100%',padding:5,background:'rgba(0,0,0,0.15)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:8,color:'#ccc',fontSize:10,cursor:'pointer'}}>{[...poseRegistry.entries()].map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select>}
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>摄像</div><EBtn label="加摄像机" onClick={addCamera}/><EBtn label={showCam?'关取景器':'开取景器'} onClick={()=>setShowCam(!showCam)} active={showCam}/>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>光照</div><div style={{display:'flex',alignItems:'center',gap:3,marginBottom:2}}><span style={{fontSize:8,color:'rgba(255,255,255,0.35)',width:28}}>方位</span><input type="range" min={0} max={360} value={sunAzimuth} onChange={e=>setSunAzimuth(Number(e.target.value))} style={{flex:1,height:3,cursor:'pointer'}}/><span style={{fontSize:8,color:'rgba(255,255,255,0.5)',width:24}}>{sunAzimuth}°</span></div><div style={{display:'flex',alignItems:'center',gap:3,marginBottom:2}}><span style={{fontSize:8,color:'rgba(255,255,255,0.35)',width:28}}>仰角</span><input type="range" min={0} max={90} value={sunElevation} onChange={e=>setSunElevation(Number(e.target.value))} style={{flex:1,height:3,cursor:'pointer'}}/><span style={{fontSize:8,color:'rgba(255,255,255,0.5)',width:24}}>{sunElevation}°</span></div>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>轨道</div><EBtn label='直线推轨' active={rig?.type==='dolly'} onClick={()=>makeRig('dolly')}/><EBtn label='曲线轨道' active={rig?.type==='curved'} onClick={()=>makeRig('curved')}/><EBtn label='环绕轨道' active={rig?.type==='orbit'} onClick={()=>makeRig('orbit')}/>{rig&&(rig.type==='curved'||rig.type==='orbit')&&<EBtn label='+控制点' onClick={()=>{setRig(prev=>{if(!prev)return prev;const getCPs=()=>{if(prev.type==='curved'&&prev.curved)return prev.curved.controlPoints;if(prev.type==='orbit'&&prev.orbit){const{center,radius,height,startAngle,endAngle}=prev.orbit;const angle=startAngle+(endAngle-startAngle)*0.5;return[{id:'cp_'+Date.now(),position:[center[0]+Math.cos(angle)*radius,center[1]+height,center[2]+Math.sin(angle)*radius]as Vec3}];}return[];};const cps=getCPs();if(prev.type==='curved'&&prev.curved&&prev.curved.controlPoints.length>=2){const last=prev.curved.controlPoints[prev.curved.controlPoints.length-1];const mid:Vec3=[(last.position[0]+prev.curved.controlPoints[0].position[0])/2,last.position[1],(last.position[2]+prev.curved.controlPoints[0].position[2])/2];const newCp={id:'cp_'+Date.now(),position:mid};return{...prev,curved:{...prev.curved,controlPoints:[...prev.curved.controlPoints.slice(0,-1),newCp,last]}};}return prev;});}}/>}{rig&&<EBtn label='清除轨道' onClick={()=>setRig(null)}/>}
      </div>
      <div style={{flex:1,minWidth:0,position:'relative'}} onDragOver={e=>{e.preventDefault();e.stopPropagation();}} onDrop={e=>{e.preventDefault();e.stopPropagation();const f=e.dataTransfer.files[0];if(!f||!f.name.match(/\.(glb|fbx)$/i))return;importFile(f,(entry,poseId)=>{counter.current++;const obj:SceneObject={id:`o_${counter.current}`,type:'figure',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:poseId,figureSrc:entry.src};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);});}}>
        <Canvas shadows camera={{position:[5,4,7],fov:50,near:0.1,far:100}} gl={{preserveDrawingBuffer:true,antialias:false,powerPreference:'high-performance'}} dpr={[0.5,1.5]} style={{width:'100%',height:'100%'}}><Suspense fallback={null}><AnimationSync time={playTime} active={playing}/><SceneContent objects={objects} selectedId={selectedId} onSelect={setSelectedId} gizmoMode={gizmoMode} rigActive={!!rig} snapToTrack={snapToTrack} sunAzimuth={sunAzimuth} sunElevation={sunElevation}/>{rig?.type==='dolly'&&<DollyRails rig={rig} selCp={trackCpId} onSelCp={setTrackCpId} onMoveCp={(id,pos)=>{setRig(prev=>prev&&prev.dolly?{...prev,dolly:{...prev.dolly,pointA:id==='A'?pos:prev.dolly.pointA,pointB:id==='B'?pos:prev.dolly.pointB}}:prev);}}/>}{rig?.type==='curved'&&<CurvedTrackRails rig={rig} selCp={trackCpId} onSelCp={setTrackCpId} onMoveCp={(id,pos)=>{setRig(prev=>{if(!prev?.curved)return prev;const cps=prev.curved.controlPoints.map(cp=>cp.id===id?{...cp,position:pos}:cp);return{...prev,curved:{...prev.curved,controlPoints:cps}};});}}/>}{rig?.type==='orbit'&&<OrbitRing rig={rig}/>}</Suspense></Canvas>
      </div>
      <div style={{width:160,padding:'10px',borderLeft:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0,background:'rgba(0,0,0,0.15)'}}><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:8}}>属性</div>
        {selObj?<div style={{display:'flex',flexDirection:'column',gap:8}}>
          <div style={{fontSize:12,color:'rgba(255,255,255,0.55)'}}>类型:<span style={{color:'#ccc'}}>{selObj.type==='box'?'立方体':selObj.type==='sphere'?'球体':selObj.type==='cylinder'?'圆柱':selObj.type==='plane'?'平面':selObj.type==='camera'?'摄像机':'人物'}</span></div>
          {selObj.type==='figure'&&<div style={{fontSize:12,color:'rgba(255,255,255,0.55)'}}>姿态:<span style={{color:'#ccc'}}>{poseRegistry.get(selObj.figurePose||'')?.name||selObj.figurePose}</span></div>}
          <div style={{display:'flex',gap:4}}><button onClick={()=>setGizmoMode('translate')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='translate'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='translate'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='translate'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>移动</button><button onClick={()=>setGizmoMode('rotate')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='rotate'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='rotate'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='rotate'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>旋转</button><button onClick={()=>setGizmoMode('scale')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='scale'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='scale'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='scale'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>缩放</button></div>
          <div style={{fontSize:11,color:'rgba(255,255,255,0.55)'}}>位置<br/><span style={{color:'#ccc',fontSize:10}}>X:{selObj.position[0].toFixed(1)} Y:{selObj.position[1].toFixed(1)} Z:{selObj.position[2].toFixed(1)}</span></div>
          <button onClick={()=>{pushUndo(objects);setObjects(prev=>prev.map(o=>o.id===selectedId?{...o,position:[0,o.type==='figure'||o.type==='plane'?0:0.5,0]as Vec3,rotation:[0,0,0]as Vec3}:o));}} style={{padding:6,borderRadius:6,fontSize:10,cursor:'pointer',background:'rgba(200,160,0,0.08)',border:'1px solid rgba(200,160,0,0.2)',color:'#886600',width:'100%'}}>复位</button>
          <button onClick={()=>{pushUndo(objects);setObjects(prev=>prev.filter(o=>o.id!==selectedId));setSelectedId(null);}} style={{padding:7,background:'rgba(200,60,60,0.08)',border:'1px solid rgba(200,60,60,0.2)',borderRadius:8,color:'#664444',fontSize:11,cursor:'pointer',width:'100%'}}>删除</button>
        </div>:<div style={{fontSize:10,color:'rgba(255,255,255,0.2)',lineHeight:1.6}}>点击物体选中<br/>拖GLB导入<br/>右键旋转视角<br/>Esc取消选中<br/>Del删除选中</div>}
      </div>
    </div>
    {showCam&&<div style={{position:'absolute',bottom:40,right:16,zIndex:100,width:680,background:'#111',borderRadius:12,overflow:'hidden',border:'2px solid #333',boxShadow:'0 0 20px rgba(0,0,0,0.5)'}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'4px 8px',background:'#1a1a1a',gap:4}}><span style={{fontSize:10,color:'#e44',fontWeight:600}}>● REC</span><select value={vcamLens} onChange={e=>setVcamLens(e.target.value)} style={{background:'#222',border:'1px solid #444',borderRadius:4,color:'#ccc',fontSize:10,padding:'2px 4px'}}>{Object.entries(LENSES).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select><select value={vcamAperture} onChange={e=>setVcamAperture(Number(e.target.value))} style={{background:'#222',border:'1px solid #444',borderRadius:4,color:'#ccc',fontSize:10,padding:'2px 4px'}}>{[1.3,1.4,2,2.8,4,5.6,8,11,16,22].map(v=><option key={v} value={v}>T{v}</option>)}</select><button onClick={()=>{const c=pipCanvasRef.current?.querySelector('canvas');if(!c)return;const u=c.toDataURL('image/png');const s=useCanvasStore.getState();const cn=s.nodes.get(nodeId);const nx=(cn?.pos?.x||0)+540;const ny=cn?.pos?.y||0;const nid=s.addNode('image.generate',{x:nx,y:ny},'PiP '+vcamLens+' T'+vcamAperture);s.updateNode(nid,{meta:{gen:{imageUrl:u,prompt:'',model:'GPT Image2',aspect:'16:9',resolution:'2K',quality:'high',resultAssetIds:[]}}});s.triggerSync();}} style={{background:'#c44',border:'1px solid #e66',borderRadius:4,color:'#fff',fontSize:10,padding:'2px 8px',cursor:'pointer',fontWeight:600}}>📸</button><span style={{fontSize:9,color:'#888'}}>ARRI S35</span></div>
      <div ref={pipCanvasRef} style={{position:'relative',width:'100%',height:380}}>
        <Canvas key={vcamLens} camera={{position:[0,0,0],fov:lensData.fov,near:0.1,far:100}} gl={{antialias:true,preserveDrawingBuffer:true}} style={{width:'100%',height:'100%'}}>
          <AnimationSync time={playTime} active={playing}/><CheckerGround/><ProcSky sunAzimuth={sunAzimuth} sunElevation={sunElevation}/><CloudLayer/><PiPCam camRef={activeCamRef}/>
          <ambientLight intensity={0.8} color="#ffffff"/><SunLight azimuth={sunAzimuth} elevation={sunElevation}/>
          <Grid position={[0,-0.01,0]} args={[100,100]} cellSize={1} cellThickness={0.5} cellColor="#666" sectionSize={5} sectionThickness={1.5} sectionColor="#999" fadeDistance={25} infiniteGrid/>
          {objects.map(o=><group key={o.id} position={o.position} rotation={o.rotation} scale={o.scale}>{o.type==='figure'?o.figureSrc?<SafeModel poseId={o.figurePose||''} figureSrc={o.figureSrc} fallback={null}/>:null:o.type==='box'?<mesh><boxGeometry/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:o.type==='sphere'?<mesh><sphereGeometry args={[0.5,16,16]}/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:o.type==='cylinder'?<mesh><cylinderGeometry args={[0.5,0.5,1,16]}/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:o.type==='plane'?<mesh><planeGeometry/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:null}</group>)}
        </Canvas>
        <div style={{position:'absolute',inset:0,pointerEvents:'none',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:'80%',height:'80%',border:'1px solid rgba(255,255,255,0.3)'}}/></div>
      </div>
    </div>}
        {rig&&<div style={{position:'absolute',bottom:0,left:0,right:0,zIndex:101,background:'rgba(0,0,0,0.85)',borderTop:'1px solid rgba(255,255,255,0.1)',padding:'6px 14px',height:timelineH,overflow:'hidden'}}>
      <div style={{position:'absolute',top:-3,left:'50%',transform:'translateX(-50%)',width:40,height:6,background:'rgba(255,255,255,0.3)',borderRadius:3,cursor:'ns-resize',zIndex:102}}
        onMouseDown={e=>{e.preventDefault();const sY=e.clientY,sH=timelineH;const mv=(me)=>{setTimelineH(Math.max(60,Math.min(300,sH+(sY-me.clientY))));};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}/>
      <div style={{display:'flex',alignItems:'center',gap:6,marginBottom:4}}>
        <button onClick={()=>{if(playing)setPlaying(false);else{if(playTime>=rig.duration)setPlayTime(0);setPlaying(true);}}} style={{padding:'4px 10px',borderRadius:5,fontSize:12,fontWeight:700,cursor:'pointer',background:playing?'rgba(200,160,0,0.15)':'rgba(100,255,100,0.1)',border:playing?'1px solid rgba(200,160,0,0.3)':'1px solid rgba(100,255,100,0.2)',color:playing?'#cc0':'#0c0'}}>{playing?'暂停':'播放'}</button>
        <button onClick={()=>{setPlaying(false);setPlayTime(0);const cam=getTrackCamera(0);if(cam&&activeCamRef.current)activeCamRef.current.position.copy(cam.pos);}} style={{padding:'4px 10px',borderRadius:5,fontSize:12,cursor:'pointer',background:'rgba(255,80,80,0.08)',border:'1px solid rgba(255,80,80,0.2)',color:'#c44'}}>停止</button>
        <button onClick={()=>{const t=playTime||0;const p=activeCamRef.current?.rotation.x||0;const y=activeCamRef.current?.rotation.y||0;const sk={time:t,speed:1};const rk={time:t,pitch:p,yaw:y};setRig({...rig,speedCurve:[...rig.speedCurve.filter(x=>Math.abs(x.time-t)>0.3),sk].sort((a,b)=>a.time-b.time),rotationKeys:[...rig.rotationKeys.filter(x=>Math.abs(x.time-t)>0.3),rk].sort((a,b)=>a.time-b.time)});}} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(100,180,255,0.12)',border:'1px solid rgba(100,180,255,0.25)',color:'#a0c8ff'}}>+关键帧</button>
        <button onClick={()=>setRig(prev=>prev?{...prev,speedCurve:[],rotationKeys:[]}:prev)} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(255,100,100,0.08)',border:'1px solid rgba(255,100,100,0.2)',color:'#f88'}}>清除</button>
        <span style={{fontSize:11,color:'#ccc',fontWeight:600,marginLeft:8}}>{(playTime||0).toFixed(1)}s / {rig.duration}s</span>
      </div>
      <div style={{display:'flex',alignItems:'center',gap:4,marginBottom:2}}>
        <span style={{fontSize:8,color:'rgba(255,255,255,0.3)'}}>缩放 {zoom}%</span>
      </div>
      <div style={{position:'relative',height:26,background:'rgba(255,255,255,0.05)',borderRadius:4,cursor:'pointer',overflow:'hidden'}}
        onWheel={e=>{e.preventDefault();setZoom(prev=>Math.max(10,Math.min(100,prev+(e.deltaY<0?10:-10))));}}
        onMouseDown={e=>{if(!rig||playing)return;const r=(e.target as HTMLElement).getBoundingClientRect();const t=((e.clientX-r.left)/r.width)*rig.duration;setPlayTime(Math.max(0,Math.min(rig.duration,t)));}}>
        {/* Frame ruler ticks */}
        {(()=>{const fps=30;const frameMs=1/fps;const totalFrames=Math.ceil(rig.duration*fps);const majorEvery=Math.max(1,Math.round(5*(zoom/100)));const ticks=[];for(let f=0;f<=totalFrames;f+=majorEvery){const x=(f/(totalFrames||1))*100;ticks.push(<div key={'t'+f} style={{position:'absolute',left:x+'%',top:0,width:1,height:12,background:'rgba(255,255,255,0.15)'}}/>);}return ticks;})()}
        {/* Sub-ticks at high zoom */}
        {zoom>=80&&(()=>{const fps=30;const totalFrames=Math.ceil(rig.duration*fps);const ticks=[];for(let f=0;f<=totalFrames;f++){const x=(f/(totalFrames||1))*100;ticks.push(<div key={'st'+f} style={{position:'absolute',left:x+'%',top:0,width:1,height:6,background:'rgba(255,255,255,0.06)'}}/>);}return ticks;})()}
        <div style={{position:'absolute',left:0,top:0,height:'100%',width:(playTime/Math.max(0.1,rig.duration))*100+'%',background:'rgba(100,180,255,0.15)',borderRight:'2px solid #60a0ff',pointerEvents:'none'}}/>
        {rig.speedCurve&&rig.speedCurve.map((k,i)=><div key={'sk'+i} style={{position:'absolute',left:(k.time/rig.duration)*100+'%',bottom:2,width:8,height:8,background:'#ffcc00',border:'1px solid #222',borderRadius:'50%',transform:'translate(-50%,0)',cursor:'grab',zIndex:2}}
          onMouseDown={ev=>{ev.stopPropagation();ev.preventDefault();const sX=ev.clientX,sT=k.time;const mv=(me)=>{if(!rig)return;const r2=(ev.target as HTMLElement).parentElement!.getBoundingClientRect();const dt=((me.clientX-sX)/r2.width)*rig.duration;const u=[...rig.speedCurve];u[i]={time:Math.max(0,Math.min(rig.duration,sT+dt)),speed:u[i].speed};setRig({...rig,speedCurve:u.sort((a,b)=>a.time-b.time)});};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}
          onContextMenu={ev=>{ev.preventDefault();setRig({...rig,speedCurve:rig.speedCurve.filter((_,j)=>j!==i)});}}/>)}
        {rig.rotationKeys&&rig.rotationKeys.map((k,i)=><div key={'rk'+i} style={{position:'absolute',left:(k.time/rig.duration)*100+'%',top:2,width:6,height:20,background:'#44ff44',borderRadius:2,cursor:'grab',zIndex:2}}
          onMouseDown={ev=>{ev.stopPropagation();ev.preventDefault();const sX=ev.clientX,sT=k.time;const mv=(me)=>{if(!rig)return;const r2=(ev.target as HTMLElement).parentElement!.getBoundingClientRect();const dt=((me.clientX-sX)/r2.width)*rig.duration;const u=[...rig.rotationKeys];u[i]={...u[i],time:Math.max(0,Math.min(rig.duration,sT+dt))};setRig({...rig,rotationKeys:u.sort((a,b)=>a.time-b.time)});};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}
          onContextMenu={ev=>{ev.preventDefault();setRig({...rig,rotationKeys:rig.rotationKeys.filter((_,j)=>j!==i)});}}/>)}
      </div>
    </div>}
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:20,padding:'5px 16px',borderTop:'1px solid rgba(255,255,255,0.06)',flexShrink:0,fontSize:10,color:'rgba(255,255,255,0.2)',background:'rgba(0,0,0,0.15)'}}><span>左键选中</span><span>移动/旋转/缩放</span><span>右键视角</span><span>Esc取消</span><span>Ctrl+Z撤销</span></div>
  </div>,document.body);
}

const NODE_W=500,NODE_H=300;
export function Scene3DNode({id,data,selected}:{id:string;data:{title?:string;isConnecting?:boolean;isConnectTarget?:boolean;multiSelect?:boolean;isPickMode?:boolean;isPickTarget?:boolean;onChange?:(p:Record<string,unknown>)=>void;};selected?:boolean;}){
  const[objects,setObjects]=useState<SceneObject[]>([]);const[selId,setSelId]=useState<string|null>(null);const[fs,setFs]=useState(false);const[gizmoMode,setGizmoMode]=useState<GizmoMode>('translate');const[rig,setRig]=useState<CameraRig|null>(null);const ctr=useRef(0);
  useEffect(()=>{initPoseRegistry();},[]);
  useEffect(()=>{const h=(e:Event)=>{const{id,position,rotation,scale}=(e as CustomEvent).detail as{id:string;position:Vec3;rotation?:Vec3;scale?:Vec3};const obj=objects.find(o=>o.id===id);const minY=obj&&(obj.type==='figure'||obj.type==='plane')?0:0.5;const p:Vec3=position[1]<minY?[position[0],minY,position[2]]:position;setObjects(prev=>prev.map(o=>o.id===id?{...o,position:p,rotation:rotation||o.rotation,scale:scale||o.scale}:o));};window.addEventListener('scene3d-object-moved',h);return()=>window.removeEventListener('scene3d-object-moved',h);},[objects]);
  const addObj=useCallback((type:SceneObject['type'])=>{ctr.current++;const y=type==='figure'||type==='plane'?0:0.5;const first=poseRegistry.size>0?poseRegistry.keys().next().value as string:'stand1';const obj:SceneObject={id:`o_${ctr.current}`,type,position:[0,y,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:type==='figure'?first:undefined,figureSrc:type==='figure'?poseRegistry.get(first)?.src:undefined};setObjects(prev=>[...prev,obj]);setSelId(obj.id);},[]);
  const delSel=useCallback(()=>{if(!selId)return;setObjects(prev=>prev.filter(o=>o.id!==selId));setSelId(null);},[selId]);
  const hSnap=useCallback(()=>{const c=document.querySelector('canvas');if(!c)return;const u=c.toDataURL('image/png');const store=useCanvasStore.getState();const n=store.nodes.get(id);if(n){const m=(n.meta||{})as Record<string,unknown>;store.updateNode(id,{meta:{...m,gen:{...((m.gen as Record<string,unknown>)||{}),imageUrl:u}}});store.triggerSync();}},[id]);
  return(<>{fs&&<FullscreenEditor objects={objects} selectedId={selId} setObjects={setObjects} setSelectedId={setSelId} onSnapshot={hSnap} onClose={()=>setFs(false)} nodeId={id} rig={rig} setRig={setRig}/>}
    <div style={{width:NODE_W,background:'rgba(18,20,24,0.95)',border:selected?'2px solid rgba(100,140,255,0.7)':'1px solid rgba(255,255,255,0.08)',borderRadius:14,overflow:'hidden',boxShadow:selected?'0 0 24px rgba(100,140,255,0.18)':'0 4px 16px rgba(0,0,0,0.3)',transition:'border 0.15s, box-shadow 0.15s'}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'6px 12px',borderBottom:'1px solid rgba(255,255,255,0.06)',fontSize:12,color:'rgba(255,255,255,0.5)',fontWeight:600,flexShrink:0}}><span>🎬 {data.title||'3D 场景'}</span><span style={{fontSize:10,color:'rgba(255,255,255,0.2)'}}>{objects.length} 物体</span></div>
      <div style={{width:'100%',height:NODE_H,position:'relative',background:'#3a3a3a',overflow:'hidden'}}><Canvas shadows camera={{position:[5,4,7],fov:50,near:0.1,far:100}} gl={{preserveDrawingBuffer:true,antialias:false,powerPreference:'high-performance'}} dpr={[0.5,1.5]} style={{width:'100%',height:'100%'}}><Suspense fallback={null}><SceneContent objects={objects} selectedId={selId} onSelect={setSelId} gizmoMode={gizmoMode}/></Suspense></Canvas>
        {selected?<button onClick={()=>setFs(true)} className="nodrag" style={{position:'absolute',top:'50%',left:'50%',transform:'translate(-50%,-50%)',padding:'10px 24px',borderRadius:10,fontSize:13,fontWeight:600,background:'rgba(100,140,255,0.15)',border:'1px solid rgba(100,140,255,0.3)',color:'rgba(140,170,255,0.9)',cursor:'pointer',zIndex:5}}>⛶ 全屏编辑</button>:<div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,0.4)',pointerEvents:'none'}}><div style={{textAlign:'center'}}><div style={{fontSize:36,opacity:0.15}}>🎬</div><div style={{fontSize:12,color:'rgba(255,255,255,0.35)',marginTop:4}}>选中节点开始编辑</div></div></div>}
      </div>
      <div style={{display:'flex',alignItems:'center',gap:5,padding:'6px 10px',borderTop:'1px solid rgba(255,255,255,0.06)',flexShrink:0,overflowX:'auto'}}><EBtn label="立方体" onClick={()=>addObj('box')}/><EBtn label="球体" onClick={()=>addObj('sphere')}/><EBtn label="圆柱" onClick={()=>addObj('cylinder')}/><EBtn label="平面" onClick={()=>addObj('plane')}/><EBtn label="人物" onClick={()=>addObj('figure')}/><span style={{flex:1}}/><button onClick={()=>setGizmoMode('translate')} title="移动" style={{padding:'4px 8px',borderRadius:5,fontSize:11,cursor:'pointer',background:gizmoMode==='translate'?'rgba(100,140,255,0.15)':'transparent',border:gizmoMode==='translate'?'1px solid rgba(100,140,255,0.25)':'1px solid transparent',color:gizmoMode==='translate'?'#a0c0ff':'rgba(255,255,255,0.35)'}}>↕</button><button onClick={()=>setGizmoMode('rotate')} title="旋转" style={{padding:'4px 8px',borderRadius:5,fontSize:11,cursor:'pointer',background:gizmoMode==='rotate'?'rgba(100,140,255,0.15)':'transparent',border:gizmoMode==='rotate'?'1px solid rgba(100,140,255,0.25)':'1px solid transparent',color:gizmoMode==='rotate'?'#a0c0ff':'rgba(255,255,255,0.35)'}}>↻</button><button onClick={()=>setGizmoMode('scale')} title="缩放" style={{padding:'4px 8px',borderRadius:5,fontSize:11,cursor:'pointer',background:gizmoMode==='scale'?'rgba(100,140,255,0.15)':'transparent',border:gizmoMode==='scale'?'1px solid rgba(100,140,255,0.25)':'1px solid transparent',color:gizmoMode==='scale'?'#a0c0ff':'rgba(255,255,255,0.35)'}}>⤡</button>{selId&&<EBtn label="删除" onClick={delSel}/>}</div>
      <Handle type="target" position={Position.Left} id="image-in" style={{background:'rgba(180,180,200,0.5)',width:10,height:10,border:'none'}}/>
      <Handle type="source" position={Position.Right} id="image-out" style={{background:'rgba(180,180,200,0.5)',width:10,height:10,border:'none'}}/>
    </div>
  </>);
}