/* === Scene3DNode v2 — clean rewrite === */
import React,{useState,useCallback,useMemo,useRef,useEffect,Suspense}from'react';
import{createPortal}from'react-dom';
import{Handle,Position}from'@xyflow/react';
import{Canvas,useThree,useFrame}from'@react-three/fiber';
import{OrbitControls,Grid,TransformControls,useGLTF,useFBX,useTexture,useAnimations}from'@react-three/drei';
import{AutoRigButton}from'./AutoRigButton';
import{Sky}from'three/examples/jsm/objects/Sky';
import{FBXLoader}from'three/examples/jsm/loaders/FBXLoader';
import{mergeGeometries}from'three/examples/jsm/utils/BufferGeometryUtils.js';
import*as THREE from'three';
const animMixers=new Map<string,THREE.AnimationMixer>();let animTime=0;let animPlaying=false;let animSpeed=0.7;let _oid=Date.now();
import{useCanvasStore}from'../../store/useCanvasStore';

// Types
interface SceneObject{id:string;type:'box'|'sphere'|'cylinder'|'plane'|'figure'|'camera';position:Vec3;rotation:Vec3;scale:Vec3;color?:string;figurePose?:string;figureSrc?:string;figureFmt?:string;}
type Vec3=[number,number,number];type GizmoMode='translate'|'rotate'|'scale';type TrackType='dolly'|'curved'|'orbit';interface SpeedKey{time:number;speed:number;}interface RotationKey{time:number;pitch:number;yaw:number;}interface AnimTrack{modelId:string;start:number;dur:number;color:string;}
interface CameraRig{type:TrackType;duration:number;speedCurve:SpeedKey[];rotationKeys:RotationKey[];animTracks:AnimTrack[];dolly?:{pointA:Vec3;pointB:Vec3;};curved?:{controlPoints:{id:string;position:Vec3;}[];};orbit?:{center:Vec3;radius:number;height:number;startAngle:number;endAngle:number;controlPoints:{id:string;position:Vec3}[];};}
interface JointSet{head:Vec3;neck:Vec3;shoulderL:Vec3;shoulderR:Vec3;elbowL:Vec3;elbowR:Vec3;handL:Vec3;handR:Vec3;hip:Vec3;hipL:Vec3;hipR:Vec3;kneeL:Vec3;kneeR:Vec3;footL:Vec3;footR:Vec3;}
const KNOWN_POSES=['stand1','stand2','sit','walk','run','squat','lie','fight'];
type PoseEntry={name:string;src:string;format?:'glb'|'fbx'};
const poseRegistry=new Map<string,PoseEntry>();let poseInitDone=false;
async function initPoseRegistry(){if(poseInitDone)return;poseInitDone=true;const r=await Promise.all(KNOWN_POSES.map(async id=>{try{const r=await fetch(`/models/${id}.glb`,{method:'HEAD'});if(r.ok)return{id,ext:'glb'};}catch{}return null;}));r.filter(Boolean).forEach(x=>{if(x)poseRegistry.set(x.id,{name:PF[x.id]||x.id,src:`/models/${x.id}.glb`});});}
const PF:Record<string,string>={stand1:'站立1',stand2:'站立2',sit:'坐姿',walk:'行走',run:'跑步',squat:'蹲姿',lie:'卧躺',fight:'格斗'};
function importFile(file:File,done:(entry:PoseEntry,poseId:string)=>void){const name=file.name.replace(/\.(glb|fbx)$/i,'');const id=name.toLowerCase().replace(/[^a-z0-9]/g,'_')||`pose_${Date.now()}`;const ext=file.name.endsWith('.fbx')?'fbx':'glb';if(ext==='fbx'){const r=new FileReader();r.onload=()=>{const buf=r.result as ArrayBuffer;const blob=new Blob([buf],{type:'application/octet-stream'});const url=URL.createObjectURL(blob);const e:PoseEntry={name,src:url,format:'fbx'};poseRegistry.set(id,e);done(e,id);};r.readAsArrayBuffer(file);return;}const r=new FileReader();r.onload=()=>{const src=r.result as string;const e:PoseEntry={name,src,format:'glb'};poseRegistry.set(id,e);done(e,id);};r.readAsDataURL(file);}
export function addPoseEntry(id:string,name:string,src:string,format?:'glb'|'fbx'){poseRegistry.set(id,{name,src,format});if(!poseInitDone)poseInitDone=true;}
const POSE_JOINTS:Record<string,JointSet>={stand:{head:[0,1.68,0],neck:[0,1.50,0],shoulderL:[-0.28,1.46,0],shoulderR:[0.28,1.46,0],elbowL:[-0.28,1.16,0],elbowR:[0.28,1.16,0],handL:[-0.28,0.86,0],handR:[0.28,0.86,0],hip:[0,0.85,0],hipL:[-0.14,0.83,0],hipR:[0.14,0.83,0],kneeL:[-0.14,0.42,0],kneeR:[0.14,0.42,0],footL:[-0.14,0.04,0],footR:[0.14,0.04,0]},sit:{head:[0,1.24,0],neck:[0,1.06,0],shoulderL:[-0.28,1.02,0],shoulderR:[0.28,1.02,0],elbowL:[-0.34,0.72,0.18],elbowR:[0.34,0.72,0.18],handL:[-0.40,0.48,0.30],handR:[0.40,0.48,0.30],hip:[0,0.40,0],hipL:[-0.18,0.38,0.12],hipR:[0.18,0.38,0.12],kneeL:[-0.36,0.30,0.28],kneeR:[0.36,0.30,0.28],footL:[-0.44,0.16,0.40],footR:[0.44,0.16,0.40]}};
function buildFigure(j:JointSet,c:string):React.ReactNode[]{const r:React.ReactNode[]=[];let k=0;const cyl=(a:Vec3,b:Vec3,rad:number)=>{const mx=(a[0]+b[0])/2,my=(a[1]+b[1])/2,mz=(a[2]+b[2])/2;const dx=b[0]-a[0],dy=b[1]-a[1],dz=b[2]-a[2];const len=Math.sqrt(dx*dx+dy*dy+dz*dz);const q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(dx,dy,dz).normalize());r.push(<mesh key={k++} position={[mx,my,mz]} quaternion={q} scale={[rad,len/2,rad]}><cylinderGeometry args={[1,1,2,10]}/><meshStandardMaterial color={c} roughness={0.5} metalness={0.2}/></mesh>);};const sph=(p:Vec3,rad:number)=>{r.push(<mesh key={k++} position={p} scale={rad}><sphereGeometry args={[1,14,14]}/><meshStandardMaterial color={c} roughness={0.5} metalness={0.2}/></mesh>);};const box=(p:Vec3,scl:Vec3)=>{r.push(<mesh key={k++} position={p} scale={scl}><boxGeometry/><meshStandardMaterial color={c} roughness={0.5} metalness={0.2}/></mesh>);};cyl(j.neck,j.hip,0.20);sph(j.head,0.14);sph(j.neck,0.07);sph(j.shoulderL,0.07);sph(j.shoulderR,0.07);cyl(j.shoulderL,j.elbowL,0.075);cyl(j.shoulderR,j.elbowR,0.075);sph(j.elbowL,0.055);sph(j.elbowR,0.055);cyl(j.elbowL,j.handL,0.065);cyl(j.elbowR,j.handR,0.065);sph(j.handL,0.055);sph(j.handR,0.055);sph(j.hip,0.10);cyl(j.hipL,j.kneeL,0.10);cyl(j.hipR,j.kneeR,0.10);sph(j.kneeL,0.065);sph(j.kneeR,0.065);cyl(j.kneeL,j.footL,0.085);cyl(j.kneeR,j.footR,0.085);box([j.footL[0],j.footL[1]-0.06,j.footL[2]+0.04],[0.10,0.04,0.14]);box([j.footR[0],j.footR[1]-0.06,j.footR[2]+0.04],[0.10,0.04,0.14]);return r;}
function StickFigure({poseId,color='#c0c8d0'}:{poseId:string;color?:string}){const j=POSE_JOINTS[poseId||'stand'];return j?<group>{buildFigure(j,color)}</group>:null;}
const OBJ_COLORS=['#8899aa','#99aabb','#aabbcc','#778899','#b0bec5'];const pickColor=()=>OBJ_COLORS[Math.floor(Math.random()*OBJ_COLORS.length)];
const SHARED_MAT=new THREE.MeshStandardMaterial({color:'#aaaaaa',roughness:0.35,metalness:0.25});
function standardize(child:any){if(child.isMesh){child.material=SHARED_MAT;}}function mergeGroupMeshes(g:THREE.Group){const byMat=new Map<string,{mat:THREE.Material;geoms:THREE.BufferGeometry[]}>();g.traverse((ch:any)=>{if(ch.isMesh&&ch.geometry){const k=ch.material.uuid;if(!byMat.has(k))byMat.set(k,{mat:ch.material,geoms:[]});byMat.get(k)!.geoms.push(ch.geometry.clone());}});if(byMat.size===0)return;g.clear();for(const[,v]of byMat){if(v.geoms.length>1){const mg=mergeGeometries(v.geoms,false);g.add(new THREE.Mesh(mg,v.mat));}else{g.add(new THREE.Mesh(v.geoms[0],v.mat));}}}
function normalizeScale(group:THREE.Group){const box=new THREE.Box3().setFromObject(group);const size=box.getSize(new THREE.Vector3());const maxDim=Math.max(size.x,size.y,size.z);if(maxDim>3){const s=3/maxDim;group.scale.setScalar(s);group.position.y+=box.min.y*s*-1;}}
function SafeModel({poseId,figureSrc,fallback,objId,noAnim,figureFmt}:{poseId:string;figureSrc?:string;fallback:React.ReactNode;objId?:string;noAnim?:boolean;figureFmt?:string}){const src=figureSrc||(poseRegistry.get(poseId)?.src);const[exists,setExists]=useState<boolean|string>('loading');useEffect(()=>{if(!src){setExists(false);return;}if(src.startsWith('data:')||src.startsWith('blob:')){setExists(src);return;}let c=false;fetch(src,{method:'HEAD'}).then(r=>{if(!c)setExists(r.ok?src:false);}).catch(()=>{if(!c)setExists(false);});return()=>{c=true;};},[src]);if(exists==='loading')return null;if(!exists||typeof exists!=='string')return<>{fallback}</>;const isFBX=figureFmt==='fbx'||exists.toString().includes('S2F5ZGFyYSBGQlgg')||poseRegistry.get(poseId)?.format==='fbx';const id=noAnim?undefined:objId;return<ModelEB fallback={fallback}>{isFBX?<FBXModel src={exists as string} objId={id}/>:<GLBModel src={exists as string} objId={id}/>}</ModelEB>;}
class ModelEB extends React.Component<{fallback:React.ReactNode;children:React.ReactNode},{err:boolean}>{constructor(p:{fallback:React.ReactNode;children:React.ReactNode}){super(p);this.state={err:false};}static getDerivedStateFromError(){return{err:true};}render(){return this.state.err?this.props.fallback:this.props.children;}}
function GLBModel({src,objId}:{src:string;objId?:string}){const{scene,animations}=useGLTF(src);const cloned=useMemo(()=>{const s=scene.clone(true);s.traverse(standardize);mergeGroupMeshes(s);normalizeScale(s);return s;},[scene]);const wrapped=useMemo(()=>{const g=new THREE.Group();const cc=cloned.clone(true);g.add(cc);addBoneOcta(g);return g;},[cloned]);useEffect(()=>{if(objId){const m=new THREE.AnimationMixer(cloned);if(animations.length>0){animations.forEach(c=>{const a=m.clipAction(c);a.setLoop(THREE.LoopRepeat,Infinity);a.play();a.paused=true;});}animMixers.set(objId,m);return()=>{animMixers.delete(objId);};}},[cloned,animations,objId]);return<primitive object={wrapped}/>;}
function FBXModel({src,objId}:{src:string;objId?:string}){const[scene,setScene]=useState<THREE.Group|null>(null);const[anims,setAnims]=useState<THREE.AnimationClip[]>([]);useEffect(()=>{let c=false;const loader=new FBXLoader();loader.load(src,(fbx:THREE.Group)=>{if(c)return;fbx.traverse(standardize);normalizeScale(fbx);addBoneOcta(fbx);setScene(fbx);const a=(fbx as any).animations||(loader as any).animations||[];setAnims(a);},undefined,()=>setScene(new THREE.Group()));return()=>{c=true;};},[src]);useEffect(()=>{if(scene&&objId){const m=new THREE.AnimationMixer(scene);if(anims.length>0){anims.forEach(c=>{const a=m.clipAction(c);a.setLoop(THREE.LoopRepeat,Infinity);a.play();a.paused=true;});}else{scene.traverse((ch:any)=>{if(ch.isSkinnedMesh){const dummy=new THREE.AnimationClip('dummy',1,[]);m.clipAction(dummy);}});}animMixers.set(objId,m);return()=>{animMixers.delete(objId);};}},[scene,anims,objId]);return scene?<primitive object={scene}/>:null;}
function addBoneOcta(root:THREE.Object3D){const sms:THREE.SkinnedMesh[]=[];root.traverse(c=>{if((c as any).isSkinnedMesh)sms.push(c as THREE.SkinnedMesh);});if(!sms.length)console.warn('[bone] No SkinnedMesh found in model');for(const sm of sms){if(!sm.skeleton?.bones.length){console.warn('[bone] SkinnedMesh has no skeleton');continue;}console.log('[bone] Found',sm.skeleton.bones.length,'bones');const helper=new THREE.SkeletonHelper(sm);helper.material.linewidth=2;(helper.material as any).depthTest=false;root.add(helper);const sk=sm.skeleton;const depths=new Map<THREE.Bone,number>();const walk=(b:THREE.Bone,d:number)=>{depths.set(b,d);b.children.forEach(c=>{if(c instanceof THREE.Bone)walk(c,d+1);});};walk(sk.bones[0],0);sk.bones.forEach(b=>{const depth=depths.get(b)||0;const t=Math.min(1,depth/8);const r=0.3+0.7*(1-t);const g=0.9-0.5*t;const bl=1-0.6*t;const childBone=b.children.find(c=>c instanceof THREE.Bone)as THREE.Bone|null;const size=0.06+0.02*(1-t);const sphere=new THREE.Mesh(new THREE.SphereGeometry(size,6,4),new THREE.MeshBasicMaterial({color:new THREE.Color(r,g,bl),depthTest:false,transparent:true,opacity:0.9}));b.add(sphere);if(childBone){const coneLen=0.12;const cone=new THREE.Mesh(new THREE.ConeGeometry(size*1.2,coneLen,5,2),new THREE.MeshBasicMaterial({color:new THREE.Color(r,g,bl),depthTest:false,transparent:true,opacity:0.7}));cone.position.copy(childBone.position).multiplyScalar(0.5);cone.lookAt(childBone.position);cone.rotateX(Math.PI/2);b.add(cone);}});}}
const SCALE_FACTOR=0.12;
function RotationGizmo({center,onRotate}:{center:Vec3;onRotate:(axis:0|1|2,dx:number,dy:number)=>void}){const{gl,camera}=useThree();const gRef=useRef<THREE.Group>(null);const drag=useRef<{axis:0|1|2;lastX:number;lastY:number}|null>(null);useFrame(()=>{if(!gRef.current)return;const d=camera.position.distanceTo(new THREE.Vector3(...center));gRef.current.scale.setScalar(d*SCALE_FACTOR);});const onDown=useCallback((axis:0|1|2)=>(e:any)=>{e.stopPropagation();if(drag.current)return;window.dispatchEvent(new CustomEvent('gizmo-drag-start'));drag.current={axis,lastX:e.clientX,lastY:e.clientY};(gl.domElement as any).style.cursor='grabbing';},[gl.domElement]);useEffect(()=>{const mv=(e:PointerEvent)=>{if(!drag.current)return;const dx=e.clientX-drag.current.lastX,dy=e.clientY-drag.current.lastY;drag.current.lastX=e.clientX;drag.current.lastY=e.clientY;onRotate(drag.current.axis,dx,dy);};const up=()=>{if(!drag.current)return;(gl.domElement as any).style.cursor='';window.dispatchEvent(new CustomEvent('gizmo-drag-end'));drag.current=null;};window.addEventListener('pointermove',mv);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',mv);window.removeEventListener('pointerup',up);};},[onRotate,gl.domElement]);const W=0.05;return(<group ref={gRef} position={center as[number,number,number]}><group onPointerDown={onDown(2)}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#4488ff" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group><group onPointerDown={onDown(1)} rotation={[Math.PI/2,0,0]}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#ddbb00" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group><group onPointerDown={onDown(0)} rotation={[0,-Math.PI/2,0]}><mesh><ringGeometry args={[1-W,1+W,32,1,0,Math.PI/2]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6} side={THREE.DoubleSide}/></mesh></group></group>);}
function CameraAxes({sel}:{sel:boolean}){return sel?<group>{[[1,0,0,'#ff3333'],[0,1,0,'#44dd44'],[0,0,1,'#4488ff']].map(([ax,ay,az,clr])=>(<group key={clr as string}>{/* + thick */}<mesh position={[(ax as number)*0.7,(ay as number)*0.7,(az as number)*0.7]} rotation={ax?[0,0,Math.PI/2]:az?[Math.PI/2,0,0]:[0,0,0]}><cylinderGeometry args={[0.04,0.04,1.2,8]}/><meshBasicMaterial color={clr as string}/></mesh>{/* - thin */}<mesh position={[-(ax as number)*0.35,-(ay as number)*0.35,-(az as number)*0.35]} rotation={ax?[0,0,Math.PI/2]:az?[Math.PI/2,0,0]:[0,0,0]}><cylinderGeometry args={[0.012,0.012,0.7,6]}/><meshBasicMaterial color={clr as string}/></mesh></group>))}</group>:null;}
function CameraGLB({pos,tgt}:{pos:Vec3;tgt:Vec3}){const{scene}=useGLTF('/models/IMAXX%20%E6%91%84%E5%83%8F%E6%9C%BA.glb');const cloned=useMemo(()=>{const c=scene.clone(true);c.rotation.set(0,Math.PI-13*Math.PI/180,0);c.traverse((ch:any)=>{if(ch.isMesh){ch.castShadow=true;if(ch.material){ch.material.roughness=0.5;ch.material.metalness=0;ch.material.emissive=ch.material.emissive||new THREE.Color('#444');ch.material.emissiveIntensity=0.3;}}});return c;},[scene]);return<primitive object={cloned} position={[0,0.2,0]} lookAt={tgt} scale={1.5}/>;}
function FallbackCamera({pos,tgt}:{pos:Vec3;tgt:Vec3}){return<group position={pos as[number,number,number]}><mesh lookAt={tgt}><boxGeometry args={[0.45,0.28,0.4]}/><meshStandardMaterial color="#3a3a44" roughness={0.5}/></mesh><mesh lookAt={tgt} position={[0,-0.04,0.22]}><boxGeometry args={[0.38,0.16,0.2]}/><meshStandardMaterial color="#f44" emissive="#f22" emissiveIntensity={0.6}/></mesh><mesh lookAt={tgt} position={[0,0,0.28]}><cylinderGeometry args={[0.09,0.07,0.16,12]}/><meshStandardMaterial color="#555" roughness={0.3}/></mesh></group>;}
class ErrorBoundary extends React.Component<{fallback:React.ReactNode;children:React.ReactNode},{err:boolean}>{constructor(p:any){super(p);this.state={err:false};}static getDerivedStateFromError(){return{err:true};}render(){return this.state.err?this.props.fallback:this.props.children;}}
const SENSOR_H=18.17;
const LENSES:Record<string,{name:string;fov:number;maxAperture:number;minAperture:number;blades:number}>={
'24':{name:'24mm',fov:2*Math.atan(SENSOR_H/(2*24))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'35':{name:'35mm',fov:2*Math.atan(SENSOR_H/(2*35))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'50':{name:'50mm',fov:2*Math.atan(SENSOR_H/(2*50))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'85':{name:'85mm',fov:2*Math.atan(SENSOR_H/(2*85))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
'135':{name:'135mm',fov:2*Math.atan(SENSOR_H/(2*135))*(180/Math.PI),maxAperture:1.3,minAperture:22,blades:11},
};

const _p:Vec3=[0,0,0];const _r:Vec3=[0,0,0];const _s:Vec3=[1,1,1];const _f:Vec3=[0,0,0];const _fv=new THREE.Vector3();let _mt=0;const mover=(el:THREE.Object3D,obj:SceneObject)=>{const now=performance.now();if(now-_mt<200)return;_mt=now;_p[0]=el.position.x;_p[1]=el.position.y;_p[2]=el.position.z;_r[0]=el.rotation.x;_r[1]=el.rotation.y;_r[2]=el.rotation.z;_s[0]=el.scale.x;_s[1]=el.scale.y;_s[2]=el.scale.z;_fv.set(0,0,-1);el.localToWorld(_fv);_f[0]=_fv.x;_f[1]=_fv.y;_f[2]=_fv.z;(window as any).__dragObj={el};window.dispatchEvent(new CustomEvent('scene3d-object-moved',{detail:{id:obj.id,position:_p,rotation:_r,scale:_s,forward:_f,objRef:el}}));};
function TileGround(){const{scene}=useThree();const meshRef=useRef<THREE.InstancedMesh>(null);const geom=useMemo(()=>{const shape=new THREE.Shape();const s=0.49;shape.moveTo(-s,-s);shape.lineTo(s,-s);shape.lineTo(s,s);shape.lineTo(-s,s);shape.closePath();const eg=new THREE.ExtrudeGeometry(shape,{depth:0.12,bevelEnabled:true,bevelThickness:0.03,bevelSize:0.03,bevelSegments:2});eg.rotateX(-Math.PI/2);eg.translate(0,-0.06,0);return eg;},[]);useEffect(()=>{if(!meshRef.current)return;const m=meshRef.current;const dummy=new THREE.Object3D();const half=30;let idx=0;for(let x=-half;x<half;x++){for(let z=-half;z<half;z++){dummy.position.set(x+0.5,-0.06,z+0.5);dummy.updateMatrix();m.setMatrixAt(idx++,dummy.matrix);}}m.instanceMatrix.needsUpdate=true;},[]);return<instancedMesh ref={meshRef} args={[geom,undefined,3600]} receiveShadow frustumCulled={false}><meshStandardMaterial color="#c0c0c0" roughness={0.35} metalness={0.02}/></instancedMesh>;}
function CheckerGround(){return<TileGround/>;}
function ProcSky({sunAzimuth,sunElevation}:{sunAzimuth:number;sunElevation:number}){const az=sunAzimuth||45;const el=sunElevation||40;const sunDir=useMemo(()=>{const phi=THREE.MathUtils.degToRad(90-el);const theta=THREE.MathUtils.degToRad(az);return new THREE.Vector3().setFromSphericalCoords(1,phi,theta);},[az,el]);const skyMesh=useMemo(()=>{const geo=new THREE.SphereGeometry(55,64,32);const mat=new THREE.ShaderMaterial({uniforms:{uSunDir:{value:sunDir.clone()}},vertexShader:`varying vec3 vWorldPos;void main(){vec4 wp=modelMatrix*vec4(position,1.0);vWorldPos=wp.xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec3 vWorldPos;uniform vec3 uSunDir;void main(){vec3 dir=normalize(vWorldPos);float h=dir.y;float t=smoothstep(-0.05,0.35,h);vec3 zenith=vec3(0.35,0.62,0.98);vec3 horizon=vec3(0.72,0.90,1.0);vec3 col=mix(horizon,zenith,t)*1.3;float sunDot=clamp(dot(dir,uSunDir),0.0,1.0);float glow=pow(sunDot,80.0)*0.25;gl_FragColor=vec4(col+glow*vec3(1.0,0.9,0.7),1.0);}`,side:THREE.BackSide,depthWrite:false});const m=new THREE.Mesh(geo,mat);m.renderOrder=-1;m.frustumCulled=false;return m;},[]);useEffect(()=>{skyMesh.material.uniforms.uSunDir.value.copy(sunDir);},[sunDir,skyMesh]);return<primitive object={skyMesh}/>;}
function AnimationSync({time,active,rig}:{time:number;active:boolean;rig:CameraRig|null}){useEffect(()=>{if(!active){animMixers.forEach(m=>{m.time=0;Object.values((m as any)._actions).forEach((a:any)=>a.paused=true);});return;}animMixers.forEach((m)=>{if(rig?.animTracks.length){const trk=rig.animTracks[0];const inRange=time>=trk.start&&time<trk.start+trk.dur;Object.values((m as any)._actions).forEach((a:any)=>a.paused=!inRange);}else{Object.values((m as any)._actions).forEach((a:any)=>a.paused=true);}});},[active,time,rig]);useFrame((_,delta)=>{if(!active||!rig)return;animMixers.forEach((m)=>{if(rig.animTracks.length>0){const trk=rig.animTracks[0];if(time>=trk.start&&time<trk.start+trk.dur)m.update(delta*animSpeed);}});});return null;}
const cloudTexCache:{key:string;tex:THREE.CanvasTexture}|null=null as any;
function mkCloudTex(sx:number,sy:number,thresh:number,pow:number):THREE.CanvasTexture{const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d')!;const img=ctx.createImageData(512,256);const n=(x:number,y:number):number=>{let v=0,amp=1,freq=1,tot=0;for(let o=0;o<6;o++){const sx=Math.sin(y*freq*0.3+x*freq*1.5+o*1.7);const sy=Math.sin(x*freq*1.3-y*freq*0.4+o*2.3);v+=(sx*0.5+sy*0.5)*amp;tot+=amp;amp*=0.45;freq*=2.5;}return v/tot;};for(let y=0;y<256;y++){for(let x=0;x<512;x++){const nx=x/512;const ny=y/256;let v=n(nx*sx,ny*sy);v=v*0.5+0.5;v=Math.pow(Math.max(0,v-thresh),pow);let edge=1;const ex=40,ey=30;if(x<ex)edge=x/ex;else if(x>512-ex)edge=(512-x)/ex;if(y<ey)edge*=y/ey;else if(y>256-ey)edge*=(256-y)/ey;v*=Math.max(0,edge);const i=(y*512+x)*4;img.data[i]=255;img.data[i+1]=255;img.data[i+2]=255;img.data[i+3]=Math.min(255,v*255);}}ctx.putImageData(img,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t;}
function CloudLayer({sunAzimuth,sunElevation}:{sunAzimuth:number;sunElevation:number}){const az=sunAzimuth||45;const el=sunElevation||40;const phi=THREE.MathUtils.degToRad(90-el);const theta=THREE.MathUtils.degToRad(az);const sunDir=useMemo(()=>new THREE.Vector3().setFromSphericalCoords(1,phi,theta),[az,el]);const texHi=useMemo(()=>mkCloudTex(40,5,0.45,5.0),[]);const texMid=useMemo(()=>mkCloudTex(28,8,0.42,4.0),[]);const texLo=useMemo(()=>mkCloudTex(18,10,0.40,3.5),[]);const mHi=useRef<THREE.ShaderMaterial>(null);const mMid=useRef<THREE.ShaderMaterial>(null);const mLo=useRef<THREE.ShaderMaterial>(null);const mats=[mHi,mMid,mLo];useEffect(()=>{mats.forEach(r=>{if(r.current)r.current.uniforms.uSunDir.value.copy(sunDir);});},[sunDir]);const _cs=[0.022,0.014,0.008];useFrame((_,delta)=>{mats.forEach((r,i)=>{if(!r.current)return;const spd=_cs[i];r.current.uniforms.uOffset.value.y+=delta*spd;r.current.uniforms.uOffset.value.x+=delta*spd*0.15;});});const vs=`varying vec2 vUv;varying vec3 vWorldPos;void main(){vec4 wp=modelMatrix*vec4(position,1.0);vWorldPos=wp.xyz;vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;const fs=`varying vec2 vUv;varying vec3 vWorldPos;uniform sampler2D uTex;uniform vec3 uSunDir;uniform vec2 uOffset;uniform float uOpacity;void main(){vec2 uv=vUv+uOffset;float c=texture2D(uTex,uv).a;if(c<0.01)discard;vec3 n=normalize(vWorldPos);float sunDot=clamp(dot(n,uSunDir),0.0,1.0);float bright=0.4+sunDot*0.6;float edge=pow(1.0-abs(sunDot-0.5)*2.0,3.0);float silver=pow(c,2.0)*edge*0.3;float alpha=c*uOpacity;gl_FragColor=vec4(vec3(1.0)*bright+silver,alpha);}`;const mkLayer=(r:number,tex:THREE.CanvasTexture,op:number,ref:React.RefObject<THREE.ShaderMaterial>)=>{const mat=new THREE.ShaderMaterial({uniforms:{uTex:{value:tex},uSunDir:{value:sunDir.clone()},uOffset:{value:new THREE.Vector2(0,0)},uOpacity:{value:op}},vertexShader:vs,fragmentShader:fs,transparent:true,depthWrite:false,side:THREE.BackSide});return<mesh frustumCulled={false}><sphereGeometry args={[r,64,32]}/><primitive object={mat} ref={ref} attach="material"/></mesh>;};return<>{mkLayer(60,texHi,0.6,mHi)}{mkLayer(54,texMid,0.7,mMid)}{mkLayer(49,texLo,0.75,mLo)}</>;}
function SunLight({azimuth,elevation}:{azimuth:number;elevation:number}){const radAz=(azimuth*Math.PI)/180;const radEl=(elevation*Math.PI)/180;const dist=20;const x=dist*Math.cos(radEl)*Math.sin(radAz);const y=dist*Math.sin(radEl);const z=dist*Math.cos(radEl)*Math.cos(radAz);return<><hemisphereLight args={['#dde8f4','#aa9988',1.8]}/><directionalLight position={[x,y,z]} intensity={3.5} color="#fff5e8" castShadow/></>;}
const RENDER_DIST=50;const LOD_DIST=20;
function FrustumGate({pos,children}:{pos:Vec3;children:React.ReactNode}){const{camera}=useThree();const[vis,setVis]=useState(true);const vRef=useRef(true);useFrame(()=>{const d=Math.sqrt(Math.pow(pos[0]-camera.position.x,2)+Math.pow(pos[2]-camera.position.z,2));const s=d<RENDER_DIST;if(vRef.current!==s){vRef.current=s;setVis(s);}});return vis?<>{children}</>:null;}
const SceneContent=React.memo(function SceneContent({objects,selectedId,onSelect,gizmoMode,rigActive,snapToTrack,sunAzimuth,sunElevation,lookTarget,onSetLookTarget}:{objects:SceneObject[];selectedId:string|null;onSelect:(id:string|null)=>void;gizmoMode:GizmoMode;rigActive?:boolean;snapToTrack?:((p:THREE.Vector3)=>THREE.Vector3|null);sunAzimuth?:number;sunElevation?:number;lookTarget?:Vec3|null;onSetLookTarget?:(pos:Vec3|null)=>void;}){
  const meshRefs=useRef<Map<string,THREE.Object3D>>(new Map());const orbitRef=useRef<any>(null);const keys=useRef<Record<string,boolean>>({});useEffect(()=>{const s=()=>{if(orbitRef.current)orbitRef.current.enabled=false;};const e=()=>{if(orbitRef.current)orbitRef.current.enabled=true;};window.addEventListener('gizmo-drag-start',s);window.addEventListener('gizmo-drag-end',e);const kd=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=true;};const ku=(e:KeyboardEvent)=>{keys.current[e.key.toLowerCase()]=false;};window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);return()=>{window.removeEventListener('gizmo-drag-start',s);window.removeEventListener('gizmo-drag-end',e);window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);};},[]);const _wp=useRef({f:new THREE.Vector3(),r:new THREE.Vector3(),u:new THREE.Vector3(0,1,0),a:new THREE.Vector3(),z:new THREE.Vector3(),s:new THREE.Vector3(),d:new THREE.Vector3()});const _w=_wp.current;const vel=useRef(new THREE.Vector3());useFrame((_,delta)=>{const c=orbitRef.current;if(!c)return;const k=keys.current;const maxSpd=6*(c.target.distanceTo(c.object.position)*0.2+0.5);_w.f.set(0,0,0);c.object.getWorldDirection(_w.f);_w.f.y=0;_w.f.normalize();_w.r.crossVectors(_w.f,_w.u).normalize();_w.a.set(0,0,0);if(k.w)_w.a.add(_w.f);if(k.s)_w.a.sub(_w.f);if(k.d)_w.a.add(_w.r);if(k.a)_w.a.sub(_w.r);if(k.e){_w.a.y+=1;}if(k.q){_w.a.y-=1;}const v=vel.current;if(_w.a.length()>0){_w.a.normalize().multiplyScalar(maxSpd);v.lerp(_w.a,delta*4);}else{v.lerp(_w.z.set(0,0,0),delta*3);}if(v.length()>0.001){_w.s.copy(v).multiplyScalar(delta);c.object.position.add(_w.s);const dist=c.target.distanceTo(c.object.position);if(dist>25){const dir2=_w.d.copy(c.object.position).sub(c.target).normalize();c.object.position.copy(c.target).add(_w.d.multiplyScalar(25));}c.target.add(_w.s);c.update();}});
  return(<><CheckerGround/><ProcSky sunAzimuth={sunAzimuth||45} sunElevation={sunElevation||40}/><CloudLayer sunAzimuth={sunAzimuth||45} sunElevation={sunElevation||40}/><SunLight azimuth={sunAzimuth||45} elevation={sunElevation||40}/>    <mesh position={[0,-0.02,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[100,100]}/><meshBasicMaterial color="#000000" transparent opacity={0} side={THREE.DoubleSide} depthTest={false}/></mesh>
    {objects.map(obj=>{const sel=selectedId===obj.id;const bottomY=obj.type==='figure'||obj.type==='plane'?0:0.5;return(<group key={obj.id}>
      <group position={obj.position} rotation={obj.rotation} scale={obj.scale} ref={el=>{if(el){meshRefs.current.set(obj.id,el);if(obj.type==='camera'){const fwd=new THREE.Vector3(0,0,-1);el.localToWorld(fwd);window.dispatchEvent(new CustomEvent('cam-ready',{detail:{objRef:el,forward:[fwd.x,fwd.y,fwd.z]as Vec3}}));}}}} onClick={e=>{e.stopPropagation();if(e.ctrlKey&&onSetLookTarget){const pt=(e as any).point;if(pt){onSetLookTarget([pt.x,pt.y,pt.z]);return;}}onSelect(obj.id);if(obj.type==='figure')window.dispatchEvent(new CustomEvent('anim-model-selected',{detail:{id:obj.id}}));}}>
        {obj.type==='figure'?<LODFigure pos={obj.position} obj={obj}/>:
        obj.type==='camera'?<><mesh rotation={[-Math.PI/2,0,0]} position={[0,0.2,-0.6]}><cylinderGeometry args={[0.01,0.01,1,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6}/></mesh><mesh position={[0,0,-3]}><sphereGeometry args={[0.08,8,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.5}/></mesh><ErrorBoundary fallback={<FallbackCamera pos={[0,0,0]} tgt={[0,0,-3]}/>}><Suspense fallback={null}><CameraGLB pos={[0,0,0]} tgt={[0,0,-3]}/></Suspense></ErrorBoundary></>:
        <mesh>{obj.type==='box'&&<boxGeometry/>}{obj.type==='sphere'&&<sphereGeometry args={[0.5,28,28]}/>}{obj.type==='cylinder'&&<cylinderGeometry args={[0.5,0.5,1,24]}/>}{obj.type==='plane'&&<planeGeometry/>}<meshStandardMaterial color={obj.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>}
      </group>
      {sel&&<lineSegments position={obj.position} rotation={obj.rotation}><edgesGeometry args={[new THREE.BoxGeometry(0.6,0.6,0.6)]}/><lineBasicMaterial color="#60a0ff" opacity={0.8} transparent/></lineSegments>}
      {sel&&<mesh position={[obj.position[0],obj.position[1]-bottomY,obj.position[2]]}><sphereGeometry args={[0.2,12,12]}/><meshBasicMaterial color="#60a0ff" transparent opacity={0.7}/></mesh>}
      {sel&&gizmoMode==='rotate'&&<RotationGizmo center={[obj.position[0],obj.position[1]-bottomY,obj.position[2]]as Vec3} onRotate={(axis,dx,dy)=>{const el=meshRefs.current.get(obj.id);if(el){el.rotation[('xyz'[axis])as'x'|'y'|'z']+=(axis===0?dy*0.008:axis===1?dx*0.008:-dx*0.008);mover(el,obj);}}}/>}
      {sel&&gizmoMode==='translate'&&<TransformControls object={meshRefs.current.get(obj.id)||undefined} mode={gizmoMode==="scale"?"scale":"translate"} size={0.65} onObjectChange={()=>{const el=meshRefs.current.get(obj.id);if(el){const box=new THREE.Box3().setFromObject(el);const size=new THREE.Vector3();box.getSize(size);const bottomY=box.min.y-el.position.y;if(el.position.y+bottomY<0)el.position.y=-bottomY;if(rigActive&&obj.type==='camera'&&snapToTrack){const wp=new THREE.Vector3();el.getWorldPosition(wp);const s=snapToTrack(wp);if(s){el.position.copy(s);window.dispatchEvent(new CustomEvent('cam-track-snap',{detail:{worldPos:[s.x,s.y,s.z]}}));}}window.dispatchEvent(new CustomEvent('gizmo-drag-start'));mover(el,obj);}}} onMouseUp={()=>{window.dispatchEvent(new CustomEvent('gizmo-drag-end'));}}/>}
      {sel&&gizmoMode==='scale'&&<TransformControls object={meshRefs.current.get(obj.id)||undefined} mode="scale" size={0.65} onObjectChange={()=>{const el=meshRefs.current.get(obj.id);if(el){window.dispatchEvent(new CustomEvent('gizmo-drag-start'));mover(el,obj);}}} onMouseUp={()=>{window.dispatchEvent(new CustomEvent('gizmo-drag-end'));}}/>}
    </group>);})}
    {lookTarget&&<><mesh position={lookTarget}><ringGeometry args={[0.15,0.2,32]}/><meshBasicMaterial color="#ff4444" side={THREE.DoubleSide}/></mesh><mesh position={lookTarget}><ringGeometry args={[0.15,0.2,32]} rotation={[Math.PI/2,0,0]}/><meshBasicMaterial color="#ff4444" side={THREE.DoubleSide}/></mesh><mesh position={lookTarget}><sphereGeometry args={[0.08,8,8]}/><meshBasicMaterial color="#ff4444" transparent opacity={0.6}/></mesh></>}
    <OrbitControls ref={orbitRef} makeDefault enableDamping dampingFactor={0.08} minDistance={2} maxDistance={25} maxPolarAngle={Math.PI/2+0.2} target={lookTarget||[0,1,0]as Vec3} />
  </>);
});

function EBtn({label,active,onClick}:{label:string;active?:boolean;onClick:()=>void}){return<button onClick={onClick} style={{padding:'6px 10px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',border:active?'1px solid rgba(255,255,255,0.25)':'1px solid rgba(255,255,255,0.08)',background:active?'rgba(255,255,255,0.12)':'transparent',color:active?'#fff':'rgba(255,255,255,0.5)',whiteSpace:'nowrap',transition:'all 0.12s ease'}} onMouseEnter={e=>{e.currentTarget.style.background='rgba(255,255,255,0.1)';e.currentTarget.style.color='#fff';}} onMouseLeave={e=>{e.currentTarget.style.background=active?'rgba(255,255,255,0.12)':'transparent';e.currentTarget.style.color=active?'#fff':'rgba(255,255,255,0.5)';}}>{label}</button>;}

function PiPCam({camRef}:{camRef:React.MutableRefObject<THREE.Object3D|null>}){const{camera}=useThree();useFrame(()=>{const el=camRef.current;if(!el)return;camera.position.copy(el.position);camera.quaternion.copy(el.quaternion);});return null;}
function PiPFigure({obj}:{obj:SceneObject}){if(!obj.figureSrc)return null;const pipId=obj.id+'_pip';return obj.figureFmt==='fbx'?<FBXModel src={obj.figureSrc} objId={pipId}/>:<GLBModel src={obj.figureSrc} objId={pipId}/>;}
const farFlags=new Map<string,boolean>();let lastLODCheck=0;
function LODFigure({pos,obj}:{pos:Vec3;obj:SceneObject}){const{camera}=useThree();const[far,setFar]=useState(false);useFrame(()=>{const now=performance.now();if(now-lastLODCheck<200)return;lastLODCheck=now;const d=Math.sqrt(Math.pow(pos[0]-camera.position.x,2)+Math.pow(pos[2]-camera.position.z,2));const isFar=d>LOD_DIST;if(farFlags.get(obj.id)!==isFar){farFlags.set(obj.id,isFar);setFar(isFar);}});return far?<StickFigure poseId={obj.figurePose||'stand'} color={obj.color||'#c0c8d0'}/>:<SafeModel poseId={obj.figurePose||''} figureSrc={obj.figureSrc} fallback={<StickFigure poseId={obj.figurePose||'stand'} color={obj.color||'#c0c8d0'}/>} objId={obj.id} figureFmt={obj.figureFmt}/>;}


function DollyRails({rig,selCp,selCps,onSelCp,onMoveCp}:{rig:CameraRig;selCp:string|null;selCps?:Set<string>;onSelCp:(id:string|null,ctrl?:boolean)=>void;onMoveCp:(id:string,pos:Vec3)=>void}){if(!rig.dolly)return null;const{pointA,pointB}=rig.dolly;const dir=new THREE.Vector3(pointB[0]-pointA[0],pointB[1]-pointA[1],pointB[2]-pointA[2]);const len=dir.length();dir.normalize();const mid:Vec3=[(pointA[0]+pointB[0])/2,(pointA[1]+pointB[1])/2,(pointA[2]+pointB[2])/2];const aRef=useRef<THREE.Mesh>(null);const bRef=useRef<THREE.Mesh>(null);return<group><mesh position={[mid[0],mid[1]+0.05,mid[2]]} quaternion={new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),dir)}><cylinderGeometry args={[0.012,0.012,len,8]}/><meshStandardMaterial color="#999" roughness={0.4} metalness={0.9}/></mesh><mesh ref={aRef} position={pointA} onClick={e=>{e.stopPropagation();onSelCp('A',e.ctrlKey);}}><sphereGeometry args={[0.04,16,16]}/><meshStandardMaterial color={(selCp==='A'||selCps?.has('A'))?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp==='A'&&aRef.current&&<TransformControls object={aRef.current} mode="translate" size={0.4} onObjectChange={()=>{const p=aRef.current?.position;if(p)onMoveCp('A',[p.x,p.y,p.z]);}}/>}<mesh ref={bRef} position={pointB} onClick={e=>{e.stopPropagation();onSelCp('B',e.ctrlKey);}}><sphereGeometry args={[0.04,16,16]}/><meshStandardMaterial color={(selCp==='B'||selCps?.has('B'))?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp==='B'&&bRef.current&&<TransformControls object={bRef.current} mode="translate" size={0.35} onObjectChange={()=>{const p=bRef.current?.position;if(p)onMoveCp('B',[p.x,p.y,p.z]);}}/>}</group>;}

function CurvedTrackRails({rig,selCp,selCps,onSelCp,onMoveCp}:{rig:CameraRig;selCp:string|null;selCps?:Set<string>;onSelCp:(id:string|null,ctrl?:boolean)=>void;onMoveCp:(id:string,pos:Vec3)=>void}){if(!rig.curved||rig.curved.controlPoints.length<2)return null;const pts=rig.curved.controlPoints.map(p=>new THREE.Vector3(...p.position));const curve=new THREE.CatmullRomCurve3(pts);const tubeGeom=new THREE.TubeGeometry(curve,32,0.012,6,false);const cpRefs=useRef<Map<string,THREE.Mesh>>(new Map());return<group><mesh><primitive object={tubeGeom} attach="geometry"/><meshStandardMaterial color="#999" roughness={0.4} metalness={0.9}/></mesh>{rig.curved.controlPoints.map((cp,i)=>{const mesh=cpRefs.current.get(cp.id);return<group key={cp.id}><mesh ref={el=>{if(el)cpRefs.current.set(cp.id,el as any);}} position={cp.position} onClick={e=>{e.stopPropagation();onSelCp(cp.id,e.ctrlKey);}}><sphereGeometry args={[0.04,16,16]}/><meshStandardMaterial color={(selCp===cp.id||selCps?.has(cp.id))?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp===cp.id&&mesh&&<TransformControls object={mesh} mode="translate" size={0.4} onObjectChange={()=>{const p=mesh?.position;if(p)onMoveCp(cp.id,[p.x,p.y,p.z]);}}/>}</group>;})}</group>;}

function OrbitRing({rig,selCp,selCps,onSelCp,onMoveCp,gizmoMode}:{rig:CameraRig;selCp:string|null;selCps?:Set<string>;onSelCp:(id:string|null,ctrl?:boolean)=>void;onMoveCp:(id:string,pos:Vec3)=>void;gizmoMode:string}){if(!rig.orbit)return null;const{center,radius,height,startAngle,endAngle}=rig.orbit;const cps=rig.orbit.controlPoints||[{id:'o_cp0',position:[center[0]+radius,center[1]+height,center[2]]as Vec3}];const steps=64;const pts:THREE.Vector3[]=[];for(let i=0;i<=steps;i++){const a=startAngle+(endAngle-startAngle)*i/steps;pts.push(new THREE.Vector3(center[0]+Math.cos(a)*radius,center[1]+height,center[2]+Math.sin(a)*radius));}const curve=new THREE.CatmullRomCurve3(pts);const tubeGeom=new THREE.TubeGeometry(curve,64,0.015,8,false);const cpRefs=useRef<Map<string,THREE.Mesh>>(new Map());return<group><mesh><primitive object={tubeGeom} attach="geometry"/><meshStandardMaterial color="#999" roughness={0.4} metalness={0.9}/></mesh>{cps.map(cp=>{const mesh=cpRefs.current.get(cp.id);return<group key={cp.id}><mesh ref={el=>{if(el)cpRefs.current.set(cp.id,el as any);}} position={cp.position} onClick={e=>{e.stopPropagation();onSelCp(cp.id,e.ctrlKey);}}><sphereGeometry args={[0.06,16,16]}/><meshStandardMaterial color={(selCp===cp.id||selCps?.has(cp.id))?'#ffcc00':'#fff'} roughness={0.3}/></mesh>{selCp===cp.id&&mesh&&<TransformControls object={mesh} mode="translate" size={0.4} onObjectChange={()=>{const p=mesh?.position;if(!p)return;const cx=center[0],cy=center[1],cz=center[2];const d=Math.sqrt((p.x-cx)**2+(p.y-cy)**2+(p.z-cz)**2);const nr=d>0.3?d:0.3;const a=Math.atan2(p.z-cz,p.x-cx);const nx=cx+Math.cos(a)*nr,nz=cz+Math.sin(a)*nr;mesh.scale.set(1,1,1);mesh.position.set(nx,p.y,nz);if(gizmoMode==="scale"){setRig(prev=>{if(!prev?.orbit)return prev;return{...prev,orbit:{...prev.orbit,radius:nr,controlPoints:[{id:cp.id,position:[nx,p.y,nz]}]}}})}else{onMoveCp(cp.id,[nx,p.y,nz])}}}/>}</group>;})}</group>;}

function FullscreenEditor({objects,selectedId,setObjects,setSelectedId,onSnapshot,onClose,nodeId,rig,setRig}:{objects:SceneObject[];selectedId:string|null;setObjects:React.Dispatch<React.SetStateAction<SceneObject[]>>;setSelectedId:React.Dispatch<React.SetStateAction<string|null>>;onSnapshot:()=>void;onClose:()=>void;nodeId:string;rig:CameraRig|null;setRig:React.Dispatch<React.SetStateAction<CameraRig|null>>;}){
  const counter=useRef(Math.max(objects.length,1000));const[gizmoMode,setGizmoMode]=useState<GizmoMode>('translate');const[sunAz,setSunAz]=useState(45);const[sunEl,setSunEl]=useState(40);
  const undoStack=useRef<SceneObject[][]>([]);const redoStack=useRef<SceneObject[][]>([]);const dragSaved=useRef(false);
  const[showCam,setShowCam]=useState(false);const[vcamLens,setVcamLens]=useState('50');const[vcamAperture,setVcamAperture]=useState(2.8);
  const activeCamRef=useRef<THREE.Object3D|null>(null);const pipCanvasRef=useRef<HTMLDivElement>(null);  const lensData=LENSES[vcamLens];
  const[playing,setPlaying]=useState(false);const[playTime,setPlayTime]=useState(0);
  const playStartRef=useRef(0);const playFromRef=useRef(0);
  const animCamPos=useRef(new THREE.Vector3());
  const animCamLook=useRef(new THREE.Vector3(0,1,0));
  const camObjIdRef=useRef<string|null>(null);
  const[trackCpId,setTrackCpId]=useState<string|null>(null);
  const[trackCpIds,setTrackCpIds]=useState<Set<string>>(new Set());
  const onSelectCpMulti=useCallback((id:string,ctrl:boolean)=>{if(ctrl){setTrackCpIds(prev=>{const n=new Set(prev);if(n.has(id))n.delete(id);else n.add(id);return n;});}else{setTrackCpId(id);setTrackCpIds(new Set([id]));}},[setTrackCpId]);
  const[timelineH,setTimelineH]=useState(80);
  const[sunAzimuth,setSunAzimuth]=useState(45);const[sunElevation,setSunElevation]=useState(40);
  const[zoom,setZoom]=useState(60);
  const rigRef=useRef(rig);rigRef.current=rig;
  const[lookTarget,setLookTarget]=useState<Vec3|null>(null);const onSetLookTarget=useCallback((pos:Vec3|null)=>{setLookTarget(pos);if(!pos)setTrackCpId(null);},[]);
  const[activeAnimModel,setActiveAnimModel]=useState<string|null>(null);
  const lookTargetRef=useRef<THREE.Mesh>(null);
  const _pool=useRef({cv:new THREE.Vector3(),cv2:new THREE.Vector3(),cv3:new THREE.Vector3(),camRes:{pos:new THREE.Vector3(),look:new THREE.Vector3(),pitch:0 as number|undefined,yaw:0 as number|undefined},lastCurve:null as THREE.CatmullRomCurve3|null,lastCurveKey:''});const{current:P}=_pool;
  const snapToTrack=useCallback((pos:THREE.Vector3):THREE.Vector3|null=>{
    const r=rigRef.current;if(!r)return null;
    if(r.type==='dolly'&&r.dolly){const A=new THREE.Vector3(...r.dolly.pointA);const B=new THREE.Vector3(...r.dolly.pointB);const dir=B.clone().sub(A);const len=dir.length();if(len<0.001)return A.clone().add(new THREE.Vector3(0,0.13,0));dir.normalize();const t=Math.max(0,Math.min(1,pos.clone().sub(A).dot(dir)/len));const pt=A.clone().add(dir.clone().multiplyScalar(t*len));pt.y+=0.13;return pt;}
    if(r.type==='curved'&&r.curved&&r.curved.controlPoints.length>=2){const pts=r.curved.controlPoints.map(p=>new THREE.Vector3(...p.position));const curve=new THREE.CatmullRomCurve3(pts);let best=Infinity;const r2=new THREE.Vector3();for(let i=0;i<=100;i++){const pt=curve.getPointAt(i/100);const d=pos.distanceToSquared(pt);if(d<best){best=d;r2.copy(pt);}}r2.y+=0.13;return r2;}
    if(r.type==='orbit'&&r.orbit){const{center,radius,height}=r.orbit;P.cv.set(...center);P.cv3.set(center[0]+Math.cos(0)*radius,center[1]+height,center[2]+Math.sin(0)*radius);const dx=pos.x-P.cv.x;const dz=pos.z-P.cv.z;const a=Math.atan2(dz,dx);return P.cv2.set(P.cv.x+Math.cos(a)*radius,P.cv.y+height+0.13,P.cv.z+Math.sin(a)*radius);}
    return null;
  },[]);
  const getTrackCamera=useCallback((prog:number):any=>{
    const r=rigRef.current;if(!r)return null;
    const sc=r.speedCurve.sort((a,b)=>a.time-b.time);
    let sp=1;const targetTime=prog*r.duration;
    if(sc.length>=2){let i0=0;for(let i=1;i<sc.length;i++){if(sc[i].time<=targetTime)i0=i;else break;}let i1=Math.min(i0+1,sc.length-1);const st=sc[i1].time>sc[i0].time?(targetTime-sc[i0].time)/(sc[i1].time-sc[i0].time):0;sp=sc[i0].speed+(sc[i1].speed-sc[i0].speed)*st;}
    else if(sc.length===1)sp=sc[0].speed;
    const pp=Math.max(0,Math.min(1,prog*sp));
    let pitch:number|undefined,yaw:number|undefined;const rk=r.rotationKeys.sort((a,b)=>a.time-b.time);
    if(rk.length>=2){const tt=pp*r.duration;let i0=0;for(let i=1;i<rk.length;i++){if(rk[i].time<=tt)i0=i;else break;}let i1=Math.min(i0+1,rk.length-1);const st=rk[i1].time>rk[i0].time?(tt-rk[i0].time)/(rk[i1].time-rk[i0].time):0;pitch=rk[i0].pitch+(rk[i1].pitch-rk[i0].pitch)*st;yaw=rk[i0].yaw+(rk[i1].yaw-rk[i0].yaw)*st;}
    else if(rk.length===1){pitch=rk[0].pitch;yaw=rk[0].yaw;}
    if(r.type==='dolly'&&r.dolly){P.cv.set(...r.dolly.pointA);P.cv2.set(...r.dolly.pointB);P.cv3.copy(P.cv).lerp(P.cv2,pp);P.cv3.y+=0.13;P.camRes.pos.copy(P.cv3);P.camRes.pitch=pitch;P.camRes.yaw=yaw;return P.camRes;}
    if(r.type==='curved'&&r.curved&&r.curved.controlPoints.length>=2){const ck=JSON.stringify(r.curved.controlPoints.map(cp=>cp.position));if(ck!==P.lastCurveKey){P.lastCurve=new THREE.CatmullRomCurve3(r.curved.controlPoints.map(p=>new THREE.Vector3(...p.position)));P.lastCurveKey=ck;}P.lastCurve!.getPointAt(pp,P.cv3);P.lastCurve!.getTangentAt(pp,P.cv);P.cv.copy(P.cv3).add(P.cv);P.camRes.pos.copy(P.cv3);P.camRes.pitch=pitch;P.camRes.yaw=yaw;return P.camRes;}
    if(r.type==='orbit'&&r.orbit){const{center,radius,height,startAngle,endAngle}=r.orbit;P.cv.set(...center);P.cv2.set(P.cv.x+Math.cos(startAngle+(endAngle-startAngle)*pp)*radius,P.cv.y+height+0.13,P.cv.z+Math.sin(startAngle+(endAngle-startAngle)*pp)*radius);P.camRes.pos.copy(P.cv2);P.camRes.pitch=pitch;P.camRes.yaw=yaw;return P.camRes;}
    return null;
  },[]);
  const playTimeRef=useRef(0);
  useEffect(()=>{playTimeRef.current=playTime;},[playTime]);
  const camObjRef=useRef(objects.find(o=>o.type==='camera'));useEffect(()=>{camObjRef.current=objects.find(o=>o.type==='camera');},[objects]);useEffect(()=>{if(!playing||!rig)return;const camObj=camObjRef.current;camObjIdRef.current=camObj?.id||null;const startTime=performance.now();const startPlay=playTimeRef.current;let raf:number;let lastTick=0;const loop=(now:number)=>{const elapsed=(now-startTime)/1000;const raw=(startPlay+elapsed)/rig.duration;const t=Math.min(1,raw);const p=t<0.01?0:t>0.99?1:t*t*(3-2*t);playTimeRef.current=p*rig.duration;if(now-lastTick>500){lastTick=now;setPlayTime(p*rig.duration);}if(p>=1){setPlaying(false);setPlayTime(rig.duration);}const cam=getTrackCamera(p);if(cam){animCamPos.current.copy(cam.pos);animCamLook.current.copy(cam.look);if(camObjIdRef.current&&activeCamRef.current){activeCamRef.current.position.copy(cam.pos);if(lookTarget){const m=new THREE.Matrix4().lookAt(activeCamRef.current.position,new THREE.Vector3(...lookTarget),new THREE.Vector3(0,1,0));activeCamRef.current.quaternion.setFromRotationMatrix(m);}else if(cam.pitch!==undefined)activeCamRef.current.rotation.set(cam.pitch,cam.yaw,0);const cid=camObjIdRef.current;}}if(p<1)raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf);},[playing,rig,getTrackCamera,lookTarget]);
  useEffect(()=>{if(playing||!rig)return;const r=rigRef.current;if(!r)return;const p=playTime/Math.max(0.1,r.duration);const cam=getTrackCamera(Math.min(1,p));if(cam){animCamPos.current.copy(cam.pos);animCamLook.current.copy(cam.look);if(activeCamRef.current){activeCamRef.current.position.copy(cam.pos);if(lookTarget){const m=new THREE.Matrix4().lookAt(activeCamRef.current.position,new THREE.Vector3(...lookTarget),new THREE.Vector3(0,1,0));activeCamRef.current.quaternion.setFromRotationMatrix(m);}}}},[playTime,playing,getTrackCamera,lookTarget]);

  const pushUndo=useCallback((snap:SceneObject[])=>{undoStack.current.push(snap);if(undoStack.current.length>60)undoStack.current.shift();redoStack.current=[];},[]);
  const doUndo=useCallback(()=>{const prev=undoStack.current.pop();if(!prev)return;redoStack.current.push(objects);setObjects(prev);},[objects]);
  const doRedo=useCallback(()=>{const next=redoStack.current.pop();if(!next)return;undoStack.current.push(objects);setObjects(next);},[objects]);
  useEffect(()=>{const h=()=>{if(!dragSaved.current){pushUndo(objects);dragSaved.current=true;}};window.addEventListener('gizmo-drag-start',h);return()=>window.removeEventListener('gizmo-drag-start',h);},[objects,pushUndo]);
  useEffect(()=>{const h=()=>{dragSaved.current=false;const r=(window as any).__dragObj;if(r&&selectedId){const el=r.el;const p:Vec3=[el.position.x,el.position.y,el.position.z];const rot:Vec3=[el.rotation.x,el.rotation.y,el.rotation.z];const scl:Vec3=[el.scale.x,el.scale.y,el.scale.z];setObjects(prev=>prev.map(o=>o.id===selectedId?{...o,position:p,rotation:rot,scale:scl}:o));}};window.addEventListener('gizmo-drag-end',h);return()=>window.removeEventListener('gizmo-drag-end',h);},[selectedId]);
  useEffect(()=>{initPoseRegistry();},[]);
  useEffect(()=>{const h=(e:Event)=>{const{id,objRef}=(e as CustomEvent).detail as{id:string;objRef?:THREE.Object3D};if(objRef){const box=new THREE.Box3().setFromObject(objRef);const bottom=box.min.y-objRef.position.y;if(objRef.position.y+bottom<0)objRef.position.y=-bottom;}if(objRef&&(objRef as any).type==='camera'){activeCamRef.current=objRef;if(rig&&!playing){const wp=new THREE.Vector3();objRef.getWorldPosition(wp);const dur=rig.duration;let bestT=0,bestD=Infinity;for(let i=0;i<=100;i++){const t=i/100;const c=getTrackCamera(t);if(c){const d=wp.distanceToSquared(c.pos);if(d<bestD){bestD=d;bestT=t;}}}setPlayTime(bestT*dur);}}};window.addEventListener('scene3d-object-moved',h);return()=>window.removeEventListener('scene3d-object-moved',h);},[rig,playing,getTrackCamera]);
  useEffect(()=>{const h=(e:Event)=>{const{id}=(e as CustomEvent).detail as{id:string};setActiveAnimModel(id);};window.addEventListener('anim-model-selected',h);return()=>window.removeEventListener('anim-model-selected',h);},[]);
  useEffect(()=>{const h=(e:Event)=>{const{objRef}=(e as CustomEvent).detail as{objRef:THREE.Object3D};if(objRef)activeCamRef.current=objRef;};window.addEventListener('cam-ready',h);return()=>window.removeEventListener('cam-ready',h);},[]);
  useEffect(()=>{const h=(e:Event)=>{const wp=(e as CustomEvent).detail.worldPos as number[];if(!rig||playing)return;const dur=rig.duration;let bt=0,bd=Infinity;for(let i=0;i<=100;i++){const t=i/100;const c=getTrackCamera(t);if(c){const d=Math.pow(wp[0]-c.pos.x,2)+Math.pow(wp[1]-c.pos.y,2)+Math.pow(wp[2]-c.pos.z,2);if(d<bd){bd=d;bt=t;}}}setPlayTime(bt*dur);};window.addEventListener('cam-track-snap',h);return()=>window.removeEventListener('cam-track-snap',h);},[rig,playing,getTrackCamera]);

  const addObj=useCallback((type:SceneObject['type'])=>{_oid++;const y=type==='figure'||type==='plane'?0:0.5;const first=poseRegistry.size>0?poseRegistry.keys().next().value as string:'stand1';const obj:SceneObject={id:`o_${_oid}`,type,position:[0,y,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:type==='figure'?first:undefined,figureSrc:type==='figure'?poseRegistry.get(first)?.src:undefined,figureFmt:type==='figure'?poseRegistry.get(first)?.format:undefined};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);},[setObjects,setSelectedId,objects,pushUndo]);
    const makeRig=(type:TrackType)=>{const cam=objects.find(o=>o.type==='camera');if(!cam)return;const py=cam.position[1],px=cam.position[0],pz=cam.position[2];if(type==='dolly')setRig({type:'dolly',duration:15,speedCurve:[{time:0,speed:1},{time:15,speed:1}],rotationKeys:[],animTracks:[],dolly:{pointA:[px+4,py,pz],pointB:[px-4,py,pz]}});if(type==='curved')setRig({type:'curved',duration:15,speedCurve:[{time:0,speed:1},{time:15,speed:1}],rotationKeys:[],animTracks:[],curved:{controlPoints:[{id:'c0',position:[px+4,py,pz]},{id:'c1',position:[px,py,pz+3]},{id:'c2',position:[px-4,py,pz]}]}});if(type==='orbit')setRig({type:'orbit',duration:15,speedCurve:[{time:0,speed:1},{time:15,speed:1}],rotationKeys:[],animTracks:[],orbit:{center:[px,py,pz-3],radius:4,height:0,startAngle:0,endAngle:Math.PI*2,controlPoints:[{id:'o_cp0',position:[px+4,py,pz-3]as Vec3}]}});setTimeout(()=>{const start=getTrackCamera(0);if(start&&cam&&activeCamRef.current){activeCamRef.current.position.copy(start.pos);setObjects(prev=>prev.map(o=>o.id===cam.id?{...o,position:[start.pos.x,start.pos.y,start.pos.z]as Vec3}:o));}},50);setSelectedId(cam.id);};
  const addCamera=useCallback(()=>{_oid++;const obj:SceneObject={id:`o_${_oid}`,type:'camera',position:[8,2,5],rotation:[0,0,0],scale:[1,1,1]};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);},[setObjects,setSelectedId,objects,pushUndo]);
  const updatePose=useCallback((pose:string)=>{const e=poseRegistry.get(pose);setObjects(prev=>prev.map(o=>o.id===selectedId&&o.type==='figure'?{...o,figurePose:pose,figureSrc:e?.src}:o));},[selectedId,setObjects]);
  const selObj=objects.find(o=>o.id===selectedId);

  useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.ctrlKey&&e.key==='z'){e.preventDefault();doUndo();return;}if(e.ctrlKey&&(e.key==='y'||(e.shiftKey&&e.key==='z'))){e.preventDefault();doRedo();return;}if(e.ctrlKey&&e.key==='c'&&selectedId){e.preventDefault();const obj=objects.find(o=>o.id===selectedId);if(obj){(window as any).__copiedObj=obj;}}if(e.ctrlKey&&e.key==='v'&&(window as any).__copiedObj){e.preventDefault();const src=(window as any).__copiedObj;_oid++;const clone:SceneObject={...src,id:`o_${_oid}`,position:[src.position[0]+2,src.position[1],src.position[2]+2]as Vec3};pushUndo(objects);setObjects(prev=>[...prev,clone]);setSelectedId(clone.id);}if(e.key===' '&&rig){e.preventDefault();if(playing){setPlaying(false);}else{if(playTime>=rig.duration)setPlayTime(0);setPlaying(true);}return;}if(e.key==='Enter'){e.preventDefault();setPlaying(false);setPlayTime(0);const cam2=getTrackCamera(0);if(cam2&&activeCamRef.current){activeCamRef.current.position.copy(cam2.pos);if(cam2.pitch!==undefined)activeCamRef.current.rotation.set(cam2.pitch,cam2.yaw,0);}return;}if(e.key==='Tab'){e.preventDefault();setGizmoMode(prev=>prev==='translate'?'rotate':prev==='rotate'?'scale':'translate');return;}if(e.key==='Escape'){if(selectedId)setSelectedId(null);else onClose();}if((e.key==='Delete'||e.key==='Backspace')&&selectedId){e.preventDefault();e.stopPropagation();pushUndo(objects);setObjects(prev=>prev.filter(o=>o.id!==selectedId));setSelectedId(null);}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h);},[doUndo,doRedo,selectedId,objects,playing,playTime,rig,getTrackCamera,onClose,setPlaying,setPlayTime,setGizmoMode]);

  return createPortal(<div tabIndex={-1} ref={el=>el?.focus()} data-3d-editor style={{position:'fixed',inset:0,zIndex:99999,outline:'none',background:'#3a3a3a',display:'flex',flexDirection:'column'}}>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'8px 14px',background:'rgba(0,0,0,0.3)',flexShrink:0}}><span style={{fontSize:14,fontWeight:600,color:'#ccc'}}>3D 场景编辑器</span><div style={{display:'flex',gap:8}}><EBtn label="截图" onClick={onSnapshot}/><EBtn label="导出" onClick={()=>{const blob=new Blob([JSON.stringify(objects,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='3d-scene-'+new Date().toISOString().slice(0,10)+'.json';a.click();}}/><EBtn label="导入" onClick={()=>{const inp=document.createElement('input');inp.type='file';inp.accept='.json';inp.onchange=()=>{const f=inp.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result as string);if(Array.isArray(data)){pushUndo(objects);setObjects(data);setSelectedId(null);}}catch{}};r.readAsText(f);};inp.click();}}/><button onClick={onClose} style={{padding:'6px 16px',background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:8,color:'#ccc',cursor:'pointer',fontSize:13}}>退出</button></div></div>
    <div style={{flex:1,display:'flex',minHeight:0}}>
      <div style={{width:90,display:'flex',flexDirection:'column',gap:5,padding:'10px 7px',borderRight:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0,alignItems:'center',background:'rgba(0,0,0,0.2)'}}>
        <div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>几何体</div><EBtn label="立方体" onClick={()=>addObj('box')}/><EBtn label="球体" onClick={()=>addObj('sphere')}/><EBtn label="圆柱" onClick={()=>addObj('cylinder')}/><EBtn label="平面" onClick={()=>addObj('plane')}/>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>人物</div><EBtn label="添加人物" onClick={()=>addObj('figure')}/>
        {selObj?.type==='figure'&&<select value={selObj.figurePose||''} onChange={e=>updatePose(e.target.value)} style={{marginTop:4,width:'100%',padding:5,background:'rgba(0,0,0,0.15)',border:'1px solid rgba(255,255,255,0.08)',borderRadius:8,color:'#ccc',fontSize:10,cursor:'pointer'}}>{[...poseRegistry.entries()].map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select>}{selObj?.type==='figure'&&selObj.figureSrc&&<AutoRigButton figureSrc={selObj.figureSrc} figureFmt={selObj.figureFmt||'glb'} onRigged={(url:string)=>{setObjects(prev=>prev.map(o=>o.id===selectedId?{const pose=poseRegistry.get(o.figurePose||'');if(pose){pose.format='glb';pose.src=url;}return{...o,figureSrc:url,figureFmt:'glb'};}:o));}}/>}
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>摄像</div><EBtn label="加摄像机" onClick={addCamera}/><EBtn label={showCam?'关取景器':'开取景器'} onClick={()=>setShowCam(!showCam)} active={showCam}/>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>光照</div><div style={{display:'flex',alignItems:'center',gap:3,marginBottom:2}}><span style={{fontSize:8,color:'rgba(255,255,255,0.35)',width:28}}>方位</span><input type="range" min={0} max={360} value={sunAzimuth} onChange={e=>setSunAzimuth(Number(e.target.value))} style={{flex:1,height:3,cursor:'pointer'}}/><span style={{fontSize:8,color:'rgba(255,255,255,0.5)',width:24}}>{sunAzimuth}°</span></div><div style={{display:'flex',alignItems:'center',gap:3,marginBottom:2}}><span style={{fontSize:8,color:'rgba(255,255,255,0.35)',width:28}}>仰角</span><input type="range" min={0} max={90} value={sunElevation} onChange={e=>setSunElevation(Number(e.target.value))} style={{flex:1,height:3,cursor:'pointer'}}/><span style={{fontSize:8,color:'rgba(255,255,255,0.5)',width:24}}>{sunElevation}°</span></div>
        <div style={{width:'70%',height:1,background:'rgba(255,255,255,0.06)',margin:'6px 0'}}/><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:2}}>轨道</div><EBtn label='直线推轨' active={rig?.type==='dolly'} onClick={()=>makeRig('dolly')}/><EBtn label='曲线轨道' active={rig?.type==='curved'} onClick={()=>makeRig('curved')}/><EBtn label='环绕轨道' active={rig?.type==='orbit'} onClick={()=>makeRig('orbit')}/>{rig&&(rig.type==='curved'||rig.type==='orbit')&&<EBtn label='+控制点' onClick={()=>{setRig(prev=>{if(!prev)return prev;const getCPs=()=>{if(prev.type==='curved'&&prev.curved)return prev.curved.controlPoints;if(prev.type==='orbit'&&prev.orbit){const{center,radius,height,startAngle,endAngle}=prev.orbit;const angle=startAngle+(endAngle-startAngle)*0.5;return[{id:'cp_'+Date.now(),position:[center[0]+Math.cos(angle)*radius,center[1]+height,center[2]+Math.sin(angle)*radius]as Vec3}];}return[];};const cps=getCPs();if(prev.type==='curved'&&prev.curved&&prev.curved.controlPoints.length>=2){const last=prev.curved.controlPoints[prev.curved.controlPoints.length-1];const mid:Vec3=[(last.position[0]+prev.curved.controlPoints[0].position[0])/2,last.position[1],(last.position[2]+prev.curved.controlPoints[0].position[2])/2];const newCp={id:'cp_'+Date.now(),position:mid};return{...prev,curved:{...prev.curved,controlPoints:[...prev.curved.controlPoints.slice(0,-1),newCp,last]}};}return prev;});}}/>}{rig&&<EBtn label='清除轨道' onClick={()=>setRig(null)}/>}
      </div>
      <div style={{flex:1,minWidth:0,position:'relative'}} onDragOver={e=>{e.preventDefault();e.stopPropagation();}} onDrop={e=>{e.preventDefault();e.stopPropagation();const f=e.dataTransfer.files[0];if(!f||!f.name.match(/\.(glb|fbx)$/i))return;importFile(f,(entry,poseId)=>{_oid++;const obj:SceneObject={id:`o_${_oid}`,type:'figure',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:poseId,figureSrc:entry.src,figureFmt:entry.format};pushUndo(objects);setObjects(prev=>[...prev,obj]);setSelectedId(obj.id);});}}>
        <Canvas shadows="soft" camera={{position:[5,4,7],fov:50,near:0.1,far:100}} gl={{preserveDrawingBuffer:true,antialias:false,powerPreference:'high-performance'}} dpr={[0.5,1.5]} style={{width:'100%',height:'100%'}}><AnimationSync time={playTime} active={playing} rig={rig}/><SceneContent objects={objects} selectedId={selectedId} onSelect={setSelectedId} gizmoMode={gizmoMode} rigActive={!!rig} snapToTrack={snapToTrack} sunAzimuth={sunAz} sunElevation={sunEl} lookTarget={lookTarget} onSetLookTarget={onSetLookTarget}/>{rig?.type==='dolly'&&<DollyRails rig={rig} selCp={trackCpId} selCps={trackCpIds} onSelCp={onSelectCpMulti} onMoveCp={(id,pos)=>{setRig(prev=>{if(!prev||!prev.dolly)return prev;const oldA=prev.dolly.pointA;const oldB=prev.dolly.pointB;const oldPos=id==='A'?oldA:oldB;const dx=pos[0]-oldPos[0];const dy=pos[1]-oldPos[1];const dz=pos[2]-oldPos[2];let newA=oldA;let newB=oldB;if(id==='A')newA=pos;else newB=pos;if(trackCpIds.size>1){if(trackCpIds.has('A')&&id!=='A')newA=[oldA[0]+dx,oldA[1]+dy,oldA[2]+dz]as Vec3;if(trackCpIds.has('B')&&id!=='B')newB=[oldB[0]+dx,oldB[1]+dy,oldB[2]+dz]as Vec3;}return{...prev,dolly:{...prev.dolly,pointA:newA,pointB:newB}};});}}/>}{rig?.type==='curved'&&<CurvedTrackRails rig={rig} selCp={trackCpId} selCps={trackCpIds} onSelCp={onSelectCpMulti} onMoveCp={(id,pos)=>{setRig(prev=>{if(!prev?.curved)return prev;const oldCp=prev.curved.controlPoints.find(cp=>cp.id===id);if(!oldCp)return prev;const dx=pos[0]-oldCp.position[0];const dy=pos[1]-oldCp.position[1];const dz=pos[2]-oldCp.position[2];const cps=prev.curved.controlPoints.map(cp=>{if(cp.id===id)return{...cp,position:pos};if(trackCpIds.has(cp.id))return{...cp,position:[cp.position[0]+dx,cp.position[1]+dy,cp.position[2]+dz]as Vec3};return cp;});return{...prev,curved:{...prev.curved,controlPoints:cps}};});}}/>}{rig?.type==='orbit'&&<OrbitRing rig={rig} selCp={trackCpId} selCps={trackCpIds} onSelCp={onSelectCpMulti} onMoveCp={(id,pos)=>{setRig(prev=>{if(!prev?.orbit)return prev;const cps=prev.orbit.controlPoints||[{id:'o_cp0',position:prev.orbit.center as Vec3}];const ocp=cps.find(cp=>cp.id===id);if(!ocp)return prev;const dcx=pos[0]-(prev.orbit.center[0]+(ocp.position[0]-prev.orbit.center[0]));const dcy=pos[1]-(prev.orbit.center[1]+(ocp.position[1]-prev.orbit.center[1]));const dcz=pos[2]-(prev.orbit.center[2]+(ocp.position[2]-prev.orbit.center[2]));const ncx=prev.orbit.center[0]+dcx,ncy=prev.orbit.center[1]+dcy,ncz=prev.orbit.center[2]+dcz;return{...prev,orbit:{...prev.orbit,center:[ncx,ncy,ncz]as Vec3,controlPoints:cps.map(cp=>({...cp,position:[cp.position[0]+dcx,cp.position[1]+dcy,cp.position[2]+dcz]as Vec3}))}};});}} gizmoMode={gizmoMode}/>}</Canvas>
      </div>
      <div style={{width:160,padding:'10px',borderLeft:'1px solid rgba(255,255,255,0.06)',overflowY:'auto',flexShrink:0,background:'rgba(0,0,0,0.15)'}}><div style={{fontSize:9,color:'rgba(255,255,255,0.25)',textTransform:'uppercase',letterSpacing:'0.05em',marginBottom:8}}>属性</div>
        {selObj?<div style={{display:'flex',flexDirection:'column',gap:8}}>
          <div style={{fontSize:12,color:'rgba(255,255,255,0.55)'}}>类型:<span style={{color:'#ccc'}}>{selObj.type==='box'?'立方体':selObj.type==='sphere'?'球体':selObj.type==='cylinder'?'圆柱':selObj.type==='plane'?'平面':selObj.type==='camera'?'摄像机':'人物'}</span></div>
          {selObj.type==='figure'&&<div style={{fontSize:12,color:'rgba(255,255,255,0.55)'}}>姿态:<span style={{color:'#ccc'}}>{poseRegistry.get(selObj.figurePose||'')?.name||selObj.figurePose}</span></div>}
          <div style={{display:'flex',gap:4}}><button onClick={()=>setGizmoMode('translate')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='translate'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='translate'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='translate'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>移动</button><button onClick={()=>setGizmoMode('rotate')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='rotate'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='rotate'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='rotate'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>旋转</button><button onClick={()=>setGizmoMode('scale')} style={{flex:1,padding:'6px 4px',borderRadius:6,fontSize:11,fontWeight:500,cursor:'pointer',background:gizmoMode==='scale'?'rgba(100,140,255,0.2)':'rgba(255,255,255,0.04)',border:gizmoMode==='scale'?'1px solid rgba(100,140,255,0.3)':'1px solid rgba(255,255,255,0.06)',color:gizmoMode==='scale'?'#a0c0ff':'rgba(255,255,255,0.4)'}}>缩放</button></div>
          <div style={{fontSize:11,color:'rgba(255,255,255,0.55)'}}>位置<br/><span style={{color:'#ccc',fontSize:10}}>X:{selObj.position[0].toFixed(1)} Y:{selObj.position[1].toFixed(1)} Z:{selObj.position[2].toFixed(1)}</span></div>
          <button onClick={()=>{pushUndo(objects);setObjects(prev=>prev.map(o=>o.id===selectedId?{...o,position:[0,o.type==='figure'||o.type==='plane'?0:0.5,0]as Vec3,rotation:[0,0,0]as Vec3}:o));}} style={{padding:6,borderRadius:6,fontSize:10,cursor:'pointer',background:'rgba(200,160,0,0.08)',border:'1px solid rgba(200,160,0,0.2)',color:'#886600',width:'100%'}}>复位</button>
          <button onClick={()=>{pushUndo(objects);setObjects(prev=>prev.filter(o=>o.id!==selectedId));setSelectedId(null);}} style={{padding:7,background:'rgba(200,60,60,0.08)',border:'1px solid rgba(200,60,60,0.2)',borderRadius:8,color:'#664444',fontSize:11,cursor:'pointer',width:'100%'}}>删除</button>
        </div>:<div style={{fontSize:10,color:'rgba(255,255,255,0.2)',lineHeight:1.6}}>点击物体选中<br/>拖GLB导入<br/>右键旋转视角<br/>Esc取消选中<br/>Del删除选中</div>}
      </div>
    </div>
    {showCam&&<div style={{position:'absolute',bottom:timelineH+10,right:16,zIndex:102,width:680,background:'#111',borderRadius:12,overflow:'hidden',border:'2px solid #333',boxShadow:'0 0 20px rgba(0,0,0,0.5)'}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'4px 8px',background:'#1a1a1a',gap:4}}><span style={{fontSize:10,color:'#e44',fontWeight:600}}>● REC</span><select value={vcamLens} onChange={e=>setVcamLens(e.target.value)} style={{background:'#222',border:'1px solid #444',borderRadius:4,color:'#ccc',fontSize:10,padding:'2px 4px'}}>{Object.entries(LENSES).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select><select value={vcamAperture} onChange={e=>setVcamAperture(Number(e.target.value))} style={{background:'#222',border:'1px solid #444',borderRadius:4,color:'#ccc',fontSize:10,padding:'2px 4px'}}>{[1.3,1.4,2,2.8,4,5.6,8,11,16,22].map(v=><option key={v} value={v}>T{v}</option>)}</select><button onClick={()=>{const c=pipCanvasRef.current?.querySelector('canvas');if(!c)return;const u=c.toDataURL('image/png');const s=useCanvasStore.getState();const cn=s.nodes.get(nodeId);const nx=(cn?.pos?.x||0)+540;const ny=cn?.pos?.y||0;const nid=s.addNode('image.generate',{x:nx,y:ny},'PiP '+vcamLens+' T'+vcamAperture);s.updateNode(nid,{meta:{gen:{imageUrl:u,prompt:'',model:'GPT Image2',aspect:'16:9',resolution:'2K',quality:'high',resultAssetIds:[]}}});s.triggerSync();}} style={{background:'#c44',border:'1px solid #e66',borderRadius:4,color:'#fff',fontSize:10,padding:'2px 8px',cursor:'pointer',fontWeight:600}}>📸</button>
      <button onClick={()=>{if(!rig||!pipCanvasRef.current)return;const c=pipCanvasRef.current.querySelector('canvas');if(!c)return;const stream=c.captureStream(30);const mr=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm',videoBitsPerSecond:8000000});const chunks:Blob[]=[];mr.ondataavailable=e=>{if(e.data.size>0)chunks.push(e.data);};mr.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='direx_'+new Date().toISOString().slice(0,19).replace(/:/g,'-')+'.webm';a.click();const reader=new FileReader();reader.onload=()=>{const dataUrl=reader.result as string;const s2=useCanvasStore.getState();const cn2=s2.nodes.get(nodeId);const nx2=(cn2?.pos?.x||0)+600;const ny2=cn2?.pos?.y||0;const nid2=s2.addNode('image.generate',{x:nx2,y:ny2},'DireX '+vcamLens+' T'+vcamAperture);s2.updateNode(nid2,{meta:{gen:{imageUrl:dataUrl,prompt:'',model:'Video',aspect:'16:9',resolution:'1080P',quality:'high',resultAssetIds:[],videoUrl:dataUrl}}});s2.triggerSync();};reader.readAsDataURL(blob);};mr.start();setPlayTime(0);setPlaying(true);const check=setInterval(()=>{if(!rigRef.current)return;if(playTimeRef.current>=rigRef.current.duration-0.1){mr.stop();clearInterval(check);setPlaying(false);}},200);}} style={{background:'#e44',border:'1px solid #f66',borderRadius:4,color:'#fff',fontSize:10,padding:'2px 8px',cursor:'pointer',fontWeight:600}}>⏺ 录制</button><span style={{fontSize:9,color:'#888'}}>ARRI S35</span></div>
      <div ref={pipCanvasRef} style={{position:'relative',width:'100%',height:380}}>
        <Canvas key={vcamLens} camera={{position:[0,0,0],fov:lensData.fov,near:0.1,far:100}} gl={{antialias:true,preserveDrawingBuffer:true}} style={{width:'100%',height:'100%'}}>
          <CheckerGround/><ProcSky sunAzimuth={sunAz} sunElevation={sunEl}/><CloudLayer sunAzimuth={sunAz} sunElevation={sunEl}/><SunLight azimuth={sunAz} elevation={sunEl}/><PiPCam camRef={activeCamRef}/>
          {objects.map(o=><group key={o.id} position={o.position} rotation={o.rotation} scale={o.scale}>{o.type==='figure'?<PiPFigure obj={o}/>:o.type==='box'?<mesh><boxGeometry/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:o.type==='sphere'?<mesh><sphereGeometry args={[0.5,16,16]}/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:o.type==='cylinder'?<mesh><cylinderGeometry args={[0.5,0.5,1,16]}/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:o.type==='plane'?<mesh><planeGeometry/><meshStandardMaterial color={o.color||'#8899aa'} roughness={0.35} metalness={0.25}/></mesh>:null}</group>)}
        </Canvas>
        <div style={{position:'absolute',inset:0,pointerEvents:'none',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:'80%',height:'80%',border:'1px solid rgba(255,255,255,0.3)'}}/></div>
      </div>
    </div>}
        {rig&&<div style={{position:'absolute',bottom:0,left:0,right:0,zIndex:101,background:'rgba(0,0,0,0.85)',borderTop:'1px solid rgba(255,255,255,0.1)',padding:'6px 14px',height:Math.max(timelineH,80+rig.animTracks.length*24),overflow:'hidden'}}>
      <div style={{position:'absolute',top:-3,left:'50%',transform:'translateX(-50%)',width:40,height:6,background:'rgba(255,255,255,0.3)',borderRadius:3,cursor:'ns-resize',zIndex:102}}
        onMouseDown={e=>{e.preventDefault();const sY=e.clientY,sH=timelineH;const mv=(me)=>{setTimelineH(Math.max(60,Math.min(300,sH+(sY-me.clientY))));};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}/>
      <div style={{display:'flex',alignItems:'center',gap:6,marginBottom:4}}>
        <button onClick={()=>{if(playing)setPlaying(false);else{if(playTime>=rig.duration)setPlayTime(0);setPlaying(true);}}} style={{padding:'4px 10px',borderRadius:5,fontSize:12,fontWeight:700,cursor:'pointer',background:playing?'rgba(200,160,0,0.15)':'rgba(100,255,100,0.1)',border:playing?'1px solid rgba(200,160,0,0.3)':'1px solid rgba(100,255,100,0.2)',color:playing?'#cc0':'#0c0'}}>{playing?'暂停':'播放'}</button>
        <button onClick={()=>{setPlaying(false);setPlayTime(0);const cam=getTrackCamera(0);if(cam&&activeCamRef.current)activeCamRef.current.position.copy(cam.pos);}} style={{padding:'4px 10px',borderRadius:5,fontSize:12,cursor:'pointer',background:'rgba(255,80,80,0.08)',border:'1px solid rgba(255,80,80,0.2)',color:'#c44'}}>停止</button>
        <button onClick={()=>{const t=playTime||0;const p=activeCamRef.current?.rotation.x||0;const y=activeCamRef.current?.rotation.y||0;const sk={time:t,speed:1};const rk={time:t,pitch:p,yaw:y};setRig({...rig,speedCurve:[...rig.speedCurve.filter(x=>Math.abs(x.time-t)>0.3),sk].sort((a,b)=>a.time-b.time),rotationKeys:[...rig.rotationKeys.filter(x=>Math.abs(x.time-t)>0.3),rk].sort((a,b)=>a.time-b.time)});}} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(100,180,255,0.12)',border:'1px solid rgba(100,180,255,0.25)',color:'#a0c8ff'}}>+关键帧</button><button onClick={()=>{const t=playTime||0;const sk={time:t,speed:5};setRig({...rig,speedCurve:[...rig.speedCurve.filter(x=>Math.abs(x.time-t)>0.3),sk].sort((a,b)=>a.time-b.time)});}} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(255,140,60,0.12)',border:'1px solid rgba(255,140,60,0.25)',color:'#ffaa66'}}>▶▶ 极快</button><button onClick={()=>{const t=playTime||0;const sk={time:t,speed:0.15};setRig({...rig,speedCurve:[...rig.speedCurve.filter(x=>Math.abs(x.time-t)>0.3),sk].sort((a,b)=>a.time-b.time)});}} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(100,200,180,0.12)',border:'1px solid rgba(100,200,180,0.25)',color:'#88ccbb'}}>▶ 极慢</button>
        <button onClick={()=>{if(!rig||!activeAnimModel)return;if(rig.animTracks.length>=10)return;const colors=['#4488ff','#44cc88','#cc8844','#cc44cc','#88cc44','#4488cc','#cc4444','#44cccc','#8844cc','#cccc44'];const c=colors[rig.animTracks.length%10];setRig({...rig,animTracks:[...rig.animTracks,{modelId:activeAnimModel,start:playTime||0,dur:15,color:c}]});}} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(100,150,255,0.12)',border:'1px solid rgba(100,150,255,0.25)',color:activeAnimModel&&rig?.animTracks.length<10?'#88bbff':'rgba(255,255,255,0.2)'}}>+动画</button>
        <select value={animSpeed} onChange={e=>{animSpeed=Number(e.target.value);}} style={{padding:'2px 4px',borderRadius:4,fontSize:9,background:'rgba(0,0,0,0.3)',border:'1px solid rgba(255,255,255,0.1)',color:'#ccc',cursor:'pointer'}}><option value={0.3}>0.3x</option><option value={0.5}>0.5x</option><option value={0.7}>0.7x</option><option value={1}>1x</option><option value={1.5}>1.5x</option><option value={2}>2x</option></select>
        <button onClick={()=>setRig(prev=>prev?{...prev,speedCurve:[],rotationKeys:[],animTracks:[]}:prev)} style={{padding:'4px 10px',borderRadius:5,fontSize:11,cursor:'pointer',background:'rgba(255,100,100,0.08)',border:'1px solid rgba(255,100,100,0.2)',color:'#f88'}}>清除</button>
        <span style={{fontSize:11,color:'#ccc',fontWeight:600,marginLeft:8}}>{(playTime||0).toFixed(1)}s / {rig.duration}s</span>
      </div>
      <div style={{display:'flex',alignItems:'center',gap:4,marginBottom:2}}>
        <span style={{fontSize:8,color:'rgba(255,255,255,0.3)'}}>缩放 {zoom}%</span>
      </div>
      <div style={{position:'relative',height:26,background:'rgba(255,255,255,0.05)',borderRadius:4,cursor:'pointer',overflow:'hidden'}}
        onWheel={e=>{e.preventDefault();setZoom(prev=>Math.max(10,Math.min(100,prev+(e.deltaY<0?10:-10))));}}
        onMouseDown={e=>{if(!rig||playing)return;const r=(e.target as HTMLElement).getBoundingClientRect();const t=((e.clientX-r.left)/r.width)*rig.duration;setPlayTime(Math.max(0,Math.min(rig.duration,t)));}}>
        {(()=>{const fps=30;const frameMs=1/fps;const totalFrames=Math.ceil(rig.duration*fps);const majorEvery=Math.max(1,Math.round(5*(zoom/100)));const ticks=[];for(let f=0;f<=totalFrames;f+=majorEvery){const x=(f/(totalFrames||1))*100;ticks.push(<div key={'t'+f} style={{position:'absolute',left:x+'%',top:0,width:1,height:12,background:'rgba(255,255,255,0.15)'}}/>);}return ticks;})()}
        {zoom>=80&&(()=>{const fps=30;const totalFrames=Math.ceil(rig.duration*fps);const ticks=[];for(let f=0;f<=totalFrames;f++){const x=(f/(totalFrames||1))*100;ticks.push(<div key={'st'+f} style={{position:'absolute',left:x+'%',top:0,width:1,height:6,background:'rgba(255,255,255,0.06)'}}/>);}return ticks;})()}
        <div style={{position:'absolute',left:0,top:0,height:'100%',width:(playTime/Math.max(0.1,rig.duration))*100+'%',background:'rgba(100,180,255,0.15)',borderRight:'2px solid #60a0ff',pointerEvents:'none'}}/>
        {rig.speedCurve&&rig.speedCurve.map((k,i)=><div key={'sk'+i} style={{position:'absolute',left:(k.time/rig.duration)*100+'%',bottom:2,width:8,height:8,background:'#ffcc00',border:'1px solid #222',borderRadius:'50%',transform:'translate(-50%,0)',cursor:'grab',zIndex:2}}
          onMouseDown={ev=>{ev.stopPropagation();ev.preventDefault();const sX=ev.clientX,sT=k.time;const mv=(me)=>{if(!rig)return;const r2=(ev.target as HTMLElement).parentElement!.getBoundingClientRect();const dt=((me.clientX-sX)/r2.width)*rig.duration;const u=[...rig.speedCurve];u[i]={time:Math.max(0,Math.min(rig.duration,sT+dt)),speed:u[i].speed};setRig({...rig,speedCurve:u.sort((a,b)=>a.time-b.time)});};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}
          onContextMenu={ev=>{ev.preventDefault();setRig({...rig,speedCurve:rig.speedCurve.filter((_,j)=>j!==i)});}}/>)}
        {rig.rotationKeys&&rig.rotationKeys.map((k,i)=><div key={'rk'+i} style={{position:'absolute',left:(k.time/rig.duration)*100+'%',top:2,width:6,height:20,background:'#44ff44',borderRadius:2,cursor:'grab',zIndex:2}}
          onMouseDown={ev=>{ev.stopPropagation();ev.preventDefault();const sX=ev.clientX,sT=k.time;const mv=(me)=>{if(!rig)return;const r2=(ev.target as HTMLElement).parentElement!.getBoundingClientRect();const dt=((me.clientX-sX)/r2.width)*rig.duration;const u=[...rig.rotationKeys];u[i]={...u[i],time:Math.max(0,Math.min(rig.duration,sT+dt))};setRig({...rig,rotationKeys:u.sort((a,b)=>a.time-b.time)});};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}
          onContextMenu={ev=>{ev.preventDefault();setRig({...rig,rotationKeys:rig.rotationKeys.filter((_,j)=>j!==i)});}}/>)}
      </div>
      {rig.animTracks.map((trk,i)=><div key={i} style={{position:'relative',height:24,background:'rgba(68,136,255,0.05)',border:'1px solid '+trk.color+'44',borderRadius:3,overflow:'visible',marginTop:3}}>
        <span style={{position:'absolute',left:4,top:3,fontSize:9,color:trk.color,pointerEvents:'none',fontWeight:600}}>角色{i+1}</span>
        <div style={{position:'absolute',left:(trk.start/rig.duration)*100+'%',width:(trk.dur/rig.duration)*100+'%',top:3,height:18,background:trk.color+'40',border:'1px solid '+trk.color,borderRadius:3,pointerEvents:'none',zIndex:1}}/>
        <div style={{position:'absolute',left:(trk.start/rig.duration)*100+'%',top:3,width:10,height:18,background:trk.color,borderRadius:3,cursor:'ew-resize',zIndex:2,boxShadow:'0 0 4px rgba(0,0,0,0.5)'}} onMouseDown={ev=>{ev.stopPropagation();ev.preventDefault();const sX=ev.clientX,sT=trk.start;const mv=(me)=>{if(!rig)return;const r2=(ev.target as HTMLElement).parentElement!.getBoundingClientRect();const dt=((me.clientX-sX)/r2.width)*rig.duration;const u=[...rig.animTracks];u[i]={...u[i],start:Math.max(0,Math.min(rig.duration,Math.min(sT+dt,trk.start+trk.dur-0.1)))};setRig({...rig,animTracks:u});};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}}/>
        <div style={{position:'absolute',left:((trk.start+trk.dur)/rig.duration)*100+'%',top:3,width:10,height:18,background:trk.color,borderRadius:3,cursor:'ew-resize',zIndex:2,boxShadow:'0 0 4px rgba(0,0,0,0.5)'}} onMouseDown={ev=>{ev.stopPropagation();ev.preventDefault();const sX=ev.clientX,sD=trk.dur;const mv=(me)=>{if(!rig)return;const r2=(ev.target as HTMLElement).parentElement!.getBoundingClientRect();const dt=((me.clientX-sX)/r2.width)*rig.duration;const u=[...rig.animTracks];u[i]={...u[i],dur:Math.max(0.1,Math.min(rig.duration-trk.start,sD+dt))};setRig({...rig,animTracks:u});};const up=()=>{window.removeEventListener('mousemove',mv);window.removeEventListener('mouseup',up);};window.addEventListener('mousemove',mv);window.addEventListener('mouseup',up);}} onContextMenu={ev=>{ev.preventDefault();setRig({...rig,animTracks:rig.animTracks.filter((_,j)=>j!==i)});}}/>
      </div>)}
    </div>}
    <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:20,padding:'5px 16px',borderTop:'1px solid rgba(255,255,255,0.06)',flexShrink:0,fontSize:10,color:'rgba(255,255,255,0.2)',background:'rgba(0,0,0,0.15)'}}><span>左键选中</span><span>移动/旋转/缩放</span><span>右键视角</span><span>Esc取消</span><span>Ctrl+Z撤销</span></div>
  </div>,document.body);
}

const NODE_W=500,NODE_H=300;
export function Scene3DNode({id,data,selected}:{id:string;data:{title?:string;isConnecting?:boolean;isConnectTarget?:boolean;multiSelect?:boolean;isPickMode?:boolean;isPickTarget?:boolean;onChange?:(p:Record<string,unknown>)=>void;};selected?:boolean;}){
  const[objects,setObjects]=useState<SceneObject[]>([]);
  const[loaded,setLoaded]=useState(false);
  const[selId,setSelId]=useState<string|null>(null);const[fs,setFs]=useState(false);const[gizmoMode,setGizmoMode]=useState<GizmoMode>('translate');
  const[rig,setRig]=useState<CameraRig|null>(null);const ctr=useRef(Date.now());
  useEffect(()=>{if(loaded)return;let tries=0;const tryLoad=()=>{tries++;const store=useCanvasStore.getState();const node=store.nodes.get(id);if(!node&&tries<30){setTimeout(tryLoad,100);return;}const m=(node?.meta as any)?.scene3d;if(m?.objects&&m.objects.length>0){const seen=new Set();const deduped=m.objects.filter((o:any)=>seen.has(o.id)?false:(seen.add(o.id),true));setObjects(deduped);let maxId=0;deduped.forEach((o:any)=>{const n=parseInt(o.id?.split('_')[1]);if(n>maxId)maxId=n;});_oid=Math.max(_oid,maxId,1000);if(m?.rig)setRig(m.rig);}setLoaded(true);};tryLoad();},[id,loaded]);
  useEffect(()=>{if(!loaded)return;const seen=new Set();const deduped=objects.filter(o=>seen.has(o.id)?false:(seen.add(o.id),true));if(deduped.length<objects.length)setObjects(deduped);const store=useCanvasStore.getState();store.updateNode(id,{meta:{...((data as any)?.meta||{}),scene3d:{objects:deduped,rig}}});},[objects,rig,id,loaded]);
  useEffect(()=>{initPoseRegistry();},[]);
  useEffect(()=>{const h=(e:Event)=>{const{id,position,rotation,scale}=(e as CustomEvent).detail as{id:string;position:Vec3;rotation?:Vec3;scale?:Vec3};const obj=objects.find(o=>o.id===id);const minY=obj&&(obj.type==='figure'||obj.type==='plane')?0:0.5;const p:Vec3=position[1]<minY?[position[0],minY,position[2]]:position;setObjects(prev=>prev.map(o=>o.id===id?{...o,position:p,rotation:rotation||o.rotation,scale:scale||o.scale}:o));};window.addEventListener('scene3d-object-moved',h);return()=>window.removeEventListener('scene3d-object-moved',h);},[objects]);
  const addObj=useCallback((type:SceneObject['type'])=>{_oid++;const first=poseRegistry.size>0?poseRegistry.keys().next().value as string:'stand1';const obj:SceneObject={id:`o_${_oid}`,type,position:[0,0.5,0],rotation:[0,0,0],scale:[1,1,1],color:pickColor(),figurePose:type==='figure'?first:undefined,figureSrc:type==='figure'?poseRegistry.get(first)?.src:undefined,figureFmt:type==='figure'?poseRegistry.get(first)?.format:undefined};setObjects(prev=>[...prev,obj]);setSelId(obj.id);},[]);
  const delSel=useCallback(()=>{if(!selId)return;setObjects(prev=>prev.filter(o=>o.id!==selId));setSelId(null);},[selId]);
  const hSnap=useCallback(()=>{const c=document.querySelector('canvas');if(!c)return;const u=c.toDataURL('image/png');const store=useCanvasStore.getState();const n=store.nodes.get(id);if(n){const m=(n.meta||{})as Record<string,unknown>;store.updateNode(id,{meta:{...m,gen:{...((m.gen as Record<string,unknown>)||{}),imageUrl:u}}});store.triggerSync();}},[id]);
  return(<>{fs&&<FullscreenEditor objects={objects} selectedId={selId} setObjects={setObjects} setSelectedId={setSelId} onSnapshot={hSnap} onClose={()=>setFs(false)} nodeId={id} rig={rig} setRig={setRig}/>}
    <div style={{width:NODE_W,height:NODE_H,position:'relative',background:selected?'rgba(200,210,225,0.5)':'#1e1e24',backdropFilter:selected?'blur(14px)':'none',border:selected?'1px solid rgba(255,255,255,0.2)':'1px solid rgba(255,255,255,0.06)',borderRadius:16,overflow:'hidden',boxShadow:selected?'0 0 24px rgba(0,0,0,0.4)':'0 4px 16px rgba(0,0,0,0.2)',transition:'all 0.2s ease',display:'flex',alignItems:'center',justifyContent:'center'}}>
      <div onClick={()=>setFs(true)} className="nodrag" style={{padding:'10px 32px',borderRadius:24,background:'rgba(255,255,255,0.15)',backdropFilter:'blur(8px)',border:'1px solid rgba(255,255,255,0.15)',cursor:'pointer'}}>
        <span style={{fontSize:14,fontWeight:500,color:selected?'rgba(20,20,30,0.7)':'rgba(255,255,255,0.4)',letterSpacing:'0.02em'}}>点击进入3D世界</span>
      </div>
      <Handle type="target" position={Position.Left} id="image-in" style={{background:'rgba(180,180,200,0.4)',width:9,height:9,border:'none',borderRadius:5}}/>
      <Handle type="source" position={Position.Right} id="image-out" style={{background:'rgba(180,180,200,0.4)',width:9,height:9,border:'none',borderRadius:5}}/>
    </div>
  </>);
}